import { RELEASE_AUTHORITY_CANONICAL_DOC } from "@/lib/release-authority/config";
import type { ReleaseAuthoritySurfaceDefinition } from "@/lib/release-authority/types";

export const RELEASE_AUTHORITY_SURFACES: ReleaseAuthoritySurfaceDefinition[] = [
  // Keep the V4 operator-coherence surface inventory explicit so canonical
  // docs and runtime reports stay in lockstep through docs-only follow-up work.
  {
    id: "operating_mode",
    label: "Operating Mode",
    area: "commercial",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/legacy-page.tsx", label: "Meta page" },
      // Operating mode now renders in the redesign pulse strip (Mode cell);
      // the legacy card component is dead code (no importer).
      { kind: "component", path: "components/meta/redesign/MetaPlatformPage.tsx", label: "Meta Decision Center (pulse Mode cell)" },
      { kind: "component", path: "components/creatives/creative-commercial-context-card.tsx", label: "Creative commercial context" },
      { kind: "api", path: "app/api/business-operating-mode/route.ts", label: "Operating mode route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-02-operating-modes.md", label: "Phase 02 operating modes" },
    ],
    notes: [
      "Deterministic commercial-truth overlay remains live.",
      "No feature flag gates the current operating mode surface.",
    ],
  },
  {
    id: "recommendations",
    label: "Recommendations",
    area: "meta",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/legacy-page.tsx", label: "Meta page" },
      // Recommendations render as Decision Center lanes in the redesign;
      // the legacy panel component is dead code (no importer).
      { kind: "component", path: "components/meta/redesign/MetaPlatformPage.tsx", label: "Meta Decision Center lanes" },
      { kind: "api", path: "app/api/meta/recommendations/route.ts", label: "Recommendations route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-03-meta-decision-os.md", label: "Phase 03 Meta Decision OS" },
    ],
    notes: [
      "The compatibility route remains live, but the visible panel now renders secondary workflow/context notes derived from the Meta Decision OS authority snapshot.",
      "This surface no longer carries an independent decision voice.",
    ],
  },
  {
    id: "meta_decision_os",
    label: "Meta Decision OS",
    area: "meta",
    repositoryState: "merged",
    runtimeState: "legacy",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/legacy-page.tsx", label: "Meta page" },
      { kind: "component", path: "lib/archive/v1-v2-v21/components/meta/meta-decision-os.tsx", label: "Archived Decision OS overview" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/meta/decision-os/route.ts", label: "Archived Meta Decision OS route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-03-meta-decision-os.md", label: "Phase 03 Meta Decision OS" },
      { kind: "doc", path: "docs/phase-03-meta-action-contract.md", label: "Phase 03 action contract" },
    ],
    notes: [
      "Legacy Meta Decision OS is archived in Phase 4.1 and no longer has serving runtime posture.",
      "The Meta page keeps snapshot-backed recommendations as context without importing archived authority code.",
      "Archived source, route, and UI files remain available under lib/archive/v1-v2-v21/ for R&D reference.",
    ],
  },
  {
    id: "creative_decision_os",
    label: "Creative Decision OS",
    area: "creative",
    repositoryState: "merged",
    runtimeState: "legacy",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/creatives/legacy-page.tsx", label: "Creatives page" },
      { kind: "component", path: "lib/archive/v1-v2-v21/components/creatives/CreativeDecisionOsOverview.tsx", label: "Archived Creative Decision OS overview" },
      { kind: "component", path: "lib/archive/v1-v2-v21/components/creatives/CreativeDecisionOsDrawer.tsx", label: "Archived Creative Decision OS drawer" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/creatives/decision-os/route.ts", label: "Archived Creative Decision OS route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "component", path: "lib/archive/v1-v2-v21/lib/creative-decision-os.ts", label: "Archived creative decision OS source" },
      { kind: "doc", path: "docs/phase-04-creative-action-contract.md", label: "Phase 04 action contract" },
      { kind: "doc", path: "docs/v2-08-historical-intelligence.md", label: "V2-08 historical intelligence" },
    ],
    notes: [
      "Legacy Creative Decision OS V1/V2/V2.1 surfaces are archived in Phase 4.1.",
      "Active creative authority lives in lib/creative-decision-engine/ and is tracked separately.",
      "Archived source, route, and UI files remain available under lib/archive/v1-v2-v21/ for R&D reference.",
    ],
  },
  {
    id: "decision_signals",
    label: "Decision Signals Compatibility",
    area: "legacy",
    repositoryState: "merged",
    runtimeState: "legacy",
    docsState: "current",
    references: [
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/creatives/decisions/route.ts", label: "Archived Decision Signals route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-04-creative-action-contract.md", label: "Phase 04 action contract" },
    ],
    notes: [
      "The legacy Decision Signals route is archived with the retired creative engines.",
      "No serving route remains for this compatibility surface after Phase 4.1.",
    ],
  },
  {
    id: "ai_commentary",
    label: "AI Commentary",
    area: "creative",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/creatives/legacy-page.tsx", label: "Creatives page" },
      { kind: "component", path: "components/creatives/CreativeDetailExperience.tsx", label: "Creative detail experience" },
      { kind: "api", path: "app/api/ai/creatives/commentary/route.ts", label: "AI commentary route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-04-creative-action-contract.md", label: "Phase 04 creative action contract" },
    ],
    notes: [
      "AI commentary remains bounded interpretation only.",
      "This authority layer only inventories the surface; it does not change provenance rules.",
    ],
  },
  {
    id: "command_center_workflow",
    label: "Command Center Workflow",
    area: "workflow",
    repositoryState: "merged",
    runtimeState: "legacy",
    docsState: "current",
    references: [
      { kind: "page", path: "lib/archive/v1-v2-v21/app/(dashboard)/command-center/page.tsx", label: "Archived Command Center page" },
      { kind: "component", path: "lib/archive/v1-v2-v21/components/command-center/CommandCenterDashboard.tsx", label: "Archived Command Center dashboard" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/route.ts", label: "Archived Command Center route" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/actions/route.ts", label: "Archived workflow mutation route" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/actions/batch/route.ts", label: "Archived batch mutation route" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/feedback/route.ts", label: "Archived feedback route" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/views/route.ts", label: "Archived saved views route" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/handoffs/route.ts", label: "Archived handoffs route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-05-command-center.md", label: "Phase 05 command center" },
      { kind: "doc", path: "docs/phase-05-action-queue-contract.md", label: "Phase 05 action queue contract" },
      { kind: "doc", path: "docs/v2-06-command-center-throughput.md", label: "V2-06 throughput baseline" },
      { kind: "doc", path: "docs/v2-06-release-checklist.md", label: "V2-06 release checklist" },
      { kind: "doc", path: "docs/v2-06-rollout-runbook.md", label: "V2-06 rollout runbook" },
      { kind: "doc", path: "docs/v2-08-historical-intelligence.md", label: "V2-08 historical intelligence" },
    ],
    notes: [
      "Legacy Command Center workflow is archived in Phase 4.1.",
      "No serving workflow routes or dashboard components remain outside lib/archive/v1-v2-v21/.",
    ],
  },
  {
    id: "command_center_execution_preview",
    label: "Command Center Execution Preview",
    area: "execution",
    repositoryState: "merged",
    runtimeState: "legacy",
    docsState: "current",
    references: [
      { kind: "page", path: "lib/archive/v1-v2-v21/app/(dashboard)/command-center/page.tsx", label: "Archived Command Center page" },
      { kind: "component", path: "lib/archive/v1-v2-v21/components/command-center/CommandCenterDashboard.tsx", label: "Archived execution panel" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/execution/route.ts", label: "Archived execution preview route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-06-safe-execution-layer.md", label: "Phase 06 safe execution layer" },
      { kind: "doc", path: "docs/phase-06-executor-contract.md", label: "Phase 06 execution contract" },
      { kind: "doc", path: "docs/v2-07-safe-execution-proof.md", label: "V2-07 safe execution proof" },
    ],
    notes: [
      "Legacy Command Center execution preview is archived in Phase 4.1.",
      "Archived execution files remain available under lib/archive/v1-v2-v21/ for R&D reference.",
    ],
  },
  {
    id: "command_center_execution_apply_rollback",
    label: "Command Center Apply & Rollback",
    area: "execution",
    repositoryState: "merged",
    runtimeState: "legacy",
    docsState: "current",
    references: [
      { kind: "page", path: "lib/archive/v1-v2-v21/app/(dashboard)/command-center/page.tsx", label: "Archived Command Center page" },
      { kind: "component", path: "lib/archive/v1-v2-v21/components/command-center/CommandCenterDashboard.tsx", label: "Archived execution panel" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/execution/apply/route.ts", label: "Archived apply route" },
      { kind: "api", path: "lib/archive/v1-v2-v21/app/api/command-center/execution/rollback/route.ts", label: "Archived rollback route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-06-safe-execution-layer.md", label: "Phase 06 safe execution layer" },
      { kind: "doc", path: "docs/phase-06-rollout-runbook.md", label: "Phase 06 rollout runbook" },
      { kind: "doc", path: "docs/v2-07-safe-execution-proof.md", label: "V2-07 safe execution proof" },
      { kind: "doc", path: "docs/v2-07-release-checklist.md", label: "V2-07 release checklist" },
      { kind: "doc", path: "docs/v2-07-rollout-runbook.md", label: "V2-07 rollout runbook" },
    ],
    notes: [
      "Legacy Command Center apply and rollback routes are archived in Phase 4.1.",
      "No serving apply or rollback route remains outside lib/archive/v1-v2-v21/.",
    ],
  },
  {
    id: "copies",
    label: "/platforms/meta/copies",
    area: "copy",
    repositoryState: "merged",
    runtimeState: "live",
    docsState: "current",
    references: [
      { kind: "page", path: "app/(dashboard)/platforms/meta/copies/legacy-page.tsx", label: "Copies page" },
      { kind: "api", path: "app/api/meta/copies/route.ts", label: "Copies route" },
      { kind: "doc", path: RELEASE_AUTHORITY_CANONICAL_DOC, label: "V3-01 authority doc" },
      { kind: "doc", path: "docs/phase-04-creative-action-contract.md", label: "Phase 04 creative action contract" },
      { kind: "doc", path: "docs/phase-05-command-center.md", label: "Phase 05 command center" },
      { kind: "doc", path: "docs/phase-06-safe-execution-layer.md", label: "Phase 06 safe execution layer" },
    ],
    notes: [
      "The surface remains live and intentionally unchanged in this phase.",
      "Authority coverage is explicit so /platforms/meta/copies cannot disappear into baseline ambiguity.",
    ],
  },
];
