/**
 * Zero-base product copy, EN and TR.
 *
 * Why a dedicated catalogue rather than adding to `lib/i18n.ts`: that dictionary
 * belongs to the legacy console and its shape (navigation/common groups) does
 * not describe these surfaces. The rules it establishes are honoured here —
 * `AppLanguage` is the same type, English is the same explicit fallback, and
 * `NON_TRANSLATABLE_TERMS` are preserved verbatim in both languages.
 *
 * The glossary rule matters and is enforced by test rather than by convention.
 * `ROAS`, `CTR`, `CPA`, `Meta`, `Google Ads`, `GA4`, `Shopify`, `Klaviyo` and
 * the rest are provider and metric identifiers. An operator reading a Turkish
 * surface still types "ROAS" into a spreadsheet and still sees "Meta" in the
 * provider's own UI; translating them would break the join between what this
 * product says and what every other system says.
 *
 * Turkish is longer than English for the same idea — roughly a fifth to a third
 * more characters. That is what the real-length test exists to catch: a label
 * that fits at 320 px in English and clips in Turkish is a defect in the layout,
 * not in the translation.
 */
import { NON_TRANSLATABLE_TERMS, type AppLanguage } from "@/lib/i18n";

export const ZERO_BASE_COPY = {
  en: {
    /* ------------------------------------------------------------- states */
    loading: "Loading…",
    notServed: "Not served",
    notReported: "Not reported",
    unavailable: "Unavailable",
    retry: "Retry",
    cancel: "Cancel",
    save: "Save",
    close: "Close",
    settings: "Settings",
    settingsSplitNote:
      "Settings is now two places, because your account and this business are two different things. Both are below.",
    accountAndSecurity: "Account & security",
    accountAndSecurityDetail:
      "Your name, email, password and the sessions you are signed in on.",
    businessSettings: "Business settings",
    businessSettingsDetail:
      "Workspace name, currency, economics, operating mode and deletion.",
    clientsAlphabeticalWithheld: "Clients are listed alphabetically, and totals across them are withheld.",
    whatsWithheldAndWhy: "What's withheld and why",
    action: "Action",
    details: "Details",
    chooseSite: "Choose site",
    resend: "Re-send",
    withdraw: "Withdraw",
    noPrioritiesServed: "No priorities were served for this window.",
    activityJournal: "Activity journal",
    economicsContext: "Economics context",
    spendRoasTrend: "Spend & ROAS trend",
    returnOnAdSpend: "Return on ad spend",
    spend: "Spend",
    keepCurrentState: "Keep the current state",
    switchBusiness: "Switch business",
    switchScope: "Switch scope",
    agencyDesk: "Agency Desk",
    client: "Client",
    chooseAnAccount: "Choose an account",
    scopeLabel: "Scope",
    englishCaptions: "English",
    confirmBatch: "Check this batch",
    batchIsReferenceOnly: "This checks the selection against the batch rules. Nothing is sent to Google.",
    served: "Served",
    all: "All",
    batchPartiallyApplied: "Some steps in this batch were applied and some were not. Neither word describes the batch as a whole.",
    planTrustNote:
      "Every step above is carried out by hand in Google Ads; nothing here changes an account. What was read to produce them is named on each step, and what could not be verified is stated rather than omitted.",
    fixThis: "Fix this",
    breakdown: "Breakdown",
    sourceContractsNote: "Each source states what it can break down by. A source that cannot answer a breakdown says so here, before it is added.",
    portfolioMode: "Portfolio mode — totals are withheld when accounts disagree on currency",
    evidenceWindow: "Evidence window",
    asOf: "As of",
    gaps: "Gaps",
    openTheBrief: "Open the brief",
    shareThisView: "Share this view",
    demotedLowConfidence: "Demoted: served with low confidence.",
    themeAcceptance: "Theme acceptance",
    themeAcceptanceNote: "Every semantic colour and surface, each stating its meaning in words as well as colour.",
    semanticColours: "Semantic colours",
    surfaces: "Surfaces",
    startTriage: "Start triage",
    connectThisSource: "Connect this source",
    automationMode: "Automation mode",
    dismiss: "Dismiss",
    runAnalysis: "Run analysis",
    copy: "Copy",
    goBackToClient: "Go back to that client",
    openManualAction: "Open manual action",
    shareThisCreative: "Share this creative",
    backToCreatives: "Back to creatives",
    runSnapshot: "Run a snapshot",
    queued: "Queued…",
    snapshotQueuedNote: "Queued. Its progress appears as a fact below when the run reports.",
    recordResponse: "Record a response",
    preset: "Preset",
    sort: "Sort by",
    actionState: "Action state",
    horizon: "Horizon",
    // Not "Search history": capitalised Search is the Google Ads campaign type
    // in the glossary, and this is the verb.
    searchHistory: "Find in history",
    historySearchIsServerSide: "Searches the whole history, not only the rows loaded here.",
    outcome: "Outcome",
    replay: "Replay",
    notAvailable: "Not available",
    emailChangeReverifies: "Changing this sends a verification email to the new address.",
    passwordStrengthHint: "At least 12 characters. Length matters more than symbols.",
    public: "Public",
    product: "Product",
    pricing: "Pricing",
    contact: "Contact",
    signIn: "Sign in",
    signingIn: "Signing in…",
    capsLockOn: "Caps Lock is on.",
    continueWithGoogle: "Continue with Google",
    continueWithFacebook: "Continue with Facebook",
    forgotPassword: "Forgot password?",
    createAccount: "Create an account",
    exploreDemo: "Explore the demo",

    keyboardMode: "Keyboard mode",
    done: "Done",
    edit: "Edit",
    delete: "Delete",
    playing: "Playing",
    paused: "Paused",
    cardPosition: "Card {index} of {total}",
    scopeServedNote: "Every value above is served — nothing is recomputed on the client.",
    undo: "Undo",

    /* -------------------------------------------------------- collections */
    noRows: "No rows were served for this period.",
    capDisclosureUnknownTotal: "The backend did not supply a total.",

    /* --------------------------------------------------------- provenance */
    connected: "Connected",
    notConnected: "Not connected",
    connectionUnknown: "The integration status could not be read, so this connection is unknown.",

    /* -------------------------------------------------------------- verbs */
    connect: "Connect",
    reconnect: "Reconnect",
    exportCsv: "Export CSV",

    /* ------------------------------------------------------------ refusal */
    needsCollaborator:
      "Connecting or reconnecting a provider needs the collaborator role.",
    needsAdmin: "This needs the admin role.",

    /* ------------------------------------------------------------ reports */
    reportsTitle: "Reports",
    newReport: "New report",
    reportName: "Report name",
    noReports: "No reports have been created for this business yet.",

    /* --------------------------------------------------------------- team */
    teamTitle: "Team",
    members: "Members",
    invitations: "Invitations",
    accessRequests: "Access requests",

    /* ----------------------------------------------------------- workflow */
    workingOnIt: "Working…",
    confirmedByFreshRead: "Saved and confirmed by a fresh read.",
    reReadFailed:
      "The change was accepted but the confirming read failed, so the current state is unknown.",
    reReadDisagreed:
      "The change was accepted but the re-read does not show it. Treat it as unresolved.",

    /* ------------------------------------------------------------ manage */
    saveSelection: "Save selection",
    assignedAccounts: "Assigned accounts",
    provider: "Provider",
    saveAssignment: "Save assignment",
    remove: "Remove",
    sendInvitations: "Send invitations",
    revoke: "Revoke",
    approve: "Approve",
    reject: "Reject",
    workspaceSettings: "Workspace settings",
    settingsUnreadable: "The current name and currency could not be read, so they are not shown.",
    saveSettings: "Save settings",
    economics: "Economics",
    economicsAgree: "The economics sources in scope agree.",
    recommendedMode: "Recommended mode",
    deleteThisBusiness: "Delete this business",
    deleteBusiness: "Delete business",
    integrations: "Integrations",
    providerConnections: "Provider connections",
    ga4Property: "Google Analytics 4 property",
    searchConsoleSite: "Search Console site",
    accountAssignment: "Account assignment",
    teamMembers: "Team members",
    emailAddresses: "Email addresses",
    emailsHint: "Comma separated. The route refuses an empty list.",
    pendingInvitations: "Pending invitations",
    business: "Business",
    workspaceName: "Workspace name",
    workspaceNameHint: "At least two characters — the route refuses anything shorter.",
    currency: "Currency",
    currencyHint: "Required on every save; the route takes name and currency together.",
    economicsSources: "Economics sources",
    operatingMode: "Operating mode",
    plan: "Plan",
    chooseOption: "Choose…",

    /* ------------------------------------------------- reports & builder */
    duplicate: "Duplicate",
    reportBuilder: "Report builder",
    sources: "Sources",
    canvas: "Canvas",
    retryNotMarked: "The renderer did not mark this failure as retryable.",
    sharing: "Sharing",
    sharingUnavailable:
      "Report sharing is not available from this product. There is no control here to mint a link.",
    name: "Name",
    reportNameHint: "Required — both save routes refuse a report without one.",
    reportCanvas: "Report canvas",

    /* ---------------------------------------------------------- analytics */
    newVsReturning: "New vs returning",
    latestAiInsight: "Latest AI insight",
    readsLatestInsight: "This surface reads the latest insight. It does not generate one.",
    servedBriefReadOnly: "Served brief, read only. This surface generates nothing.",
    aiVisitedPages: "AI-visited pages",
    valueAtCap: "This value is at the cap.",
    topPriorities: "Top priorities",
    ga4Kpis: "GA4 KPIs",
    searchPerformance: "Search Console performance",
    leadingQueries: "Leading queries",
    decliningQueries: "Declining queries",
    likelyCauses: "Likely causes",
    recommendations: "Recommendations",
    aiPageReach: "AI page reach",
    priorities: "Priorities",

    /* ---------------------------------------------------------- launchpad */
    whatWorksToday: "What works today",
    launch: "Launch",
    drafts: "Drafts",
    noDrafts: "No drafts have been saved for this account.",
    saveDraft: "Save draft",
    validation: "Validation",
    validationSilent: "Validation reported nothing for this draft.",
    goToFirstProblem: "Go to the first problem",
    runValidation: "Run validation",
    templates: "Templates",
    deleteItem: "Delete",
    bulkAdStatus: "Bulk ad status",
    execution: "Execution",
    newDraftName: "New draft name",
    adName: "Ad name",
    launchpadTemplates: "Launchpad templates",

    /* ------------------------------------------- creative, meta, ops */
    createBriefFromCreative: "Create brief from this creative",
    createAShare: "Create a share",
    audience: "Audience",
    createShare: "Create share",
    rotateLink: "Rotate link",
    creativeBriefs: "Creative briefs",
    landingPages: "Landing pages",
    shares: "Shares",
    title: "Title",
    expiresAt: "Expires at",
    shareLedger: "Share ledger",
    workflowUnknown: "Workflow unknown",
    assigned: "Assigned",
    promise: "Promise",
    workflow: "Workflow",
    history: "History",
    nothingRecordedDecision: "Nothing has been recorded for this decision yet.",
    assigneeUserId: "Assignee (user id)",
    mustBeActiveMember: "Must be an active member of this business.",
    wakeUpAt: "Wake up at",
    snoozeReturns: "A snooze that has elapsed returns the decision to the queue.",
    reasonCode: "Reason code",
    rejectionCarriesReason: "Rejecting the engine's call always carries a reason.",
    dueOptional: "Due (optional)",
    creative: "Creative",
    creativeIntelligence: "Creative Intelligence",
    metaScoped: "META-SCOPED",
    campaignNotServed: "Campaign not served",
    noEngineVerdict: "No engine verdict",
    targetNotServed: "target not served",
    purchases: "Purchases",
    status: "Status",
    decision: "Decision",
    openInDecisions: "Open in Decisions",
    evidence: "Evidence",
    noEvidenceServed: "No evidence fields were served for this creative.",
    nothingRecordedCreative: "Nothing has been recorded for this creative yet.",
    replayed: "Replayed",
    recordedAtTheTime: "Recorded at the time",
    creativeHistory: "Creative history",
    email: "Email",
    password: "Password",
    sessions: "Sessions",
    revokeOtherSessions: "Revoke other sessions",
    revokeThisSession: "Revoke this session",
    theme: "Theme",
    currentPassword: "Current password",
    newPassword: "New password",
    revokeOtherSessionsQ: "Revoke other sessions?",
    revokeThisSessionQ: "Revoke this session?",
    yourPlan: "Your plan",
    carryOutInGoogle: "Carry these out in Google Ads yourself. Nothing on this page changes anything in Google.",
    downloadCsv: "Download CSV",
    open: "Open",
    activity: "Activity",
    referenceNotEnabled: "Reference — not enabled",
    checkThisSelection: "Check this selection",
    googlePlan: "Google plan",
    manualPlan: "Manual plan",
    googleManualPlan: "Google manual plan",
    googleReadOnlyPlanNote: "Google rows are read-only here. Every change remains recommendation-bound in the manual plan.",
    viewAsTable: "View as table",
    viewAsChart: "View as chart",
    referenceWriteStates: "Reference write states",
    metaDecisions: "Meta Decisions",
    level: "Level",
    verdict: "Verdict",
    scope: "Scope",
    openMetaAdsManager: "Open Meta Ads Manager",
    opensMetaNewTab: "Opens Meta in a new tab. Nothing is changed by following it.",
    findADecision: "Find a decision",
    campaignAdsetOrTitle: "Campaign, ad set or title",
    filtersLaneDecisions: "Filters the decisions served in this lane.",
    decisionLanes: "Decision lanes",
    decisionNoLongerServed: "The decision this link names is no longer served in this lane. It may have aged out of the window or moved lane.",
    run: "Run",
    runIt: "Run it",
    reRunHealthCheck: "Re-run the health check",
    ifSomethingIsFailing: "If something is failing",
    repair: "Repair",
    confirmRepair: "Confirm repair",
    criticalIncidentPath: "Critical incident path",
    controlledHere: "Controlled here",
    notControlledHere: "Not controlled here",
    guardrails: "Guardrails",
    providerPosture: "Provider posture",
    metaStop: "Meta stop",
    automationGuardrails: "Automation guardrails",

    /* --------------------------------------- shell, home, agency, share */
    whereNumbersFrom: "Where these numbers come from",
    eachSourceState: "Each source, its state and when it last updated.",
    source: "Source",
    state: "State",
    lastUpdated: "Last updated",
    sourceHealth: "Source health",
    home: "Home",
    refresh: "Refresh",
    keyMetrics: "Key metrics",
    date: "Date",
    value: "Value",
    skipToMain: "Skip to main content",
    account: "Account",
    language: "Language",
    logOut: "Log out",
    menu: "Menu",
    openNavigation: "Open navigation",
    navigation: "Navigation",
    primary: "Primary",
    agency: "Agency",
    nothingInHorizon: "Nothing in this horizon.",
    googleOverview: "Google overview",
    googleOverviewByAccount: "Google overview by account",
    googleAdvisor: "Google advisor",
    reference: "Reference",
    backToClients: "Back to clients",
    clients: "Clients",
    returnToFirstPage: "Return to first page",
    notRecorded: "Not recorded",
    findAClient: "Find a client",
    filtersLoadedClients: "Filters the clients already loaded on this page.",
    clientsAlphabetical: "Clients, listed alphabetically",
    today: "Today",
    type: "Type",
    clearSearch: "Clear search",
    metaLaunchpad: "Meta Launchpad",
    withheldSafety: "Withheld — safety",
    failed: "Failed",
    nothingToShow: "Nothing to show",
    shopifyWebhookRepair: "Shopify webhook repair",
    workspace: "Workspace",
    noBlockersReported: "This read reported no blockers.",
    noMediaInShare: "No media was included in this share.",
    mediaCouldNotLoad: "This media could not be loaded.",
    tryAgain: "Try again",
    linkNotAvailable: "This link is not available",
    shareHasNoCreatives: "This share contains no creatives.",
    creatives: "Creatives",
    creativePerformance: "Creative performance",
    creativeInbox: "Creative inbox",
    creativeCopies: "Creative copies",
    noPreview: "No preview",
    signedInAsSession: "Signed in on this device as session",
    reportLayout: "Report layout",
    selected: "SELECTED",
    loadMore: "Load more",
    accountIntelligence: "Account Intelligence",
    nothingServed: "Nothing served",
    intelligenceSources: "Intelligence sources",
    manualWrite: "Manual write",
    checkOlderThan15: "That check is older than 15 minutes. Run it again before acting.",
    reCheck: "Re-check",
    metaHistory: "Meta History",
    metaActionHistory: "Meta action history",
    whyAgencyNoTotals: "Why Agency shows no totals",
    findAnything: "Find",
    brandName: "ADSECUTE",
    mediaBuyingOperatingSystem: "The media-buying operating system.",
    adsecuteHome: "Adsecute home",
    profile: "Profile",
    revokeAllSessions: "Revoke all sessions",
    signInEmailReadOnly: "Your sign-in email is verified and cannot be changed from this screen.",
    revokeAllSessionsQ: "Revoke all sessions?",
    aiInsights: "AI Insights",
    trafficSources: "Traffic sources",
    readLatestOnly: "READ LATEST ONLY",
    aiGenerationUnavailable: "Generate is not available here. This surface reads the latest served insight and never invents one in the browser.",
    aiCitedPages: "AI-cited pages",
    sourcesServing: "Sources serving",
    prioritiesServed: "Priorities served",
    audienceSessionComparison: "New and returning audience session comparison",
    audienceCohorts: "Audience cohorts",
    geoSummary: "GEO summary",
    sharedVia: "Shared via",
    created: "Created",
    deletion: "Deletion",
    lineageImmutable: "Not available — lineage is immutable",
    derivedContext: "Derived context",
    diagnostics: "Diagnostics",
    accountScope: "Account scope",
    googleAdsOverviewTitle: "Google Ads — Overview",
    googleKeyMetrics: "Google key metrics",
    campaigns: "Campaigns",
    homeDecisionOrientation: "A decision-oriented view of the business, its efficiency and data readiness.",
    noDailyTrendServed: "No daily trend is served for this window.",
    featureAccessNotBillingGated: "Feature access is not billing-gated.",
    planAndBilling: "Plan & Billing",
    automationReadOnlyNote: "Automation settings are shown read-only. The Meta stop is business-scoped and never affects Google.",
    inactiveAssets: "Inactive assets",
    inactiveAssetsOutsideLanes: "Kept outside decision lanes.",
    accountPulse: "Account pulse",
    workspaceScope: "Workspace scope",
    seoFindings: "SEO — Findings",
    commentary: "Commentary",
    publicShareCommentary:
      "The issuer shared this creative for review. Conclusions remain limited to the figures served in this snapshot.",
    objective: "Objective",
    briefObjectiveDetail:
      "Refresh the served creative direction while preserving the immutable decision and account lineage shown beside this brief.",
    otherBriefs: "Other briefs",
    acknowledgementRequired: "Acknowledgement required",
    briefLifecycle: "Brief lifecycle",
    metaStopEngagedBusiness: "Meta write stop is ENGAGED for this business",
    metaWriteBlockedGoogleUnaffected: "Meta write paths are blocked. Google Ads is unaffected.",
    observed: "Observed",
    actor: "Actor",
    evidenceBasis: "Evidence basis",
    campaignLabels: "Campaign labels",
    campaignLabelsSemanticOnly:
      "Labels are semantic only. They carry no menus and grant no write authority.",
  },

  tr: {
    loading: "Yükleniyor…",
    notServed: "Sunulmadı",
    notReported: "Bildirilmedi",
    unavailable: "Kullanılamıyor",
    retry: "Yeniden dene",
    cancel: "Vazgeç",
    save: "Kaydet",
    close: "Kapat",
    settings: "Ayarlar",
    settingsSplitNote:
      "Ayarlar artık iki ayrı yerde, çünkü hesabınız ile bu işletme iki farklı şey. İkisi de aşağıda.",
    accountAndSecurity: "Hesap ve güvenlik",
    accountAndSecurityDetail:
      "Adınız, e-postanız, parolanız ve oturum açtığınız cihazlar.",
    businessSettings: "İşletme ayarları",
    businessSettingsDetail:
      "Çalışma alanı adı, para birimi, ekonomi, çalışma modu ve silme.",
    clientsAlphabeticalWithheld: "Müşteriler alfabetik sıralanır; aralarındaki toplamlar paylaşılmaz.",
    whatsWithheldAndWhy: "Neyin paylaşılmadığı ve nedeni",
    action: "Eylem",
    details: "Ayrıntılar",
    chooseSite: "Site seç",
    resend: "Yeniden gönder",
    withdraw: "Geri çek",
    noPrioritiesServed: "Bu aralık için öncelik sunulmadı.",
    activityJournal: "Etkinlik günlüğü",
    agencyDesk: "Ajans Masası",
    chooseAnAccount: "Bir hesap seç",
    economicsContext: "Ekonomi bağlamı",
    englishCaptions: "İngilizce",
    keepCurrentState: "Mevcut durumu koru",
    returnOnAdSpend: "Reklam harcaması getirisi",
    scopeLabel: "Kapsam",
    spend: "Harcama",
    spendRoasTrend: "Harcama ve ROAS eğilimi",
    switchBusiness: "İşletme değiştir",
    switchScope: "Kapsam değiştir",

    confirmBatch: "Bu grubu denetle",
    batchIsReferenceOnly: "Bu, seçimi grup kurallarına göre denetler. Google’a hiçbir şey gönderilmez.",
    served: "Sunulan",
    all: "Tümü",
    batchPartiallyApplied: "Bu gruptaki bazı adımlar uygulandı, bazıları uygulanmadı. Hiçbir sözcük grubun tamamını tanımlamıyor.",
    planTrustNote:
      "Yukarıdaki adımlar Google Ads içinde elle uygulanır; burada hiçbir şey hesabı değiştirmez. Her adımın neye dayandığı adımın üzerinde yazar, doğrulanamayan şeyler atlanmaz, açıkça belirtilir.",
    fixThis: "Bunu düzelt",
    breakdown: "Kırılım",
    sourceContractsNote: "Her kaynak hangi kırılımları yanıtlayabildiğini belirtir. Yanıtlayamayan bir kaynak, eklenmeden önce bunu burada söyler.",
    portfolioMode: "Portföy modu — hesaplar para biriminde ayrışıyorsa toplamlar gösterilmez",
    evidenceWindow: "Kanıt aralığı",
    asOf: "Şu ana göre",
    gaps: "Boşluklar",
    openTheBrief: "Brief’i aç",
    shareThisView: "Bu görünümü paylaş",
    demotedLowConfidence: "Düşürüldü: düşük güvenle sunuldu.",
    themeAcceptance: "Tema kabulü",
    themeAcceptanceNote: "Her anlamsal renk ve yüzey; anlamını renkle birlikte sözcükle de belirtir.",
    semanticColours: "Anlamsal renkler",
    surfaces: "Yüzeyler",
    startTriage: "Önceliklendirmeye başla",
    connectThisSource: "Bu kaynağı bağla",
    automationMode: "Otomasyon modu",
    dismiss: "Yoksay",
    runAnalysis: "Analizi çalıştır",
    copy: "Kopyala",
    goBackToClient: "O müşteriye geri dön",
    openManualAction: "Manuel işlemi aç",
    shareThisCreative: "Bu kreatifi paylaş",
    backToCreatives: "Kreatiflere dön",
    runSnapshot: "Anlık görüntü al",
    queued: "Sıraya alındı…",
    snapshotQueuedNote: "Sıraya alındı. İlerlemesi, çalışma rapor verdiğinde aşağıda bir olgu olarak görünür.",
    recordResponse: "Yanıt kaydet",
    preset: "Hazır görünüm",
    sort: "Sıralama",
    actionState: "Eylem durumu",
    horizon: "Ufuk",
    searchHistory: "Geçmişte ara",
    historySearchIsServerSide: "Yalnızca yüklenen satırlarda değil, tüm geçmişte arar.",
    outcome: "Sonuç",
    replay: "Yeniden oynat",
    notAvailable: "Kullanılamıyor",
    emailChangeReverifies: "Bunu değiştirmek yeni adrese bir doğrulama e-postası gönderir.",
    passwordStrengthHint: "En az 12 karakter. Uzunluk, sembollerden daha önemlidir.",
    public: "Genel",
    product: "Ürün",
    pricing: "Fiyatlandırma",
    contact: "İletişim",
    signIn: "Oturum aç",
    signingIn: "Oturum açılıyor…",
    capsLockOn: "Caps Lock açık.",
    continueWithGoogle: "Google ile devam et",
    continueWithFacebook: "Facebook ile devam et",
    forgotPassword: "Parolanızı mı unuttunuz?",
    createAccount: "Hesap oluştur",
    exploreDemo: "Demoyu inceleyin",

    keyboardMode: "Klavye modu",
    done: "Bitti",
    edit: "Düzenle",
    delete: "Sil",
    playing: "Oynatılıyor",
    paused: "Duraklatıldı",
    cardPosition: "Kart {index} / {total}",
    scopeServedNote: "Yukarıdaki her değer sunucudan gelir — istemcide hiçbir şey yeniden hesaplanmaz.",
    undo: "Geri al",

    noRows: "Bu dönem için satır sunulmadı.",
    capDisclosureUnknownTotal: "Arka uç bir toplam sunmadı.",

    connected: "Bağlı",
    notConnected: "Bağlı değil",
    connectionUnknown:
      "Entegrasyon durumu okunamadı, bu nedenle bu bağlantının durumu bilinmiyor.",

    connect: "Bağlan",
    reconnect: "Yeniden bağlan",
    exportCsv: "CSV dışa aktar",

    needsCollaborator:
      "Bir sağlayıcıyı bağlamak veya yeniden bağlamak için collaborator rolü gerekir.",
    needsAdmin: "Bunun için admin rolü gerekir.",

    reportsTitle: "Raporlar",
    newReport: "Yeni rapor",
    reportName: "Rapor adı",
    noReports: "Bu işletme için henüz rapor oluşturulmadı.",

    teamTitle: "Ekip",
    members: "Üyeler",
    invitations: "Davetler",
    accessRequests: "Erişim talepleri",

    workingOnIt: "Çalışıyor…",
    confirmedByFreshRead: "Kaydedildi ve yeni bir okumayla doğrulandı.",
    reReadFailed:
      "Değişiklik kabul edildi ancak doğrulayıcı okuma tamamlanmadı, bu nedenle güncel durum bilinmiyor.",
    reReadDisagreed:
      "Değişiklik kabul edildi ancak yeniden okuma bunu göstermiyor. Çözülmemiş olarak değerlendirin.",

    saveSelection: "Seçimi kaydet",
    assignedAccounts: "Atanmış hesaplar",
    provider: "Sağlayıcı",
    saveAssignment: "Atamayı kaydet",
    remove: "Kaldır",
    sendInvitations: "Davetleri gönder",
    revoke: "İptal et",
    approve: "Onayla",
    reject: "Reddet",
    workspaceSettings: "Çalışma alanı ayarları",
    settingsUnreadable: "Mevcut ad ve para birimi okunamadı, bu nedenle gösterilmiyor.",
    saveSettings: "Ayarları kaydet",
    economics: "Ekonomi",
    economicsAgree: "Kapsamdaki ekonomi kaynakları uyuşuyor.",
    recommendedMode: "Önerilen mod",
    deleteThisBusiness: "Bu işletmeyi sil",
    deleteBusiness: "İşletmeyi sil",
    integrations: "Entegrasyonlar",
    providerConnections: "Sağlayıcı bağlantıları",
    ga4Property: "Google Analytics 4 mülkü",
    searchConsoleSite: "Search Console sitesi",
    accountAssignment: "Hesap ataması",
    teamMembers: "Ekip üyeleri",
    emailAddresses: "E-posta adresleri",
    emailsHint: "Virgülle ayrılmış. Rota boş bir listeyi reddeder.",
    pendingInvitations: "Bekleyen davetler",
    business: "İşletme",
    workspaceName: "Çalışma alanı adı",
    workspaceNameHint: "En az iki karakter — rota daha kısasını reddeder.",
    currency: "Para birimi",
    currencyHint: "Her kayıtta zorunlu; rota adı ve para birimini birlikte alır.",
    economicsSources: "Ekonomi kaynakları",
    operatingMode: "Çalışma modu",
    plan: "Plan (abonelik)",
    chooseOption: "Seçin…",

    duplicate: "Çoğalt",
    reportBuilder: "Rapor oluşturucu",
    sources: "Kaynaklar",
    canvas: "Tuval",
    retryNotMarked: "Oluşturucu bu hatayı yeniden denenebilir olarak işaretlemedi.",
    sharing: "Paylaşım",
    sharingUnavailable:
      "Rapor paylaşımı bu üründe kullanılamıyor. Burada bağlantı üretecek bir kontrol yok.",
    name: "Ad",
    reportNameHint: "Zorunlu — her iki kayıt rotası da adsız raporu reddeder.",
    reportCanvas: "Rapor tuvali",

    newVsReturning: "Yeni ve geri dönen",
    latestAiInsight: "En son AI içgörüsü",
    readsLatestInsight: "Bu yüzey en son içgörüyü okur. Yeni bir içgörü üretmez.",
    servedBriefReadOnly: "Sunulan brief, salt okunur. Bu yüzey hiçbir şey üretmez.",
    aiVisitedPages: "AI tarafından ziyaret edilen sayfalar",
    valueAtCap: "Bu değer üst sınırda.",
    topPriorities: "Öncelikli başlıklar",
    ga4Kpis: "GA4 KPI'ları",
    searchPerformance: "Search Console performansı",
    leadingQueries: "Öne çıkan sorgular",
    decliningQueries: "Gerileyen sorgular",
    likelyCauses: "Olası nedenler",
    recommendations: "Öneriler",
    aiPageReach: "AI sayfa erişimi",
    priorities: "Öncelikler",

    whatWorksToday: "Bugün ne işe yarıyor",
    launch: "Yayına al",
    drafts: "Taslaklar",
    noDrafts: "Bu hesap için kaydedilmiş taslak yok.",
    saveDraft: "Taslağı kaydet",
    validation: "Doğrulama",
    validationSilent: "Doğrulama bu taslak için hiçbir şey bildirmedi.",
    goToFirstProblem: "İlk soruna git",
    runValidation: "Doğrulamayı çalıştır",
    templates: "Şablonlar",
    deleteItem: "Sil",
    bulkAdStatus: "Toplu reklam durumu",
    execution: "Yürütme",
    newDraftName: "Yeni taslak adı",
    adName: "Reklam adı",
    launchpadTemplates: "Launchpad şablonları",

    createBriefFromCreative: "Bu kreatiften brief oluştur",
    createAShare: "Paylaşım oluştur",
    audience: "Kitle",
    createShare: "Paylaşımı oluştur",
    rotateLink: "Bağlantıyı yenile",
    creativeBriefs: "Kreatif brief'leri",
    landingPages: "Açılış sayfaları",
    shares: "Paylaşımlar",
    title: "Başlık",
    expiresAt: "Sona erme",
    shareLedger: "Paylaşım defteri",
    workflowUnknown: "İş akışı bilinmiyor",
    assigned: "Atandı",
    promise: "Taahhüt",
    workflow: "İş akışı",
    history: "Geçmiş",
    nothingRecordedDecision: "Bu karar için henüz hiçbir şey kaydedilmedi.",
    assigneeUserId: "Atanan (kullanıcı kimliği)",
    mustBeActiveMember: "Bu işletmenin aktif bir üyesi olmalıdır.",
    wakeUpAt: "Uyanma zamanı",
    snoozeReturns: "Süresi dolan bir erteleme kararı kuyruğa geri döndürür.",
    reasonCode: "Gerekçe kodu",
    rejectionCarriesReason: "Motorun kararını reddetmek her zaman bir gerekçe taşır.",
    dueOptional: "Termin (isteğe bağlı)",
    creative: "Kreatif",
    creativeIntelligence: "Kreatif Zekâsı",
    metaScoped: "Meta KAPSAMLI",
    campaignNotServed: "Kampanya sunulmadı",
    noEngineVerdict: "Motor kararı yok",
    targetNotServed: "hedef sunulmadı",
    purchases: "Satın almalar",
    status: "Durum",
    decision: "Karar",
    openInDecisions: "Kararlar'da aç",
    evidence: "Kanıt",
    noEvidenceServed: "Bu kreatif için hiçbir kanıt alanı sunulmadı.",
    nothingRecordedCreative: "Bu kreatif için henüz hiçbir şey kaydedilmedi.",
    replayed: "Yeniden oynatıldı",
    recordedAtTheTime: "O anda kaydedildi",
    creativeHistory: "Kreatif geçmişi",
    email: "E-posta",
    password: "Parola",
    sessions: "Oturumlar",
    revokeOtherSessions: "Diğer oturumları sonlandır",
    revokeThisSession: "Bu oturumu sonlandır",
    theme: "Tema",
    currentPassword: "Mevcut parola",
    newPassword: "Yeni parola",
    revokeOtherSessionsQ: "Diğer oturumlar sonlandırılsın mı?",
    revokeThisSessionQ: "Bu oturum sonlandırılsın mı?",
    yourPlan: "Planınız",
    carryOutInGoogle: "Bunları Google Ads içinde kendiniz uygulayın. Bu sayfadaki hiçbir şey Google'da bir değişiklik yapmaz.",
    downloadCsv: "CSV indir",
    open: "Aç",
    activity: "Etkinlik",
    referenceNotEnabled: "Referans — etkin değil",
    checkThisSelection: "Bu seçimi denetle",
    googlePlan: "Google planı",
    manualPlan: "Manuel plan",
    googleManualPlan: "Google manuel planı",
    googleReadOnlyPlanNote: "Google satırları burada salt okunurdur. Her değişiklik manuel plandaki bir öneriye bağlı kalır.",
    viewAsTable: "Tablo olarak göster",
    viewAsChart: "Grafik olarak göster",
    referenceWriteStates: "Referans yazma durumları",
    metaDecisions: "Meta Kararları",
    level: "Seviye",
    verdict: "Karar sonucu",
    scope: "Kapsam",
    openMetaAdsManager: "Meta Ads Manager'ı aç",
    opensMetaNewTab: "Meta'yı yeni bir sekmede açar. Bunu izlemek hiçbir şeyi değiştirmez.",
    findADecision: "Karar ara",
    campaignAdsetOrTitle: "Kampanya, reklam seti veya başlık",
    filtersLaneDecisions: "Bu şeritte sunulan kararları filtreler.",
    decisionLanes: "Karar şeritleri",
    decisionNoLongerServed: "Bu bağlantının adlandırdığı karar artık bu şeritte sunulmuyor. Pencereden düşmüş veya şerit değiştirmiş olabilir.",
    run: "Çalıştır",
    runIt: "Şimdi çalıştır",
    reRunHealthCheck: "Sağlık kontrolünü yeniden çalıştır",
    ifSomethingIsFailing: "Bir şey başarısız oluyorsa",
    repair: "Onarım",
    confirmRepair: "Onarımı doğrula",
    criticalIncidentPath: "Kritik olay yolu",
    controlledHere: "Buradan denetleniyor",
    notControlledHere: "Buradan denetlenmiyor",
    guardrails: "Koruma kuralları",
    providerPosture: "Sağlayıcı duruşu",
    metaStop: "Meta durdurma",
    automationGuardrails: "Otomasyon koruma kuralları",

    whereNumbersFrom: "Bu sayılar nereden geliyor",
    eachSourceState: "Her kaynak, durumu ve en son ne zaman güncellendiği.",
    source: "Kaynak",
    state: "Durum",
    lastUpdated: "Son güncelleme",
    sourceHealth: "Kaynak sağlığı",
    home: "Ana sayfa",
    refresh: "Yenile",
    keyMetrics: "Temel metrikler",
    date: "Tarih",
    value: "Değer",
    skipToMain: "Ana içeriğe geç",
    account: "Hesap",
    language: "Dil",
    logOut: "Çıkış yap",
    menu: "Menü",
    openNavigation: "Gezinmeyi aç",
    navigation: "Gezinme",
    primary: "Birincil",
    agency: "Ajans",
    client: "Müşteri",
    nothingInHorizon: "Bu ufukta hiçbir şey yok.",
    googleOverview: "Google genel bakış",
    googleOverviewByAccount: "Hesaba göre Google genel bakış",
    googleAdvisor: "Google danışmanı",
    reference: "Referans",
    backToClients: "Müşterilere dön",
    clients: "Müşteriler",
    returnToFirstPage: "İlk sayfaya dön",
    notRecorded: "Kaydedilmedi",
    findAClient: "Müşteri ara",
    filtersLoadedClients: "Bu sayfada zaten yüklenmiş müşterileri filtreler.",
    clientsAlphabetical: "Müşteriler, alfabetik sırayla",
    today: "Bugün",
    type: "Tür",
    clearSearch: "Aramayı temizle",
    metaLaunchpad: "Meta Launchpad'i",
    withheldSafety: "Esirgendi — güvenlik",
    failed: "Başarısız",
    nothingToShow: "Gösterilecek bir şey yok",
    shopifyWebhookRepair: "Shopify webhook onarımı",
    workspace: "Çalışma alanı",
    noBlockersReported: "Bu okuma hiçbir engel bildirmedi.",
    noMediaInShare: "Bu paylaşıma hiçbir medya dahil edilmedi.",
    mediaCouldNotLoad: "Bu medya yüklenemedi.",
    tryAgain: "Tekrar deneyin",
    linkNotAvailable: "Bu bağlantı kullanılamıyor",
    shareHasNoCreatives: "Bu paylaşım hiçbir kreatif içermiyor.",
    creatives: "Kreatifler",
    creativePerformance: "Kreatif performansı",
    creativeInbox: "Kreatif gelen kutusu",
    creativeCopies: "Kreatif metinleri",
    noPreview: "Önizleme yok",
    signedInAsSession: "Bu cihazda şu oturumla oturum açıldı",
    reportLayout: "Rapor düzeni",
    selected: "SEÇİLİ",
    loadMore: "Daha fazla yükle",
    accountIntelligence: "Hesap zekâsı",
    nothingServed: "Hiçbir şey sunulmadı",
    intelligenceSources: "Zekâ kaynakları",
    manualWrite: "Manuel yazma",
    checkOlderThan15: "Bu kontrol 15 dakikadan eski. Harekete geçmeden önce yeniden çalıştırın.",
    reCheck: "Yeniden denetle",
    metaHistory: "Meta Geçmişi",
    metaActionHistory: "Meta işlem geçmişi",
    whyAgencyNoTotals: "Ajans neden toplam göstermiyor",
    findAnything: "Bul",
    brandName: "ADSECUTE",
    mediaBuyingOperatingSystem: "Medya satın alma işletim sistemi.",
    adsecuteHome: "Adsecute ana sayfası",
    profile: "Profil",
    revokeAllSessions: "Tüm oturumları sonlandır",
    signInEmailReadOnly: "Oturum açma e-postanız doğrulandı ve bu ekrandan değiştirilemez.",
    revokeAllSessionsQ: "Tüm oturumlar sonlandırılsın mı?",
    aiInsights: "AI İçgörüleri",
    trafficSources: "Trafik kaynakları",
    readLatestOnly: "YALNIZCA EN SONU OKUR",
    aiGenerationUnavailable: "Burada üretim kullanılamaz. Bu yüzey sunulan en son içgörüyü okur ve tarayıcıda yeni bir içgörü uydurmaz.",
    aiCitedPages: "AI tarafından kaynak gösterilen sayfalar",
    sourcesServing: "Veri sunan kaynaklar",
    prioritiesServed: "Sunulan öncelikler",
    audienceSessionComparison: "Yeni ve geri dönen kitle oturumlarının karşılaştırması",
    audienceCohorts: "Kitle grupları",
    geoSummary: "GEO özeti",
    sharedVia: "Şununla paylaşıldı",
    created: "Oluşturuldu",
    deletion: "Silme",
    lineageImmutable: "Kullanılamıyor — kaynak zinciri değiştirilemez",
    derivedContext: "Türetilmiş bağlam",
    diagnostics: "Tanılama",
    accountScope: "Hesap kapsamı",
    googleAdsOverviewTitle: "Google Ads — Genel Bakış",
    googleKeyMetrics: "Google temel metrikleri",
    campaigns: "Kampanyalar",
    homeDecisionOrientation: "İşletmeyi, verimliliğini ve veri hazırlığını karar odaklı gösterir.",
    noDailyTrendServed: "Bu aralık için günlük eğilim sunulmadı.",
    featureAccessNotBillingGated: "Özellik erişimi faturalandırma katmanıyla kısıtlanmaz.",
    planAndBilling: "Plan ve Faturalandırma",
    automationReadOnlyNote: "Otomasyon ayarları salt okunur gösterilir. Meta durdurma işletme kapsamındadır ve Google'ı hiçbir zaman etkilemez.",
    inactiveAssets: "Etkin olmayan varlıklar",
    inactiveAssetsOutsideLanes: "Karar şeritlerinin dışında tutulur.",
    accountPulse: "Hesap nabzı",
    workspaceScope: "Çalışma alanı kapsamı",
    seoFindings: "SEO — Bulgular",
    commentary: "Yorum",
    publicShareCommentary:
      "Paylaşımı oluşturan kişi bu kreatifi inceleme için paylaştı. Sonuçlar, bu anlık görüntüde sunulan verilerle sınırlıdır.",
    objective: "Amaç",
    briefObjectiveDetail:
      "Sunulan kreatif yönünü yenilerken bu brief'in yanında gösterilen değiştirilemez karar ve hesap kökenini koruyun.",
    otherBriefs: "Diğer brief'ler",
    acknowledgementRequired: "Onay gerekli",
    briefLifecycle: "Brief yaşam döngüsü",
    metaStopEngagedBusiness: "Meta yazma durdurması bu işletme için DEVREDE",
    metaWriteBlockedGoogleUnaffected: "Meta yazma yolları engellendi. Google Ads etkilenmez.",
    observed: "Gözlemlendi",
    actor: "İşlemi yapan",
    evidenceBasis: "Kanıt dayanağı",
    campaignLabels: "Kampanya etiketleri",
    campaignLabelsSemanticOnly:
      "Etiketler yalnızca anlam taşır. Menü içermez ve yazma yetkisi vermez.",
  },
} as const;

export type ZeroBaseCopyKey = keyof (typeof ZERO_BASE_COPY)["en"];
export type ZeroBaseCopy = (typeof ZERO_BASE_COPY)["en"];

/**
 * Copy for a language, falling back to English explicitly.
 *
 * The fallback is a value, not an accident: a language with no catalogue must
 * render English rather than blank keys, and the parity test makes sure that
 * path is never reached for a language the UI actually offers.
 */
export function zeroBaseCopy(language: AppLanguage | null | undefined): ZeroBaseCopy {
  return language === "tr" ? (ZERO_BASE_COPY.tr as unknown as ZeroBaseCopy) : ZERO_BASE_COPY.en;
}

/** The terms that must survive translation byte-for-byte. */
export { NON_TRANSLATABLE_TERMS };

/**
 * Does this string keep every non-translatable term the English original used?
 *
 * Used by the glossary test. A Turkish string that renders "ROAS" as "YG" has
 * silently broken the join with every other system the operator reads.
 */
/**
 * Terms that are also ordinary English words.
 *
 * "Search", "Shopping" and "Display" are Google Ads campaign types **when
 * capitalised**. Lowercase they are common nouns: "Clear search" is a button,
 * not a reference to the campaign type, and forcing it to survive translation
 * would produce nonsense Turkish. These are matched case-sensitively; every
 * other term stays case-insensitive.
 */
const CASE_SENSITIVE_TERMS = new Set(["Search", "Shopping", "Display"]);

export function preservesGlossary(english: string, translated: string): string[] {
  const missing: string[] = [];
  for (const term of NON_TRANSLATABLE_TERMS) {
    const escaped = term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const flags = CASE_SENSITIVE_TERMS.has(term) ? "" : "i";
    const inEnglish = new RegExp(`\\b${escaped}\\b`, flags).test(english);
    if (!inEnglish) continue;
    if (!translated.includes(term)) missing.push(term);
  }
  return missing;
}
