/**
 * The legacy ADSET calibration reader, against a real PostgreSQL.
 *
 * WHY THIS FILE EXISTS. `readAggregatedAdsetMetricRows` in
 * `lib/meta/calibration.ts` builds its 28-day ad-derived windows from SQL
 * fragments generated by three shared contracts — the D095 link-click
 * authority ladder (`lib/meta/link-click-parse.ts`), the funnel-stage ladder
 * and the complete-or-null window rule (`lib/meta/funnel-stage-parse.ts`) —
 * and joins them onto the `meta_adset_daily` spine. Every claim that matters
 * here is a claim about what PostgreSQL does with NULL: that `SUM` over a
 * window with a missing delivered day is NULL rather than a partial sum, that
 * a LEFT JOIN miss on a delivered adset-day counts as missing, that a legacy
 * stored zero with no payload provenance is unknown, that a malformed value
 * neither becomes 0 nor aborts the query. A template-SQL mock answers all of
 * those with whatever the test author typed, so they run here.
 *
 * THE ACCEPTANCE RULES, as cases:
 *   R1 zero + missing  -> NULL        R2 zero + zero -> 0
 *   R3 aliases are never summed       R4 malformed stays missing, no abort
 *   R5 thruplay has no verified contract on this grain -> NULL
 * plus the two ways the old reader dropped evidence: a delivered adset-day with
 * no ad rows (now missing), and an adset folded back from two (goal, event)
 * rows (now merged complete-only).
 *
 * Every case owns its own business id, so no case can read another's rows and
 * nothing collides with other stages of the seam gate. Rows are inserted
 * directly: the reader is what is under test, and both tables are plain
 * warehouse tables with no triggers.
 *
 * Runs only inside an ephemeral-database seam (`ADSECUTE_EPHEMERAL_DB_SEAM=1`),
 * because outside one `DATABASE_URL` in this repository points at PRODUCTION.
 * Registered in `scripts/ephemeral-postgres-migrations-check.ts` with its exact
 * passing count, because `describe.skipIf(!SEAM)` reads green when skipped.
 * Adding or removing a case means updating that count.
 */
import { describe, expect, it } from "vitest";

import { getDb } from "@/lib/db";
import {
  readAggregatedAdsetMetricRows,
  runMetaCalibrationForBusiness,
  type AggregatedAdsetMetricRow,
} from "@/lib/meta/calibration";

const SEAM = process.env.ADSECUTE_EPHEMERAL_DB_SEAM === "1";

const ACCOUNT_ID = "act_calibration_window_seam_9301";
const SNAPSHOT = "2026-05-28";
const DAY_1 = "2026-05-20";
const DAY_2 = "2026-05-21";
const DAY_3 = "2026-05-22";

let businessSequence = 0;
function newBusinessId(label: string) {
  businessSequence += 1;
  return `calibration-window-seam-${label}-${businessSequence}-${Date.now()}`;
}

interface Delivery {
  spend?: number;
  impressions?: number;
  clicks?: number;
  conversions?: number;
  revenue?: number;
}

const ACTIVE: Required<Delivery> = {
  spend: 10,
  impressions: 100,
  clicks: 10,
  conversions: 1,
  revenue: 40,
};
const INERT: Required<Delivery> = {
  spend: 0,
  impressions: 0,
  clicks: 0,
  conversions: 0,
  revenue: 0,
};

async function adsetDay(input: {
  businessId: string;
  date: string;
  adsetId: string;
  goal?: string;
  event?: string | null;
  delivery?: Delivery;
}) {
  const delivery = { ...ACTIVE, ...input.delivery };
  const sql = getDb();
  await sql`
    INSERT INTO meta_adset_daily (
      business_id, provider_account_id, date, campaign_id, adset_id,
      optimization_goal, custom_event_type, account_timezone, account_currency,
      spend, impressions, clicks, reach, conversions, revenue
    ) VALUES (
      ${input.businessId}, ${ACCOUNT_ID}, ${input.date}::date, 'cmp_window',
      ${input.adsetId}, ${input.goal ?? "LINK_CLICKS"}, ${input.event ?? null},
      'UTC', 'USD', ${delivery.spend}, ${delivery.impressions}, ${delivery.clicks},
      ${delivery.impressions}, ${delivery.conversions}, ${delivery.revenue}
    )
  `;
}

/**
 * `payload` undefined writes SQL NULL; an object without `actions` is the
 * "Meta reported no actions breakdown" shape.
 */
async function adDay(input: {
  businessId: string;
  date: string;
  adsetId: string;
  adId: string;
  linkClicks: number | null;
  payload?: Record<string, unknown>;
  delivery?: Delivery;
}) {
  const delivery = { ...ACTIVE, ...input.delivery };
  const sql = getDb();
  await sql`
    INSERT INTO meta_ad_daily (
      business_id, provider_account_id, date, campaign_id, adset_id, ad_id,
      account_timezone, account_currency, spend, impressions, clicks, reach,
      conversions, revenue, link_clicks, payload_json
    ) VALUES (
      ${input.businessId}, ${ACCOUNT_ID}, ${input.date}::date, 'cmp_window',
      ${input.adsetId}, ${input.adId}, 'UTC', 'USD', ${delivery.spend},
      ${delivery.impressions}, ${delivery.clicks}, ${delivery.impressions},
      ${delivery.conversions}, ${delivery.revenue}, ${input.linkClicks},
      ${input.payload === undefined ? null : JSON.stringify(input.payload)}::jsonb
    )
  `;
}

/** Numbers come back as float8 numbers, numeric strings, or NULL. */
function num(value: unknown): number | null {
  if (value === null || value === undefined) return null;
  const parsed = Number(value);
  if (!Number.isFinite(parsed)) throw new Error(`not a number: ${String(value)}`);
  return parsed;
}

async function readAdsets(businessId: string) {
  const rows = await readAggregatedAdsetMetricRows(businessId, SNAPSHOT);
  const byAdset = new Map<string, AggregatedAdsetMetricRow[]>();
  for (const row of rows) {
    const list = byAdset.get(row.adset_id) ?? [];
    list.push(row);
    byAdset.set(row.adset_id, list);
  }
  return {
    one(adsetId: string) {
      const list = byAdset.get(adsetId) ?? [];
      if (list.length !== 1) {
        throw new Error(`expected one row for ${adsetId}, got ${list.length}`);
      }
      return list[0]!;
    },
  };
}

const actions = (...entries: Array<[string, unknown]>) => ({
  actions: entries.map(([action_type, value]) => ({ action_type, value })),
});

describe.skipIf(!SEAM)("adset calibration windows against real PostgreSQL", () => {
  it("R2: zero + zero stays a measured zero for link clicks and every stage", async () => {
    const businessId = newBusinessId("zero-zero");
    for (const date of [DAY_1, DAY_2]) {
      await adsetDay({ businessId, date, adsetId: "s1" });
      // Meta's measured-zero encoding: an actions array that omits the stage.
      await adDay({
        businessId,
        date,
        adsetId: "s1",
        adId: "a1",
        linkClicks: 0,
        payload: actions(["post_engagement", "3"]),
      });
    }

    const row = (await readAdsets(businessId)).one("s1");
    expect(num(row.link_clicks_28d)).toBe(0);
    expect(num(row.add_to_cart_28d)).toBe(0);
    expect(num(row.landing_page_views_28d)).toBe(0);
    expect(num(row.leads_28d)).toBe(0);
    expect(num(row.post_engagement_28d)).toBe(6);
    expect(num(row.link_clicks_28d_missing_days)).toBe(0);
    expect(num(row.add_to_cart_28d_missing_days)).toBe(0);
  });

  it("R1: zero + a delivered day with no actions breakdown is NULL, not 0", async () => {
    const businessId = newBusinessId("zero-missing");
    await adsetDay({ businessId, date: DAY_1, adsetId: "s1" });
    await adsetDay({ businessId, date: DAY_2, adsetId: "s1" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s1",
      adId: "a1",
      linkClicks: 0,
      payload: actions(["post_engagement", "3"]),
    });
    await adDay({
      businessId,
      date: DAY_2,
      adsetId: "s1",
      adId: "a1",
      linkClicks: null,
      payload: { spend: "10.00" },
    });

    const row = (await readAdsets(businessId)).one("s1");
    for (const field of [
      "link_clicks_28d",
      "add_to_cart_28d",
      "initiate_checkout_28d",
      "view_content_28d",
      "landing_page_views_28d",
      "post_engagement_28d",
      "leads_28d",
    ] as const) {
      expect(row[field], field).toBeNull();
    }
    expect(num(row.link_clicks_28d_missing_days)).toBe(1);
    expect(num(row.add_to_cart_28d_missing_days)).toBe(1);
    // The delivery the window divides by is still all there.
    expect(num(row.spend_28d)).toBe(20);
    expect(num(row.impressions_28d)).toBe(200);
  });

  it("R1: a measured value + a missing delivered day is NULL, never the partial sum", async () => {
    const businessId = newBusinessId("value-missing");
    await adsetDay({ businessId, date: DAY_1, adsetId: "s1" });
    await adsetDay({ businessId, date: DAY_2, adsetId: "s1" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s1",
      adId: "a1",
      linkClicks: 30,
      payload: actions(["link_click", "30"], ["add_to_cart", "4"]),
    });
    await adDay({
      businessId,
      date: DAY_2,
      adsetId: "s1",
      adId: "a1",
      linkClicks: null,
      payload: { spend: "10.00" },
    });

    const row = (await readAdsets(businessId)).one("s1");
    // The old reader returned 30 and 4 here.
    expect(row.link_clicks_28d).toBeNull();
    expect(row.add_to_cart_28d).toBeNull();
  });

  it("D095: a legacy stored zero with no payload provenance is unknown; a stored positive stands", async () => {
    const businessId = newBusinessId("d095");
    // s1: the legacy writer's literal zero beside a payload with no actions.
    await adsetDay({ businessId, date: DAY_1, adsetId: "s1" });
    await adsetDay({ businessId, date: DAY_2, adsetId: "s1" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s1",
      adId: "a1",
      linkClicks: 0,
      payload: actions(["post_engagement", "1"]),
    });
    await adDay({
      businessId,
      date: DAY_2,
      adsetId: "s1",
      adId: "a1",
      linkClicks: 0,
      payload: { spend: "10.00" },
    });
    // s2: a stored positive count needs no payload evidence; one exact "0"
    // entry is a measured zero too.
    await adsetDay({ businessId, date: DAY_1, adsetId: "s2" });
    await adsetDay({ businessId, date: DAY_2, adsetId: "s2" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s2",
      adId: "a2",
      linkClicks: 7,
      payload: { spend: "10.00" },
    });
    await adDay({
      businessId,
      date: DAY_2,
      adsetId: "s2",
      adId: "a2",
      linkClicks: 0,
      payload: actions(["link_click", "0"]),
    });

    const read = await readAdsets(businessId);
    // The old reader summed the raw column: 0 + 0 = a confident 0.
    expect(read.one("s1").link_clicks_28d).toBeNull();
    expect(num(read.one("s1").link_clicks_28d_missing_days)).toBe(1);
    expect(num(read.one("s2").link_clicks_28d)).toBe(7);
    // The link-click column and the funnel stages are separate evidence: the
    // no-actions day is still missing for every stage.
    expect(read.one("s2").add_to_cart_28d).toBeNull();
  });

  it("R3: equivalent and divergent aliases are never summed into the stage", async () => {
    const businessId = newBusinessId("aliases");
    await adsetDay({ businessId, date: DAY_1, adsetId: "s1" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s1",
      adId: "a1",
      linkClicks: 12,
      payload: actions(
        ["link_click", "12"],
        ["outbound_click", "20"],
        ["add_to_cart", "3"],
        ["offsite_conversion.fb_pixel_add_to_cart", "3"],
        ["omni_add_to_cart", "9"],
        ["landing_page_view", "40"],
        ["omni_landing_page_view", "40"],
        ["lead", "2"],
        ["onsite_conversion.lead_grouped", "5"],
        ["post_engagement", "6"],
        ["page_engagement", "8"],
      ),
    });

    const row = (await readAdsets(businessId)).one("s1");
    expect(num(row.link_clicks_28d)).toBe(12);
    expect(num(row.add_to_cart_28d)).toBe(3);
    expect(num(row.landing_page_views_28d)).toBe(40);
    expect(num(row.leads_28d)).toBe(2);
    expect(num(row.post_engagement_28d)).toBe(6);
  });

  it("R4: a malformed value stays missing, never 0, and never aborts the query", async () => {
    const businessId = newBusinessId("malformed");
    const malformed: Array<[string, unknown]> = [
      ["fraction", "3.5"],
      ["json_number", 3],
      ["past_safe_integer", "99999999999999999999"],
      ["junk", "3abc"],
      ["negative", "-3"],
      ["empty", ""],
    ];
    for (const [adsetId, value] of malformed) {
      await adsetDay({ businessId, date: DAY_1, adsetId });
      await adDay({
        businessId,
        date: DAY_1,
        adsetId,
        adId: `ad_${adsetId}`,
        linkClicks: 0,
        payload: actions(["add_to_cart", value], ["link_click", value]),
      });
    }
    // A duplicated entry is a shape the provider has not shown us: unreadable.
    await adsetDay({ businessId, date: DAY_1, adsetId: "duplicate" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "duplicate",
      adId: "ad_duplicate",
      linkClicks: 0,
      payload: actions(["add_to_cart", "2"], ["add_to_cart", "2"], ["link_click", "0"], ["link_click", "0"]),
    });
    // The control, in the same query: a well-formed neighbour still reads.
    await adsetDay({ businessId, date: DAY_1, adsetId: "valid" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "valid",
      adId: "ad_valid",
      linkClicks: 0,
      payload: actions(["add_to_cart", "2"], ["link_click", "0"]),
    });
    // A top-level thruplay key the reader used to cast with ::numeric.
    await adsetDay({ businessId, date: DAY_1, adsetId: "thruplay_junk" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "thruplay_junk",
      adId: "ad_thruplay_junk",
      linkClicks: 0,
      payload: { ...actions(["add_to_cart", "1"]), thruplay_actions: "not-a-number" },
    });

    const read = await readAdsets(businessId);
    for (const [adsetId] of [...malformed, ["duplicate"]]) {
      const row = read.one(adsetId as string);
      expect(row.add_to_cart_28d, `${adsetId} add_to_cart`).toBeNull();
      expect(num(row.add_to_cart_28d_missing_days), `${adsetId} missing`).toBe(1);
      // Stored 0 beside a malformed or duplicated link_click entry is not
      // Meta's measured zero either.
      expect(row.link_clicks_28d, `${adsetId} link_clicks`).toBeNull();
    }
    expect(num(read.one("valid").add_to_cart_28d)).toBe(2);
    expect(num(read.one("valid").link_clicks_28d)).toBe(0);
    expect(num(read.one("thruplay_junk").add_to_cart_28d)).toBe(1);
  });

  it("R5: thruplay is NULL even when a numeric top-level key is present", async () => {
    const businessId = newBusinessId("thruplay");
    await adsetDay({ businessId, date: DAY_1, adsetId: "s1", goal: "THRUPLAY" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s1",
      adId: "a1",
      linkClicks: 0,
      payload: { ...actions(["video_view", "80"]), thruplay_actions: "12" },
    });

    const row = (await readAdsets(businessId)).one("s1");
    expect(row.thruplay_actions_28d).toBeNull();
  });

  it("a delivered adset-day with NO ad rows is missing; an inert one is not a gap", async () => {
    const businessId = newBusinessId("no-ad-rows");
    // s1: day 2 delivered per meta_adset_daily but carries no ad rows at all.
    await adsetDay({ businessId, date: DAY_1, adsetId: "s1" });
    await adsetDay({ businessId, date: DAY_2, adsetId: "s1" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s1",
      adId: "a1",
      linkClicks: 5,
      payload: actions(["link_click", "5"], ["landing_page_view", "4"]),
    });
    // s2: day 2 did nothing at all and has no ad rows either.
    await adsetDay({ businessId, date: DAY_1, adsetId: "s2" });
    await adsetDay({ businessId, date: DAY_2, adsetId: "s2", delivery: INERT });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s2",
      adId: "a2",
      linkClicks: 5,
      payload: actions(["link_click", "5"], ["landing_page_view", "4"]),
    });

    const read = await readAdsets(businessId);
    // The old LEFT JOIN summed past s1's day 2 and reported 5 against 20 of
    // spend and 200 impressions.
    expect(read.one("s1").link_clicks_28d).toBeNull();
    expect(read.one("s1").landing_page_views_28d).toBeNull();
    expect(num(read.one("s1").link_clicks_28d_missing_days)).toBe(1);
    expect(num(read.one("s1").spend_28d)).toBe(20);
    expect(num(read.one("s2").link_clicks_28d)).toBe(5);
    expect(num(read.one("s2").landing_page_views_28d)).toBe(4);
    expect(num(read.one("s2").link_clicks_28d_missing_days)).toBe(0);
  });

  it("an inert ad row without actions is not a gap; an active one is, whichever grain saw the activity", async () => {
    const businessId = newBusinessId("ad-activity");
    // s1: two ads on one adset-day, the second did nothing and reported nothing.
    await adsetDay({ businessId, date: DAY_1, adsetId: "s1" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s1",
      adId: "a1",
      linkClicks: 5,
      payload: actions(["link_click", "5"], ["add_to_cart", "1"]),
    });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s1",
      adId: "a2",
      linkClicks: null,
      payload: {},
      delivery: INERT,
    });
    // s2: the adset row reads inert, but an ad row on that day delivered and
    // reported no actions. Either grain doing something makes the day count.
    await adsetDay({ businessId, date: DAY_1, adsetId: "s2" });
    await adsetDay({ businessId, date: DAY_2, adsetId: "s2", delivery: INERT });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "s2",
      adId: "b1",
      linkClicks: 5,
      payload: actions(["link_click", "5"], ["add_to_cart", "1"]),
    });
    await adDay({
      businessId,
      date: DAY_2,
      adsetId: "s2",
      adId: "b1",
      linkClicks: null,
      payload: {},
    });

    const read = await readAdsets(businessId);
    expect(num(read.one("s1").link_clicks_28d)).toBe(5);
    expect(num(read.one("s1").add_to_cart_28d)).toBe(1);
    expect(read.one("s2").link_clicks_28d).toBeNull();
    expect(read.one("s2").add_to_cart_28d).toBeNull();
  });

  it("end to end: percentile populations receive only complete windows, merged complete-only", async () => {
    const businessId = newBusinessId("e2e");
    // t0..t7: complete traffic windows, 20 of spend over 10 link clicks and 8
    // landing-page views each.
    for (let index = 0; index < 8; index += 1) {
      const adsetId = `t${index}`;
      for (const date of [DAY_1, DAY_2]) {
        await adsetDay({ businessId, date, adsetId });
        await adDay({
          businessId,
          date,
          adsetId,
          adId: `ad_${adsetId}`,
          linkClicks: 5,
          payload: actions(["link_click", "5"], ["landing_page_view", "4"]),
        });
      }
    }
    // t8: one delivered day without an actions breakdown. Fabricated, it would
    // have voted cost-per-link-click 4 and cost-per-LPV 5.
    await adsetDay({ businessId, date: DAY_1, adsetId: "t8" });
    await adsetDay({ businessId, date: DAY_2, adsetId: "t8" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "t8",
      adId: "ad_t8",
      linkClicks: 5,
      payload: actions(["link_click", "5"], ["landing_page_view", "4"]),
    });
    await adDay({
      businessId,
      date: DAY_2,
      adsetId: "t8",
      adId: "ad_t8",
      linkClicks: null,
      payload: {},
    });
    // t9: switched LINK_CLICKS -> LANDING_PAGE_VIEWS (both traffic), so it
    // arrives as two rows. The second half delivered with no ad rows.
    await adsetDay({ businessId, date: DAY_1, adsetId: "t9", goal: "LINK_CLICKS" });
    await adDay({
      businessId,
      date: DAY_1,
      adsetId: "t9",
      adId: "ad_t9",
      linkClicks: 5,
      payload: actions(["link_click", "5"], ["landing_page_view", "4"]),
    });
    await adsetDay({ businessId, date: DAY_3, adsetId: "t9", goal: "LANDING_PAGE_VIEWS" });

    const result = await runMetaCalibrationForBusiness(businessId, SNAPSHOT);
    expect(result.sampleRowsByCohort.traffic).toBe(10);

    const written = (await getDb()`
      SELECT metric_name, sample_size, p10, p50, p90
      FROM meta_decision_calibration_daily
      WHERE business_id = ${businessId}
        AND scope_type = 'account'
        AND cohort = 'traffic'
    `) as Array<{
      metric_name: string;
      sample_size: unknown;
      p10: unknown;
      p50: unknown;
      p90: unknown;
    }>;
    const metric = (name: string) => {
      const row = written.find((entry) => entry.metric_name === name);
      if (!row) throw new Error(`no ${name} row`);
      return row;
    };
    // Only the eight complete windows vote, and every one of them votes 2.
    expect(num(metric("cost_per_link_click_28d").sample_size)).toBe(8);
    expect(num(metric("cost_per_link_click_28d").p10)).toBe(2);
    expect(num(metric("cost_per_link_click_28d").p90)).toBe(2);
    expect(num(metric("cost_per_lpv_28d").sample_size)).toBe(8);
    expect(num(metric("cost_per_lpv_28d").p90)).toBe(2.5);
    // The control: CTR comes from meta_adset_daily, which every adset has.
    expect(num(metric("ctr_28d").sample_size)).toBe(10);
  });
});
