/**
 * WP-06 responsive evidence: 1440 / 1280 / 768 / 390 / 320, light and dark.
 *
 * Scope, stated plainly: this renders the **real shell components** to markup
 * and measures them against the **real** `app/globals.css` in a real browser.
 * It does not exercise a data-populated live page — this worktree has no
 * `.env.local` and deliberately reaches no database, so there is no server to
 * render one. What it proves is the layout contract: at every named width, in
 * both themes, the page does not scroll horizontally, the rail/drawer swap
 * happens at the right breakpoint, and the rail footer stays visible at a
 * short viewport.
 *
 * That is the property that actually breaks — overflow and clipping are CSS
 * outcomes — and it is checked against the shipped stylesheet rather than a
 * copy.
 */
import { existsSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { expect, test } from "@playwright/test";

import { DARK_PALETTE, LIGHT_PALETTE } from "../../lib/design/ledger-tokens";

const HARNESS_DIR = path.join(process.cwd(), "playwright", ".harness");
const DRAWER_BREAKPOINT = 768;

/** Harness pages are generated by `npm run zero-base:shell:harness`. */
function harnessUrl(width: number, theme: string): string {
  const file = path.join(HARNESS_DIR, `shell-${width}-${theme}.html`);
  if (!existsSync(file)) {
    throw new Error(
      `missing harness page ${file}. Run: npm run zero-base:shell:harness`,
    );
  }
  return pathToFileURL(file).href;
}

function rgb(hex: string): string {
  const value = Number.parseInt(hex.replace("#", ""), 16);
  return `rgb(${(value >> 16) & 255}, ${(value >> 8) & 255}, ${value & 255})`;
}

const WIDTHS = [1440, 1280, 768, 390, 320];
const THEMES = ["light", "dark"] as const;

for (const width of WIDTHS) {
  for (const theme of THEMES) {
    test(`shell at ${width}px — ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 800 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      await page.goto(harnessUrl(width, theme), { waitUntil: "load" });

      // 1 · No page-level horizontal scroll at any width.
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `page scrolls horizontally at ${width}px`,
      ).toBeLessThanOrEqual(overflow.clientWidth);

      // 2 · The wide table scrolls inside main instead of widening the page.
      const mainScrolls = await page.evaluate(() => {
        const main = document.getElementById("zero-base-main")!;
        return main.scrollWidth > main.clientWidth;
      });
      if (width < 1440) expect(mainScrolls, "wide content should scroll inside main").toBe(true);

      // 3 · Rail above the breakpoint, compact context bar below it.
      const rail = await page.$("[data-rail]");
      const compactBar = await page.$('[data-context-bar="compact"]');
      if (width >= DRAWER_BREAKPOINT) {
        expect(rail, `rail missing at ${width}px`).not.toBeNull();
        expect(compactBar).toBeNull();
        expect(await rail!.evaluate((node) => node.getBoundingClientRect().width)).toBe(232);
      } else {
        expect(rail, `rail should be a drawer at ${width}px`).toBeNull();
        expect(compactBar, `compact context bar missing at ${width}px`).not.toBeNull();
      }

      // 4 · The context bar is present at every width — never absent.
      expect(await page.$("[data-context-bar]")).not.toBeNull();

      // 5 · The theme actually applied, so this is not five copies of light.
      const palette = theme === "dark" ? DARK_PALETTE : LIGHT_PALETTE;
      const background = await page.evaluate(
        () => getComputedStyle(document.querySelector("[data-shell]")!).backgroundColor,
      );
      expect(background).toBe(rgb(palette["bg/app"]));

      await context.close();
    });
  }
}

test("rail footer stays visible in a 640px artboard (B02)", async ({ browser }) => {
  const context = await browser.newContext({
    // The short viewport that pushed the identity row off-screen.
    viewport: { width: 1280, height: 640 },
    colorScheme: "light",
  });
  const page = await context.newPage();
  await page.goto(harnessUrl(1280, "light"), { waitUntil: "load" });

  const footer = await page.$("[data-rail-footer]");
  expect(footer).not.toBeNull();
  const box = (await footer!.boundingBox())!;
  expect(box.y + box.height, "rail footer is clipped by the artboard").toBeLessThanOrEqual(640);

  // And the nav area has a real scroll range, so items are still reachable.
  const navScrolls = await page.evaluate(() => {
    const nav = document.querySelector("[data-rail-nav]") as HTMLElement;
    return { scrollHeight: nav.scrollHeight, clientHeight: nav.clientHeight };
  });
  expect(navScrolls.scrollHeight).toBeGreaterThan(navScrolls.clientHeight);

  await context.close();
});

/**
 * WP-10: the 50-client scan at 1440 and 390.
 *
 * Fifty rows is where a directory that looks fine with three starts to
 * overflow, so this measures the real projection through the real table: the
 * page must not scroll sideways at either width, every row must be present,
 * and no forbidden column may have appeared.
 */
for (const width of [1440, 390]) {
  for (const theme of THEMES) {
    test(`agency directory — 50 clients at ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `agency-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      // All fifty are actually rendered — a scan that silently stops at 20 is
      // the failure this is here to catch.
      expect(await page.locator("tbody tr").count()).toBe(50);
      await expect(page.locator("[data-collection-count]")).toContainText("Showing 50 of 50");

      // No page-level horizontal scroll at either width.
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `agency directory scrolls horizontally at ${width}px`,
      ).toBeLessThanOrEqual(overflow.clientWidth);

      // Wide content stays inside main.
      const mainScrolls = await page.evaluate(() => {
        const main = document.getElementById("zero-base-main")!;
        return main.scrollWidth > main.clientWidth;
      });
      if (width === 390) expect(mainScrolls).toBe(true);

      // Column set, and the absence of anything money- or ranking-shaped.
      const headers = await page.locator("thead th").allTextContents();
      expect(headers).toEqual(["Client", "Your role", "Currency", "Last source activity"]);
      const body = (await page.locator("body").innerText()).toLowerCase();
      for (const forbidden of ["spend", "revenue", "roas", "severity", "priority", "urgency"]) {
        expect(body, forbidden).not.toContain(forbidden);
      }

      // Currency is labelled as configuration, not as an observed value.
      await expect(page.locator("tbody tr").first()).toContainText("(configured)");

      await context.close();
    });
  }
}

/**
 * WP-11 · H03/H04/H08 — Client Home at 1440, 390 and 320 in both themes.
 *
 * Rendered from the real contract through the real components, so the checks
 * are about the surface's truth rules rather than its pixels: no fabricated
 * zero, no percentage where there is no comparison, a cost metric coloured by
 * meaning rather than by its arrow, both banner severities visible at once, and
 * a failed refresh that keeps the previous figures on screen.
 */
for (const width of [1440, 390, 320]) {
  for (const theme of THEMES) {
    test(`client home — ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `home-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      // No page-level horizontal scroll at any width.
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(overflow.scrollWidth, `home scrolls horizontally at ${width}px`).toBeLessThanOrEqual(
        overflow.clientWidth,
      );

      // Every metric card is present, including the unavailable one.
      expect(await page.locator("[data-metric-card]").count()).toBe(6);
      await expect(page.locator('[data-metric-card="aov"]')).toHaveAttribute(
        "data-availability",
        "unavailable",
      );

      // An unavailable metric renders an em dash, never a zero.
      await expect(
        page.locator('[data-metric-card="aov"] [data-metric-value]'),
      ).toHaveText("—");

      // A metric with no comparison states the reason instead of 0.0%.
      const noComparison = page.locator('[data-metric-card="orders"] [data-comparison="unavailable"]');
      await expect(noComparison).toBeVisible();
      expect(await noComparison.textContent()).not.toMatch(/0\.0\s*%/);

      // Direction and desirability disagree on a rising cost metric.
      const cpa = page.locator('[data-metric-card="cpa"] [data-comparison="available"]');
      await expect(cpa).toHaveAttribute("data-sentiment", "negative");
      expect(await cpa.textContent()).toContain("▲");

      // Rising spend stays neutral.
      await expect(
        page.locator('[data-metric-card="spend"] [data-comparison="available"]'),
      ).toHaveAttribute("data-sentiment", "neutral");

      // Both banner severities are visible together.
      await expect(page.locator('[data-banner="hard"]')).toBeVisible();
      await expect(page.locator('[data-banner="partial"]')).toBeVisible();

      // A failed refresh keeps the previous figures and says they are unchanged.
      await expect(page.locator('[data-refresh-notice="failed"]')).toContainText("unchanged");

      // Money never claims an unproven currency was observed.
      await expect(
        page.locator('[data-metric-card="revenue"] [data-money-proof="configured-only"]'),
      ).toContainText("not observed");

      // Every chart offers its values as a table.
      const charts = await page.locator("svg[role='img']").count();
      expect(await page.locator("[data-sparkline-toggle]").count()).toBe(charts);

      // Source health lists each source with its state.
      await expect(page.locator("[data-source-health]")).toBeVisible();
      expect(await page.locator("[data-source]").count()).toBe(3);

      await context.close();
    });
  }
}
