/**
 * WP-06 responsive evidence: 1440 / 1280 / 768 / 390 / 320, light and dark.
 *
 * Scope, stated plainly: this renders the **real shell components** to markup
 * and measures them against the **real** `app/globals.css` in a real browser.
 * It does not exercise a data-populated live page — this worktree has no
 * `.env.local` and deliberately reaches no database, so there is no server to
 * render one. What it proves is the layout contract: at every named width, in
 * both themes, the page does not scroll horizontally, the rail/drawer swap
 * happens at the right breakpoint, and the rail footer stays visible at a
 * short viewport.
 *
 * That is the property that actually breaks — overflow and clipping are CSS
 * outcomes — and it is checked against the shipped stylesheet rather than a
 * copy.
 */
import { existsSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";

import { expect, test } from "@playwright/test";

import { DARK_PALETTE, LIGHT_PALETTE } from "../../lib/design/ledger-tokens";

const HARNESS_DIR = path.join(process.cwd(), "playwright", ".harness");
const DRAWER_BREAKPOINT = 768;

/** Harness pages are generated by `npm run zero-base:shell:harness`. */
function harnessUrl(width: number, theme: string): string {
  const file = path.join(HARNESS_DIR, `shell-${width}-${theme}.html`);
  if (!existsSync(file)) {
    throw new Error(
      `missing harness page ${file}. Run: npm run zero-base:shell:harness`,
    );
  }
  return pathToFileURL(file).href;
}

function rgb(hex: string): string {
  const value = Number.parseInt(hex.replace("#", ""), 16);
  return `rgb(${(value >> 16) & 255}, ${(value >> 8) & 255}, ${value & 255})`;
}

const WIDTHS = [1440, 1280, 768, 390, 320];
const THEMES = ["light", "dark"] as const;

for (const width of WIDTHS) {
  for (const theme of THEMES) {
    test(`shell at ${width}px — ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 800 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      await page.goto(harnessUrl(width, theme), { waitUntil: "load" });

      // 1 · No page-level horizontal scroll at any width.
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `page scrolls horizontally at ${width}px`,
      ).toBeLessThanOrEqual(overflow.clientWidth);

      // 2 · The wide table scrolls inside main instead of widening the page.
      const mainScrolls = await page.evaluate(() => {
        const main = document.getElementById("zero-base-main")!;
        return main.scrollWidth > main.clientWidth;
      });
      if (width < 1440) expect(mainScrolls, "wide content should scroll inside main").toBe(true);

      // 3 · Rail above the breakpoint, compact context bar below it.
      const rail = await page.$("[data-rail]");
      const compactBar = await page.$('[data-context-bar="compact"]');
      if (width >= DRAWER_BREAKPOINT) {
        expect(rail, `rail missing at ${width}px`).not.toBeNull();
        expect(compactBar).toBeNull();
        expect(await rail!.evaluate((node) => node.getBoundingClientRect().width)).toBe(232);
      } else {
        expect(rail, `rail should be a drawer at ${width}px`).toBeNull();
        expect(compactBar, `compact context bar missing at ${width}px`).not.toBeNull();
      }

      // 4 · The context bar is present at every width — never absent.
      expect(await page.$("[data-context-bar]")).not.toBeNull();

      // 5 · The theme actually applied, so this is not five copies of light.
      const palette = theme === "dark" ? DARK_PALETTE : LIGHT_PALETTE;
      const background = await page.evaluate(
        () => getComputedStyle(document.querySelector("[data-shell]")!).backgroundColor,
      );
      expect(background).toBe(rgb(palette["bg/app"]));

      await context.close();
    });
  }
}

test("rail footer stays visible in a 640px artboard (B02)", async ({ browser }) => {
  const context = await browser.newContext({
    // The short viewport that pushed the identity row off-screen.
    viewport: { width: 1280, height: 640 },
    colorScheme: "light",
  });
  const page = await context.newPage();
  await page.goto(harnessUrl(1280, "light"), { waitUntil: "load" });

  const footer = await page.$("[data-rail-footer]");
  expect(footer).not.toBeNull();
  const box = (await footer!.boundingBox())!;
  expect(box.y + box.height, "rail footer is clipped by the artboard").toBeLessThanOrEqual(640);

  // And the nav area has a real scroll range, so items are still reachable.
  const navScrolls = await page.evaluate(() => {
    const nav = document.querySelector("[data-rail-nav]") as HTMLElement;
    return { scrollHeight: nav.scrollHeight, clientHeight: nav.clientHeight };
  });
  expect(navScrolls.scrollHeight).toBeGreaterThan(navScrolls.clientHeight);

  await context.close();
});

/**
 * WP-10: the 50-client scan at 1440 and 390.
 *
 * Fifty rows is where a directory that looks fine with three starts to
 * overflow, so this measures the real projection through the real table: the
 * page must not scroll sideways at either width, every row must be present,
 * and no forbidden column may have appeared.
 */
for (const width of [1440, 390]) {
  for (const theme of THEMES) {
    test(`agency directory — 50 clients at ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `agency-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      // All fifty are actually rendered — a scan that silently stops at 20 is
      // the failure this is here to catch.
      expect(await page.locator("tbody tr").count()).toBe(50);
      await expect(page.locator("[data-collection-count]")).toContainText("Showing 50 of 50");

      // No page-level horizontal scroll at either width.
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `agency directory scrolls horizontally at ${width}px`,
      ).toBeLessThanOrEqual(overflow.clientWidth);

      // Wide content scrolls inside its own frame, not by dragging the surface.
      //
      // This used to assert that `main` itself scrolled sideways. That does
      // keep the overflow off the document, but it moves the heading and the
      // navigation along with the table, and the columns that leave the screen
      // give no sign they are there. The table now declares its own horizontal
      // scroller, so the surface stays put and the table moves inside it.
      const scrolling = await page.evaluate(() => {
        const undeclared: string[] = [];
        for (const node of document.querySelectorAll("*")) {
          if (node.hasAttribute("data-scroll-x")) continue;
          const cs = getComputedStyle(node);
          if (cs.overflowX !== "auto" && cs.overflowX !== "scroll") continue;
          if (node.scrollWidth > node.clientWidth + 1) {
            undeclared.push(`${node.tagName.toLowerCase()}#${node.id || "-"}`);
          }
        }
        return undeclared;
      });
      expect(
        scrolling,
        `something other than a declared scroller runs off the side at ${width}px`,
      ).toEqual([]);

      // Column set, and the absence of anything money- or ranking-shaped.
      const headers = await page.locator("thead th").allTextContents();
      expect(headers).toEqual(["Client", "Your role", "Currency", "Last source activity"]);
      const body = (await page.locator("body").innerText()).toLowerCase();
      for (const forbidden of ["spend", "revenue", "roas", "severity", "priority", "urgency"]) {
        expect(body, forbidden).not.toContain(forbidden);
      }

      // Currency is labelled as configuration, not as an observed value.
      await expect(page.locator("tbody tr").first()).toContainText("(configured)");

      await context.close();
    });
  }
}

/**
 * WP-11 · H03/H04/H08 — Client Home at 1440, 390 and 320 in both themes.
 *
 * Rendered from the real contract through the real components, so the checks
 * are about the surface's truth rules rather than its pixels: no fabricated
 * zero, no percentage where there is no comparison, a cost metric coloured by
 * meaning rather than by its arrow, both banner severities visible at once, and
 * a failed refresh that keeps the previous figures on screen.
 */
for (const width of [1440, 390, 320]) {
  for (const theme of THEMES) {
    test(`client home — ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `home-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      // No page-level horizontal scroll at any width.
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(overflow.scrollWidth, `home scrolls horizontally at ${width}px`).toBeLessThanOrEqual(
        overflow.clientWidth,
      );

      // Every metric card is present, including the unavailable one.
      expect(await page.locator("[data-metric-card]").count()).toBe(6);
      await expect(page.locator('[data-metric-card="aov"]')).toHaveAttribute(
        "data-availability",
        "unavailable",
      );

      // An unavailable metric renders an em dash, never a zero.
      await expect(
        page.locator('[data-metric-card="aov"] [data-metric-value]'),
      ).toHaveText("—");

      // A metric with no comparison states the reason instead of 0.0%.
      const noComparison = page.locator('[data-metric-card="orders"] [data-comparison="unavailable"]');
      await expect(noComparison).toBeVisible();
      expect(await noComparison.textContent()).not.toMatch(/0\.0\s*%/);

      // Direction and desirability disagree on a rising cost metric.
      const cpa = page.locator('[data-metric-card="cpa"] [data-comparison="available"]');
      await expect(cpa).toHaveAttribute("data-sentiment", "negative");
      expect(await cpa.textContent()).toContain("▲");

      // Rising spend stays neutral.
      await expect(
        page.locator('[data-metric-card="spend"] [data-comparison="available"]'),
      ).toHaveAttribute("data-sentiment", "neutral");

      /**
       * Source problems live in Source readiness, not in a page banner.
       *
       * This asserted that both banner severities were visible together, and it
       * contradicted `components/zero-base/home/home.test.tsx` — "keeps source
       * problems in Source readiness instead of duplicating a page banner" —
       * which asserts `[data-banner]` is null and has been enforced all along.
       *
       * Both could not be true. The unit test states the decision and its
       * reason and runs on every commit; this spec has not run since the
       * harness build broke on a CSS-module import, so it encodes an intent
       * that was superseded and never re-checked. `BannerStack` in
       * `source-health.tsx` is the leftover of the abandoned approach and is
       * called by nothing.
       *
       * What matters to the operator is unchanged and is what is checked now:
       * an unavailable and a partial source are both named, on the surface,
       * with their reasons.
       */
      const sourceHealth = page.locator("[data-source-health]");
      await expect(sourceHealth).toBeVisible();
      await expect(sourceHealth).toContainText("Meta");
      await expect(sourceHealth).toContainText("GA4");
      // And the page does not carry the duplicate banner the unit test forbids.
      await expect(page.locator("[data-banner]")).toHaveCount(0);

      // A failed refresh keeps the previous figures and says they are unchanged.
      await expect(page.locator('[data-refresh-notice="failed"]')).toContainText("unchanged");

      // Money never claims an unproven currency was observed.
      await expect(
        page.locator('[data-metric-card="revenue"] [data-money-proof="configured-only"]'),
      ).toContainText("not observed");

      // Every chart offers its values as a table.
      const charts = await page.locator("svg[role='img']").count();
      expect(await page.locator("[data-sparkline-toggle]").count()).toBe(charts);

      // Source health lists each source with its state.
      await expect(page.locator("[data-source-health]")).toBeVisible();
      expect(await page.locator("[data-source]").count()).toBe(3);

      await context.close();
    });
  }
}

/**
 * WP-12 · H09/H10 — Meta Decisions at 1440/1280/768/390/320 in both themes.
 *
 * The verdict text on screen is compared against the exact strings the fixture
 * served: a surface that reformats a verdict can disagree with the resolver,
 * which the Decision Center's invariants forbid.
 */
const SERVED_VERDICTS = [
  "Scale up — 7-day ROAS 3.4 vs target 2.6",
  "Hold — evidence incomplete at ad grain",
  "Cut — 14-day CPA above break-even",
];

for (const width of [1440, 1280, 768, 390, 320]) {
  for (const theme of THEMES) {
    test(`meta decisions — ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `decisions-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `decisions scrolls horizontally at ${width}px`,
      ).toBeLessThanOrEqual(overflow.clientWidth);

      // Verdict text is byte-identical to what was served.
      for (const [index, verdict] of SERVED_VERDICTS.entries()) {
        await expect(page.locator(`[data-verdict="d${index + 1}"]`)).toHaveText(verdict);
      }

      // A held decision offers no action and says why.
      await expect(page.locator('[data-decision-row="d2"]')).toBeVisible();
      const heldCell = page.locator('tbody tr', { has: page.locator('[data-decision-row="d2"]') });
      await expect(heldCell.locator('[data-action-count="0"]')).toBeVisible();
      await expect(heldCell).toContainText("Authority blocked");

      // Blocking and advisory banners are visible together.
      await expect(page.locator('[data-banner="hard"]')).toBeVisible();
      await expect(page.locator('[data-banner="partial"]')).toBeVisible();

      // Evidence window and snapshot time are distinct, labelled facts.
      const windowText = await page.locator("[data-evidence-window]").textContent();
      const snapshotText = await page.locator("[data-snapshot-time]").textContent();
      expect(windowText).toContain("2026-08-01");
      expect(snapshotText).toContain("2026-08-11T06:00:00Z");
      expect(windowText).not.toEqual(snapshotText);

      // Lane counts come from the payload, not from the rendered row count.
      await expect(page.getByRole("tab", { name: /Monitoring \(4\)/ })).toBeVisible();

      await context.close();
    });
  }
}

/**
 * The Meta-only scope of the stop, whichever composition is on screen.
 *
 * `MetaAutomationView` ships two: below 1024px `.desktopSurface` is hidden and
 * a read-only `.mobileSurface` takes over. Both state the same thing — the
 * sentence is the law — but only the desktop one carries H19's
 * `data-el="google-posture-row"` marker, because H19 is a 1440px artboard.
 * Asserting the marker at every width would fail on a surface that is telling
 * the operator exactly what it must.
 */
async function expectStopScopeIsMetaOnly(
  page: import("@playwright/test").Page,
  width: number,
) {
  const sentence = /no control on this screen stops google ads writes/i;
  if (width >= 1024) {
    const row = page.locator('[data-el="google-posture-row"]');
    await expect(row).toBeVisible();
    await expect(row).toContainText(sentence);
    return;
  }
  const mobile = page.locator('[data-testid="meta-mobile-automation"]');
  await expect(mobile).toBeVisible();
  await expect(mobile).toContainText(sentence);
  // And it is read-only, which is the other half of what mobile promises.
  await expect(mobile).toHaveAttribute("data-read-only", "true");
}

/**
 * WP-15 · Flow I — Meta Automation and the Meta stop at 1440/390/320.
 *
 * The fixture is the dangerous case: Meta degraded, Google healthy, no
 * read-back yet. A missing Google row here is exactly what would teach an
 * operator that one switch covers both providers, and a status banner here
 * would claim a state nobody has observed.
 */
for (const width of [1440, 390, 320]) {
  for (const theme of THEMES) {
    test(`meta automation — ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `automation-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `automation scrolls horizontally at ${width}px`,
      ).toBeLessThanOrEqual(overflow.clientWidth);

      /*
       * The same laws, against the MOUNTED body's markers.
       *
       * The archived presenter's `data-provider-state` / `data-stoppable` /
       * `data-stop-scope` / `data-guardrail-value` vocabulary went with it when
       * H19 and H20 were repointed at `MetaAutomationView` — the body every
       * route renders. What must hold is unchanged, and is what these check:
       * Google is named as outside this screen's reach, nothing claims a stop
       * wider than Meta, and the guardrails carry no edit affordance.
       */
      await expectStopScopeIsMetaOnly(page, width);

      const bodyText = (await page.locator("body").innerText()).toLowerCase();
      for (const phrase of ["stop all", "all providers", "all platforms"]) {
        expect(bodyText, phrase).not.toContain(phrase);
      }

      /*
       * The guardrails and the autonomy ladder are the desktop composition's.
       * The mobile surface is read-only by design and draws neither, which is
       * why it carries `data-read-only` rather than a disabled copy of them.
       */
      if (width >= 1024) {
        const guardrails = page.locator('[data-collection="guardrails"]');
        await expect(guardrails).toBeVisible();
        expect(
          await guardrails.locator("button, input, select, textarea").count(),
          "a guardrail gained an edit affordance",
        ).toBe(0);

        // Four action kinds, three rungs each; the launch row has no decision
        // type and must not gain one.
        expect(await page.locator('[data-ctl="gated:AUTO-03 mode"]').count()).toBe(4);
      }

      await context.close();
    });
  }
}

/**
 * WP-15 correction · the remaining Flow I surfaces at 1440/390/320.
 *
 * The mirror case (Meta healthy, Google unreadable) matters as much as the
 * original: covering only one direction would let a provider's row be quietly
 * conditional on the other's health.
 *
 * Network interactions — engage, release, read-back agreement, disagreement
 * and failure — are driven with real user events in
 * `components/zero-base/meta/flow-i.test.tsx`. These pages are static, and
 * nothing here is claimed as proof that a request was made.
 */
for (const width of [1440, 390, 320]) {
  for (const theme of THEMES) {
    async function open(browser: import("@playwright/test").Browser, name: string) {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `${name}-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });
      return { context, page };
    }

    async function expectNoOverflow(page: import("@playwright/test").Page, label: string) {
      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(overflow.scrollWidth, `${label} scrolls horizontally at ${width}px`).toBeLessThanOrEqual(
        overflow.clientWidth,
      );
    }

    test(`meta automation mirror — Meta healthy, Google unreadable — ${width}px ${theme}`, async ({
      browser,
    }) => {
      const { context, page } = await open(browser, "automation-mirror");
      await expectNoOverflow(page, "automation mirror");

      /*
       * The same laws, against the MOUNTED body's markers.
       *
       * This page used to render the archived Automation presenter, whose DOM
       * carried `data-provider-state`, `data-not-stoppable`, `data-stoppable`,
       * `data-stop-scope` and `data-guardrail-value`. The route renders
       * `MetaAutomationView`, which states the same facts with its own markers,
       * and grading the presenter meant these laws were being checked on a body
       * no operator can open. What must hold is unchanged: Google is named, the
       * stop's reach is stated as Meta-only, nothing claims a global stop, and
       * the guardrails are read-only.
       */
      await expectStopScopeIsMetaOnly(page, width);

      const body = (await page.locator("body").innerText()).toLowerCase();
      for (const phrase of ["stop all", "all providers", "all platforms"]) {
        expect(body, phrase).not.toContain(phrase);
      }

      // The guardrails are addressable, and none of them is a control.
      if (width >= 1024) {
        const guardrails = page.locator('[data-collection="guardrails"]');
        await expect(guardrails).toBeVisible();
        expect(
          await guardrails.locator("button, input, select, textarea").count(),
          "a guardrail gained an edit affordance",
        ).toBe(0);
      }
      /*
       * The release control is reachable from the keyboard.
       *
       * The archived presenter marked it `data-stop-trigger`; the mounted body
       * carries the manifest's own key. This frame is the engaged state, so the
       * control it offers is release rather than engage.
       */
      if (width >= 1024) {
        const trigger = page.locator('[data-ctl="gated:AUTO-02 release"]');
        await expect(trigger).toBeVisible();
        await trigger.focus();
        expect(await trigger.evaluate((node) => node === document.activeElement)).toBe(true);
      }

      await context.close();
    });

    test(`meta history — real actor and replay rows — ${width}px ${theme}`, async ({ browser }) => {
      const { context, page } = await open(browser, "history");
      await expectNoOverflow(page, "history");

      // A replayed window is marked, and the caveat has no dismiss control.
      const banner = page.locator("[data-replay-banner]");
      await expect(banner).toBeVisible();
      expect(await banner.locator("button").count()).toBe(0);

      // Recorded actor passes through; the unrecorded one says so.
      await expect(page.locator('[data-actor="h1"]')).toContainText("ada@example.com");
      const unknown = page.locator('[data-actor="h2"]');
      await expect(unknown).toContainText("Actor not recorded");
      await expect(unknown).not.toContainText("System");
      await expect(page.locator('[data-replayed="h2"]')).toBeVisible();
      await expect(page.locator('[data-recorded="h1"]')).toBeVisible();

      // The page cap is disclosed rather than implying this is everything.
      await expect(page.locator("[data-history-disclosure]")).toContainText("More exist");
      await expect(page.locator("[data-history-limitations]")).toBeVisible();
      await expect(page.locator("[data-history-account]")).toContainText("Main account");

      await context.close();
    });

    test(`meta intelligence — partial and degraded sources — ${width}px ${theme}`, async ({
      browser,
    }) => {
      const { context, page } = await open(browser, "intelligence");
      await expectNoOverflow(page, "intelligence");

      // Each impaired source keeps its own state word and its own reason.
      await expect(page.locator('[data-source-state="summary"]')).toContainText("Partial");
      await expect(page.locator('[data-source-state="summary"]')).toContainText(
        "still being prepared",
      );
      await expect(page.locator('[data-source-state="breakdowns"]')).toContainText("Degraded");
      await expect(page.locator('[data-source-state="structure"]')).toContainText("Unavailable");

      // A source with nothing served says so instead of showing a zero.
      await expect(page.locator('[data-source-facts-none="breakdowns"]')).toContainText(
        "Nothing served",
      );
      const text = await page.locator("body").innerText();
      expect(text).not.toMatch(/some data missing/i);

      // Every windowed source is stated to cover the same window.
      await expect(page.locator("[data-intelligence-window]")).toContainText("2026-07-15");

      await context.close();
    });
  }
}

/**
 * BLOCKER 1 · the public creative share at desktop, 390 and 320.
 *
 * The fixture carries workspace identity in the stored payload deliberately —
 * a business id, a provider account, the workspace name and a contact address —
 * so these assertions prove the sanitizer, not merely a payload that had
 * nothing to leak.
 */
for (const width of [1440, 390, 320]) {
  for (const theme of THEMES) {
    test(`public creative share — ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `public-share-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `public share scrolls horizontally at ${width}px`,
      ).toBeLessThanOrEqual(overflow.clientWidth);

      // Complete media state: the served video plays, the unserved one says so.
      await expect(page.locator('[data-share-media="video"]')).toBeVisible();
      await expect(page.locator('[data-share-media="missing"]')).toContainText("No preview");
      expect(await page.locator('[data-share-media="video"]').getAttribute("controls")).not.toBeNull();

      // No captions track anywhere: the payload contract serves none.
      expect(await page.locator("track").count()).toBe(0);

      // Buyer disclosure travels with the numbers it qualifies.
      await expect(page.locator("[data-share-financial-warning]")).toContainText(
        "attribution-window dependent",
      );

      // Nothing of the workspace survives into what a stranger can read.
      const html = await page.content();
      for (const secret of [
        "biz-internal-9f2c",
        "act_internal_7781",
        "Acme Internal Workspace",
        "finance@acme-internal.example",
        "cr-internal-1",
      ]) {
        expect(html, secret).not.toContain(secret);
      }

      await context.close();
    });

    test(`public creative share unavailable — ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `public-share-gone-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(overflow.scrollWidth).toBeLessThanOrEqual(overflow.clientWidth);

      await expect(page.locator('[data-public-share="unavailable"]')).toContainText(
        "expired, been withdrawn, or never existed",
      );
      // The cause is never named, so a dead link tells a stranger nothing.
      const body = (await page.locator("body").innerText()).toLowerCase();
      for (const word of ["revoked by", "rotated", "workspace"]) {
        expect(body, word).not.toContain(word);
      }

      await context.close();
    });
  }
}

/**
 * WP-24 · Flow J — the critical incident path at Ops widths.
 *
 * Ops is an operator console, so its widths are 1280/768/390 rather than the
 * buyer trio. The load-bearing assertion is the last step: the path must end in
 * a re-read, because the repair action itself confirms nothing.
 */
for (const width of [1280, 768, 390]) {
  for (const theme of THEMES) {
    test(`ops critical incident — ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `ops-incident-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(
        overflow.scrollWidth,
        `ops incident scrolls horizontally at ${width}px`,
      ).toBeLessThanOrEqual(overflow.clientWidth);

      // All four steps survive at every width — a truncated path would drop
      // the re-read, which is the only step that confirms anything.
      expect(await page.locator("[data-incident-step]").count()).toBe(4);
      await expect(page.locator('[data-incident-step="reread"]')).toContainText(
        "Only this shows whether the condition is actually resolved",
      );
      await expect(page.locator('[data-incident-step="act"]')).toContainText(
        "accepted, refused, or ambiguous",
      );

      await context.close();
    });
  }
}

/**
 * WP-25 · marketing presentation at 1440/390/320.
 *
 * Long legal prose is the hard case: readable at 320 without the page scrolling
 * sideways, and bounded measure at 1440 so a line does not run edge to edge.
 */
for (const width of [1440, 390, 320]) {
  for (const theme of THEMES) {
    test(`marketing presentation — ${width}px ${theme}`, async ({ browser }) => {
      const context = await browser.newContext({
        viewport: { width, height: 900 },
        colorScheme: theme,
      });
      const page = await context.newPage();
      const file = path.join(HARNESS_DIR, `marketing-${width}-${theme}.html`);
      if (!existsSync(file)) {
        throw new Error(`missing harness page ${file}. Run: npm run zero-base:shell:harness`);
      }
      await page.goto(pathToFileURL(file).href, { waitUntil: "load" });

      const overflow = await page.evaluate(() => ({
        scrollWidth: document.documentElement.scrollWidth,
        clientWidth: document.documentElement.clientWidth,
      }));
      expect(overflow.scrollWidth, `marketing scrolls horizontally at ${width}px`).toBeLessThanOrEqual(
        overflow.clientWidth,
      );

      // Ledger typography actually applied, not just the attribute present.
      const type = await page.evaluate(() => {
        const p = document.querySelector("[data-adc-marketing] p") as HTMLElement;
        const h1 = document.querySelector("[data-adc-marketing] h1") as HTMLElement;
        const style = getComputedStyle(p);
        return {
          fontSize: parseFloat(style.fontSize),
          lineHeight: parseFloat(style.lineHeight),
          maxWidth: style.maxWidth,
          h1Size: parseFloat(getComputedStyle(h1).fontSize),
        };
      });
      expect(type.fontSize, "body type is readable").toBeGreaterThanOrEqual(15);
      expect(type.lineHeight / type.fontSize, "line height is comfortable").toBeGreaterThan(1.4);
      // Measure is bounded so a wide viewport does not produce edge-to-edge lines.
      expect(type.maxWidth).not.toBe("none");
      expect(type.h1Size).toBeGreaterThan(type.fontSize);

      // Keyboard focus is visible for a visitor with no session.
      await page.locator("[data-adc-marketing] a").first().focus();
      const focusOutline = await page.evaluate(() => {
        const active = document.activeElement as HTMLElement;
        const style = getComputedStyle(active);
        return { width: style.outlineWidth, style: style.outlineStyle };
      });
      expect(focusOutline.style).not.toBe("none");
      expect(parseFloat(focusOutline.width)).toBeGreaterThan(0);

      // No product-only surface leaked into a public page. Asserted on the
      // DOM rather than the page source: the harness inlines globals.css,
      // whose text legitimately contains the product selector as a CSS rule.
      for (const selector of ['[data-adc-ui="zero-base"]', "[data-ops-shell]", "[data-shell]"]) {
        expect(await page.locator(selector).count(), selector).toBe(0);
      }
      expect(await page.locator("[data-adc-marketing]").count()).toBeGreaterThan(0);

      await context.close();
    });
  }
}
