#!/usr/bin/env bash
set -euo pipefail

# Host-side global sync cutover.
#
# WHY THIS EXISTS
#
# `scripts/global-sync-rollout.ts` is TypeScript run through npm. The app host
# has docker and docker compose and no Node, no npm, no node_modules — so
# `npm run rollout:enable` cannot run there. Everything below uses what the hosts
# actually have and reaches the repository's TypeScript by executing it inside
# the already-pinned worker image.
#
# HOW THIS FILE GETS TO THE APP HOST
#
# It does not arrive by magic and it is not in a git checkout on the host: the
# deploy only ever synced `docker-compose.yml`, so the runbook used to name a
# repository path that does not exist there.
#
# This file therefore lives under `scripts/`, which the worker image already
# copies (`COPY --from=builder /app/scripts /app/scripts`), so the release image
# carries it at `/app/scripts/hetzner-sync-cutover.sh` with no build-context
# special case. It used to live under `.github/`, which `.dockerignore` excludes,
# and reached the image only as a generated byte-identical duplicate — a second
# copy of a security-critical script, kept honest by a drift gate. Moving the
# file deleted the duplicate and the gate that guarded it.
#
# `scripts/cutover-wrapper-package.sh` records this file's SHA-256 in
# `scripts/cutover-wrapper.manifest`, which ships in the same image directory.
# `.github/scripts/hetzner-remote.sh deliver_cutover_wrapper` extracts both out
# of the exact pinned image, refuses unless the extracted script hashes to what
# the manifest pins, and installs them under `${APP_DIR}/cutover`.
# `assert_wrapper_integrity` below then re-hashes THIS FILE against that manifest
# before any phase runs, so a wrapper that was edited on the host, truncated by a
# failed copy, or carried over from another release refuses instead of driving a
# cutover nobody reviewed.
#
# TWO HOSTS
#
# The application and PostgreSQL are on SEPARATE hosts. The app host has the
# Compose project and no local PostgreSQL socket; the DB host has PostgreSQL and
# no Compose project. Assuming both live together is how a cutover script fails
# on its first real run. Every database operation therefore goes through
# `db_sql`/`db_run`, which use `SYNC_CUTOVER_DB_SSH` when set and fall back to a
# local psql only for single-host development.
#
# PHASE GRAPH
#
# Preflight is OLD-SCHEMA SAFE — it checks images, the env file, a freshly taken
# and scratch-restored backup, the scheduler and the database identity, none of
# which depend on the new schema — and the post-migration schema contract is its
# own phase AFTER migrate. A preflight that ran the post-migration contract could
# never pass before the migration it gates, which is a deadlock, not a gate.
#
# WHAT IS AND IS NOT ATOMIC
#
# Nothing here is atomic across hosts, and this file does not pretend otherwise.
# What is actually guaranteed:
#   - the env file is REPLACED by a rename within one filesystem, so a reader
#     sees either the whole old file or the whole new file, never a partial one;
#   - the previous (disabled) env file is copied aside first, so the disabled
#     configuration can always be put back byte-for-byte;
#   - the root crontab is replaced as a whole document, so the managed block and
#     every unrelated entry move together.
# What is NOT guaranteed:
#   - the RUNTIME does not change when the file changes. web and worker read
#     their environment when the container is created, so the runtime change is
#     the recreate, and the recreate is sequential: for a window measured in
#     seconds one container runs the new configuration and the other the old.
#     The cutover is built around both processes already being deployed and
#     disabled before that window opens, and around a failure inside the window
#     restoring the disabled env, stopping everything and invalidating the state
#     so the only way forward is a clean retry;
#   - a database migration is not undone by any of this. The rollback of record
#     is the backup artifact this script takes and scratch-restores.
#
#   ./hetzner-sync-cutover.sh <phase>
#
# Phases, in order:
#   preflight         old-schema safe; images, env, FRESH verified backup, scheduler, DB
#   quiesce           stop the real scheduler, autoheal, web, worker; prove drain
#   fingerprint-pre   DB identity, schema identity, counts, identity/generation hashes
#   migrate           run migrations from the pinned image
#   verify-contract   POST-migration schema contract (needs the new schema)
#   fingerprint-post  compare against the pre-migration fingerprint
#   deploy-disabled   both processes on the new build with every lane off
#   enable            update the preserved env, recreate both, verify, roll back on failure
#   resume-scheduler  re-enable the real scheduler, last
#   emergency-disable stop live runtime and scheduler; INVALIDATE the enable proof
#   status            print the state record and live state

PHASE="${1:-status}"
APP_DIR="${REMOTE_APP_DIR:-/var/www/adsecute}"
ENV_FILE="${APP_DIR}/.env.production"
STATE_DIR="${SYNC_CUTOVER_STATE_DIR:-/var/lib/adsecute-cutover}"
# The versioned state RECORD. The previous append-only list of phase strings
# could not answer "is this the same cutover?" — it survived a retag, an env
# edit, a different DEPLOY_SHA and an emergency stop, and every one of those
# leaves the recorded phases meaningless.
STATE_FILE="${STATE_DIR}/state"
STATE_VERSION=2
IMAGE_PIN_FILE="${STATE_DIR}/image-pin"
LOCK_FILE="${STATE_DIR}/lock"

CUTOVER_DIR="${SYNC_CUTOVER_INSTALL_DIR:-${APP_DIR}/cutover}"
WRAPPER_MANIFEST="${SYNC_CUTOVER_WRAPPER_MANIFEST:-${CUTOVER_DIR}/cutover-wrapper.manifest}"

# Where the FRESH cutover backup and its manifest are written ON THE DB HOST.
BACKUP_ROOT="${SYNC_CUTOVER_BACKUP_ROOT:-/var/backups/adsecute-cutover}"
BACKUP_MANIFEST="${SYNC_CUTOVER_BACKUP_MANIFEST:-}"

DRAIN_SECONDS="${SYNC_CUTOVER_DRAIN_SECONDS:-90}"
DB_NAME="${DB_NAME:-adsecute_prod}"

# The DB host. Empty means "PostgreSQL is reachable locally", which is only true
# in development.
DB_SSH="${SYNC_CUTOVER_DB_SSH:-}"

# One multiplexed connection for the whole cutover, not one per statement.
#
# A cutover issues dozens of separate database calls. Opening a fresh SSH
# connection for each one is fine on a quiet host and fails on a busy one: the
# database host runs `sshd` with a MaxStartups limit, and internet-facing brute
# force traffic keeps that queue full, so an unlucky connection is dropped and
# the phase dies mid-backup. Observed exactly that: "drop connection ... past
# MaxStartups" while taking the rollback artifact.
#
# ControlMaster reuses a single authenticated channel, so the whole cutover
# costs one connection attempt instead of dozens. ControlPersist keeps it warm
# between phases. ServerAlive keeps a long pg_dump from looking idle.
DB_SSH_CONTROL_DIR="${SYNC_CUTOVER_SSH_CONTROL_DIR:-${STATE_DIR}/ssh}"
db_ssh_opts() {
  mkdir -p "${DB_SSH_CONTROL_DIR}" 2>/dev/null || true
  chmod 0700 "${DB_SSH_CONTROL_DIR}" 2>/dev/null || true
  printf '%s\n' \
    -o BatchMode=yes \
    -o ConnectTimeout=20 \
    -o ConnectionAttempts=5 \
    -o ServerAliveInterval=30 \
    -o ServerAliveCountMax=20 \
    -o ControlMaster=auto \
    -o ControlPersist=900 \
    -o "ControlPath=${DB_SSH_CONTROL_DIR}/cutover-%C"
}

# `lib/db.ts` connects with application_name `omniads-web` / `omniads-worker`.
# Quiescence is decided on ACTUAL backends carrying that name, because that is
# the only thing that says whether application code is touching the database
# right now.
APP_NAME_PREFIX="${SYNC_CUTOVER_APP_NAME_PREFIX:-omniads}"

# The root crontab block this script owns. Everything outside these two markers
# belongs to somebody else — healthz probes, backups, certificate renewals — and
# must survive a cutover byte-for-byte.
ROOTCRON_BEGIN='# BEGIN adsecute-sync'
ROOTCRON_END='# END adsecute-sync'
ROOTCRON_USER="${SYNC_CUTOVER_ROOT_CRONTAB_USER:-root}"

# How the external trigger is actually run. Declared rather than assumed: an
# earlier version accepted a missing systemd unit during quiesce and then
# REQUIRED that same unit to exist when resuming, so a deployment using cron
# would quiesce "successfully" and then fail to resume.
#   systemd:<unit>     systemctl enable/disable --now
#   cron:<file>        a crontab fragment moved aside and back
#   rootcron           a delimited block inside the ROOT crontab
#   compose:<service>  a Compose service stopped and started
#   none               explicitly no external scheduler, and it must be PROVEN
SCHEDULER_SPEC="${SYNC_CUTOVER_SCHEDULER:-}"

EXPECTED_SHA="${DEPLOY_SHA:-}"
EXPECTED_WEB_IMAGE="ghcr.io/erhanrdn/omniads-web:${EXPECTED_SHA}"
EXPECTED_WORKER_IMAGE="ghcr.io/erhanrdn/omniads-worker:${EXPECTED_SHA}"

# Every key this cutover is allowed to change in the env file. `enable` diffs the
# file it produced against the disabled copy and refuses if anything outside this
# set moved, because the rollout script runs inside a container with the whole
# env file mounted and a bug there would otherwise rewrite credentials silently.
MANAGED_ENV_KEY_PATTERN='^ADSECUTE_SYNC_(GLOBAL_ENABLED|LANE_[A-Z0-9_]+_ENABLED)$'

log() { printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1"; }
die() { printf '[%s] ABORT %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$1" >&2; exit 1; }

mkdir -p "${STATE_DIR}"
chmod 0700 "${STATE_DIR}" 2>/dev/null || true
touch "${STATE_FILE}" "${LOCK_FILE}"
chmod 0600 "${STATE_FILE}"

# ── Portable digests ───────────────────────────────────────────────────────
#
# The DB host and the app host are Debian and have `sha256sum`; a developer
# machine driving the harness is macOS and has `shasum`. Picking one and hoping
# is how the integrity check becomes an unconditional die on somebody's laptop.
sha256_file() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum "$1" | awk '{print $1}'
  else
    shasum -a 256 "$1" | awk '{print $1}'
  fi
}

sha256_stdin() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum | awk '{print $1}'
  else
    shasum -a 256 | awk '{print $1}'
  fi
}

sha256_string() { printf '%s' "$1" | sha256_stdin; }

file_bytes() { wc -c < "$1" | tr -d '[:space:]'; }

# The same digest, computed ON THE DB HOST, where this script only has a shell.
REMOTE_SHA256_FN='sha256_of() { if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk "{print \$1}"; else shasum -a 256 "$1" | awk "{print \$1}"; fi; }'

# ── F21.1: the wrapper proves it is the wrapper that was released ──────────

assert_wrapper_integrity() {
  local expected actual source
  source="${BASH_SOURCE[0]}"
  [ -f "${WRAPPER_MANIFEST}" ] \
    || die "no wrapper manifest at ${WRAPPER_MANIFEST}; this script was not delivered by a deploy. Run '.github/scripts/hetzner-remote.sh deliver_cutover_wrapper' for the release being cut over to."
  expected="$(awk -F= '$1 == "wrapper_sha256" { print $2 }' "${WRAPPER_MANIFEST}" | tr -d '[:space:]')"
  [ -n "${expected}" ] \
    || die "${WRAPPER_MANIFEST} records no wrapper_sha256; refusing to run an unpinned cutover wrapper"
  actual="$(sha256_file "${source}")"
  [ "${actual}" = "${expected}" ] \
    || die "this wrapper hashes ${actual}, the delivered manifest pins ${expected}. The file on this host is not the released cutover script — re-deliver it; do NOT edit it in place."
  log "wrapper integrity OK sha256=${actual}"
}

# ── F21.4: the versioned state record ──────────────────────────────────────
#
# Every phase re-derives the bindings below and compares them to what preflight
# recorded. A cutover that drifts — a different DEPLOY_SHA, a retagged image, a
# hand-edited env file, a swapped database, a scheduler rewired underneath it,
# a replaced backup — must stop at the next phase boundary rather than complete
# on top of premises that are no longer true.

state_get() {
  awk -F= -v key="$1" '$1 == key { sub(/^[^=]*=/, ""); print; exit }' "${STATE_FILE}"
}

state_set() {
  local key="$1" value="$2" tmp
  tmp="$(mktemp "${STATE_DIR}/state.XXXXXX")"
  awk -F= -v key="${key}" '$1 != key { print }' "${STATE_FILE}" > "${tmp}"
  printf '%s=%s\n' "${key}" "${value}" >> "${tmp}"
  chmod 0600 "${tmp}"
  mv "${tmp}" "${STATE_FILE}"
}

state_chain() { state_get phase_chain; }

state_chain_has() {
  case ",$(state_chain)," in
    *",$1,"*) return 0 ;;
    *) return 1 ;;
  esac
}

state_chain_add() {
  local chain
  chain="$(state_chain)"
  if state_chain_has "$1"; then return 0; fi
  if [ -z "${chain}" ]; then chain="$1"; else chain="${chain},$1"; fi
  state_set phase_chain "${chain}"
}

state_chain_drop() {
  local chain out=""
  chain="$(state_chain)"
  local IFS=,
  for item in ${chain}; do
    local keep=yes
    for drop in "$@"; do
      [ "${item}" = "${drop}" ] && keep=no
    done
    if [ "${keep}" = "yes" ]; then
      if [ -z "${out}" ]; then out="${item}"; else out="${out},${item}"; fi
    fi
  done
  state_set phase_chain "${out}"
}

require_phase() {
  state_chain_has "$1" \
    || die "phase '$1' has not completed in this cutover (chain='$(state_chain)'); run it first"
  [ "$(state_get invalidated)" != "yes" ] \
    || die "this cutover was INVALIDATED at $(state_get invalidated_utc) after '$(state_get invalidated_after)'. Every runtime proof it held is void; re-run deploy-disabled to re-establish one."
}

require_sha() {
  [ -n "${EXPECTED_SHA}" ] || die "DEPLOY_SHA is required and must be the exact commit being cut over to"
  case "${EXPECTED_SHA}" in
    *[!0-9a-f]* | "") die "DEPLOY_SHA must be a lowercase hex commit sha" ;;
  esac
}

# ── The Sync release identity record ─────────────────────────────────────────
#
# A dedicated, root-owned, atomically written record of WHICH RELEASE this
# cutover is. It exists because `current-build-info.json` is written by an
# unrelated workflow: racing or clobbering that file would corrupt a diagnostic
# somebody else owns, and it never described the deployed image anyway.
#
# What it binds, and why each field is load-bearing:
#   source_sha          the commit being cut over to
#   base_sha            the commit it was built ON, so a rebase is visible
#   remote_branch_sha   what the pushed branch resolves to; a deploy from an
#                       unpushed tree is untraceable
#   *_image_id          immutable image ids — a TAG can be moved, an id cannot
#   *_image_revision    the OCI revision LABEL baked into the image, which is
#                       the only thing that ties an image id back to a commit
#   wrapper/manifest/policy sha256  the exact cutover tooling in force
#   backup_manifest_id  the rollback artifact this cutover is authorised against
#   prev_*              the exact identity a rollback must restore
#
# It carries no secret: shas, ids, digests, paths and a phase name.
RELEASE_RECORD="${SYNC_CUTOVER_RELEASE_RECORD:-${STATE_DIR}/sync-release-identity}"
RELEASE_RECORD_VERSION=1

release_get() {
  [ -f "${RELEASE_RECORD}" ] || return 0
  awk -F= -v key="$1" '$1 == key { sub(/^[^=]*=/, ""); print; exit }' "${RELEASE_RECORD}"
}

# Atomic: write a temp file in the SAME directory, fsync-ish via mv, then mode.
# A partial write must never be readable as a valid record, so the temp file is
# created 0600 before any content reaches it and the rename is the commit point.
release_set() {
  local key="$1" value="$2" tmp
  case "${key}" in
    *[!a-z0-9_]*) die "refusing to write release record key '${key}'" ;;
  esac
  tmp="$(mktemp "${STATE_DIR}/relrec.XXXXXX")"
  chmod 0600 "${tmp}"
  if [ -f "${RELEASE_RECORD}" ]; then
    awk -F= -v key="${key}" '$1 != key { print }' "${RELEASE_RECORD}" > "${tmp}"
  fi
  printf '%s=%s
' "${key}" "${value}" >> "${tmp}"
  chown root:root "${tmp}" 2>/dev/null || true
  mv "${tmp}" "${RELEASE_RECORD}"
  chmod 0600 "${RELEASE_RECORD}" 2>/dev/null || true
  chown root:root "${RELEASE_RECORD}" 2>/dev/null || true
}

image_revision_label() {
  docker image inspect "$1" \
    --format '{{index .Config.Labels "org.opencontainers.image.revision"}}' 2>/dev/null || true
}

# Everything the record should say about the release being cut over to, derived
# fresh. Called at preflight to WRITE it and later to CHECK against it.
release_identity_now() {
  printf 'record_version=%s\n' "${RELEASE_RECORD_VERSION}"
  printf 'source_sha=%s\n' "${EXPECTED_SHA}"
  printf 'base_sha=%s\n' "${RELEASE_BASE_SHA:-unset}"
  printf 'remote_branch_sha=%s\n' "${RELEASE_REMOTE_SHA:-unset}"
  printf 'web_image_id=%s\n' "$(docker image inspect "${EXPECTED_WEB_IMAGE}" --format '{{.Id}}' 2>/dev/null || true)"
  printf 'worker_image_id=%s\n' "$(docker image inspect "${EXPECTED_WORKER_IMAGE}" --format '{{.Id}}' 2>/dev/null || true)"
  printf 'web_image_revision=%s\n' "$(image_revision_label "${EXPECTED_WEB_IMAGE}")"
  printf 'worker_image_revision=%s\n' "$(image_revision_label "${EXPECTED_WORKER_IMAGE}")"
  printf 'wrapper_sha256=%s\n' "$(sha256_file "$0")"
  printf 'manifest_sha256=%s\n' "$([ -f "${WRAPPER_MANIFEST}" ] && sha256_file "${WRAPPER_MANIFEST}" || echo missing)"
  printf 'policy_sha256=%s\n' "$([ -f "${RECOVERY_POLICY_FILE}" ] && sha256_file "${RECOVERY_POLICY_FILE}" || echo missing)"
}

# The record must exist, be well-formed, and describe THIS release.
assert_release_record() {
  local context="$1" want got key
  [ -f "${RELEASE_RECORD}" ] \
    || die "no Sync release identity record at ${RELEASE_RECORD}; run preflight for this release first"
  [ "$(release_get record_version)" = "${RELEASE_RECORD_VERSION}" ] \
    || die "release record is version '$(release_get record_version)', this wrapper writes ${RELEASE_RECORD_VERSION}; they do not describe the same release"
  # A truncated record — a partial write, a full disk — must refuse rather than
  # read as "some fields happen to match".
  for key in record_version source_sha web_image_id worker_image_id \
             web_image_revision worker_image_revision wrapper_sha256 \
             manifest_sha256 policy_sha256; do
    [ -n "$(release_get "${key}")" ] \
      || die "release record is missing '${key}'; it is truncated or was written by a different tool. Refusing to ${context}."
  done

  release_identity_now | while IFS= read -r line; do
    key="${line%%=*}"; want="${line#*=}"
    got="$(release_get "${key}")"
    if [ "${want}" != "${got}" ]; then
      printf 'release identity MISMATCH on %s: record=%s now=%s\n' "${key}" "${got}" "${want}" >&2
      exit 90
    fi
  done || die "the release identity changed since preflight; refusing to ${context}"

  # The image must SAY which commit it is. An image whose revision label does
  # not equal the sha being deployed is not this release, whatever its tag says.
  [ "$(release_get web_image_revision)" = "${EXPECTED_SHA}" ] \
    || die "the web image's OCI revision label is '$(release_get web_image_revision)', not ${EXPECTED_SHA}; refusing to ${context}"
  [ "$(release_get worker_image_revision)" = "${EXPECTED_SHA}" ] \
    || die "the worker image's OCI revision label is '$(release_get worker_image_revision)', not ${EXPECTED_SHA}; refusing to ${context}"

  # A deploy from an unpushed tree cannot be traced back to anything.
  if [ -n "${RELEASE_REMOTE_SHA:-}" ] && [ "${RELEASE_REMOTE_SHA}" != "unset" ]; then
    [ "${RELEASE_REMOTE_SHA}" = "${EXPECTED_SHA}" ] \
      || die "the pushed branch resolves to ${RELEASE_REMOTE_SHA}, not the ${EXPECTED_SHA} being deployed; refusing to ${context}"
  fi
}

# After a container swap: what is RUNNING must be the release, not merely
# something that started successfully.
assert_running_image_identity() {
  local svc cid img rev
  for svc in web worker; do
    cid="$(docker compose ps -q "${svc}" 2>/dev/null | head -1)"
    [ -n "${cid}" ] || die "service '${svc}' is not running after the swap; refusing to enable"
    img="$(docker inspect "${cid}" --format '{{.Image}}' 2>/dev/null || true)"
    rev="$(docker inspect "${cid}" --format '{{index .Config.Labels "org.opencontainers.image.revision"}}' 2>/dev/null || true)"
    case "${svc}" in
      web) [ "${img}" = "$(release_get web_image_id)" ] \
             || die "the running web container is image ${img}, the release record pins $(release_get web_image_id); refusing to enable" ;;
      worker) [ "${img}" = "$(release_get worker_image_id)" ] \
             || die "the running worker container is image ${img}, the release record pins $(release_get worker_image_id); refusing to enable" ;;
    esac
    [ "${rev}" = "${EXPECTED_SHA}" ] \
      || die "the running ${svc} container reports revision '${rev}', not ${EXPECTED_SHA}; refusing to enable"
  done
  log "running containers verified against the release record: web+worker both ${EXPECTED_SHA}"
}

# Retagging between phases must refuse. A tag is mutable; the image id is not.
assert_image_pin() {
  local pinned_web pinned_worker web_digest worker_digest
  [ -s "${IMAGE_PIN_FILE}" ] || die "no image pin recorded; run preflight first"
  read -r pinned_web pinned_worker < "${IMAGE_PIN_FILE}"
  web_digest="$(docker image inspect "${EXPECTED_WEB_IMAGE}" --format '{{.Id}}' 2>/dev/null || true)"
  worker_digest="$(docker image inspect "${EXPECTED_WORKER_IMAGE}" --format '{{.Id}}' 2>/dev/null || true)"
  [ "${web_digest}" = "${pinned_web}" ] \
    || die "the web image tag now resolves to ${web_digest}, not the pinned ${pinned_web}; it was retagged mid-cutover"
  [ "${worker_digest}" = "${pinned_worker}" ] \
    || die "the worker image tag now resolves to ${worker_digest}, not the pinned ${pinned_worker}; it was retagged mid-cutover"
}

# ── Two-host primitives ────────────────────────────────────────────────────

# Run SQL on the DATABASE host. The statement travels on STDIN rather than
# inside a nested shell quote: a hash query contains newlines, single quotes and
# `$` and there is no defensible way to quote that twice through ssh.
db_sql_on() {
  local database="$1" statement="$2"
  if [ -n "${DB_SSH}" ]; then
    local -a opts; IFS=$'\n' read -r -d '' -a opts < <(db_ssh_opts; printf '\0')
    printf '%s\n' "${statement}" | ssh "${opts[@]}" "${DB_SSH}" \
      "runuser -u postgres -- psql --dbname=$(printf %q "${database}") -v ON_ERROR_STOP=1 --tuples-only --no-align --file=-"
  else
    printf '%s\n' "${statement}" | runuser -u postgres -- psql --dbname="${database}" \
      -v ON_ERROR_STOP=1 --tuples-only --no-align --file=-
  fi
}

db_sql() { db_sql_on "${DB_NAME}" "$1"; }

# Run a command on the DATABASE host.
db_run() {
  if [ -n "${DB_SSH}" ]; then
    local -a opts; IFS=$'\n' read -r -d '' -a opts < <(db_ssh_opts; printf '\0')
    ssh "${opts[@]}" "${DB_SSH}" "$@"
  else
    "$@"
  fi
}

# Write a file on the DATABASE host from stdin.
db_write_file() {
  if [ -n "${DB_SSH}" ]; then
    local -a opts; IFS=$'\n' read -r -d '' -a opts < <(db_ssh_opts; printf '\0')
    ssh "${opts[@]}" "${DB_SSH}" "cat > $(printf %q "$1")"
  else
    cat > "$1"
  fi
}

db_read_file() {
  db_run "cat $(printf %q "$1")"
}

# ── F21.3: root crontab block management ───────────────────────────────────
#
# The Sync/AI entries live in the ROOT crontab next to a healthz probe and
# unrelated jobs. `crontab -r`, a rewritten file, or "comment out everything
# that mentions adsecute" all silently take those unrelated entries down with
# them, and nobody notices until the thing they scheduled fails to run. This
# manages exactly one delimited block and proves, by digest, that every byte
# outside it is unchanged.

rootcron_read() {
  crontab -l -u "${ROOTCRON_USER}" 2>/dev/null || true
}

rootcron_write() {
  crontab -u "${ROOTCRON_USER}" -
}

# Splits the current crontab into "outside" and "block", and prints the line
# index in the outside stream at which the block started (-1 when absent).
rootcron_split() {
  local current="$1" outside="$2" block="$3"
  : > "${outside}"
  : > "${block}"
  awk -v begin="${ROOTCRON_BEGIN}" -v end="${ROOTCRON_END}" \
      -v outside="${outside}" -v block="${block}" '
    BEGIN { inside = 0; found = 0; outcount = 0; startidx = -1 }
    {
      if (!inside && $0 == begin) { inside = 1; found = 1; startidx = outcount; print > block; next }
      if (inside) { print > block; if ($0 == end) { inside = 0 }; next }
      print > outside; outcount++
    }
    END {
      if (inside) exit 3
      if (!found) startidx = -1
      print startidx
    }
  ' "${current}"
}

rootcron_block_hash() {
  local tmp outside block
  tmp="$(mktemp)"; outside="$(mktemp)"; block="$(mktemp)"
  rootcron_read > "${tmp}"
  if rootcron_split "${tmp}" "${outside}" "${block}" >/dev/null; then
    if [ -s "${block}" ]; then
      sha256_file "${block}"
    elif [ -s "${STATE_DIR}/rootcron.block" ]; then
      sha256_file "${STATE_DIR}/rootcron.block"
    else
      printf 'absent'
    fi
  else
    printf 'unterminated'
  fi
  rm -f "${tmp}" "${outside}" "${block}"
}

rootcron_stop() {
  local tmp outside block start
  tmp="$(mktemp)"; outside="$(mktemp)"; block="$(mktemp)"
  rootcron_read > "${tmp}"
  start="$(rootcron_split "${tmp}" "${outside}" "${block}")" \
    || die "the root crontab has a '${ROOTCRON_BEGIN}' with no '${ROOTCRON_END}'; refusing to guess where the managed block ends"
  if [ "${start}" = "-1" ]; then
    log "root crontab has no managed block; nothing to stop"
    rm -f "${tmp}" "${outside}" "${block}"
    return 0
  fi
  # Everything outside the block is what must survive. It is saved with its
  # digest so `resume-scheduler` can prove nothing else changed meanwhile.
  cp "${block}" "${STATE_DIR}/rootcron.block"
  cp "${outside}" "${STATE_DIR}/rootcron.outside"
  chmod 0600 "${STATE_DIR}/rootcron.block" "${STATE_DIR}/rootcron.outside"
  state_set rootcron_block_index "${start}"
  state_set rootcron_outside_sha256 "$(sha256_file "${outside}")"
  state_set rootcron_block_sha256 "$(sha256_file "${block}")"
  rootcron_write < "${outside}"

  # Read back. `crontab` exiting 0 is not proof the daemon accepted the file.
  local verify_tmp verify_outside verify_block
  verify_tmp="$(mktemp)"; verify_outside="$(mktemp)"; verify_block="$(mktemp)"
  rootcron_read > "${verify_tmp}"
  rootcron_split "${verify_tmp}" "${verify_outside}" "${verify_block}" >/dev/null \
    || die "the root crontab is unparseable after removing the managed block"
  [ ! -s "${verify_block}" ] \
    || die "the managed block is still present in the root crontab after removal"
  [ "$(sha256_file "${verify_outside}")" = "$(state_get rootcron_outside_sha256)" ] \
    || die "removing the managed block changed unrelated root crontab lines; the crontab has been rewritten by something else"
  log "root crontab: managed block removed at line ${start}, $(wc -l < "${verify_outside}" | tr -d '[:space:]') unrelated line(s) preserved byte-for-byte"
  rm -f "${tmp}" "${outside}" "${block}" "${verify_tmp}" "${verify_outside}" "${verify_block}"
}

rootcron_start() {
  local saved_block="${STATE_DIR}/rootcron.block"
  [ -s "${saved_block}" ] \
    || die "no saved root crontab block in ${saved_block}; refusing to invent Sync schedule entries"
  local tmp outside block start rebuilt
  tmp="$(mktemp)"; outside="$(mktemp)"; block="$(mktemp)"; rebuilt="$(mktemp)"
  rootcron_read > "${tmp}"
  rootcron_split "${tmp}" "${outside}" "${block}" >/dev/null \
    || die "the root crontab is unparseable; refusing to rewrite it"
  [ ! -s "${block}" ] || die "the managed block is already present; the scheduler was restarted by something else"
  [ "$(sha256_file "${outside}")" = "$(state_get rootcron_outside_sha256)" ] \
    || die "unrelated root crontab lines changed while the Sync block was out. Someone else edited the crontab during the cutover; reconcile by hand before resuming."

  start="$(state_get rootcron_block_index)"
  case "${start}" in "" | *[!0-9]*) start=0 ;; esac
  awk -v idx="${start}" -v blockfile="${saved_block}" '
    BEGIN { emitted = 0 }
    {
      if (NR - 1 == idx) { while ((getline line < blockfile) > 0) print line; close(blockfile); emitted = 1 }
      print
    }
    END { if (!emitted) { while ((getline line < blockfile) > 0) print line; close(blockfile) } }
  ' "${outside}" > "${rebuilt}"
  rootcron_write < "${rebuilt}"

  local verify_tmp verify_outside verify_block
  verify_tmp="$(mktemp)"; verify_outside="$(mktemp)"; verify_block="$(mktemp)"
  rootcron_read > "${verify_tmp}"
  rootcron_split "${verify_tmp}" "${verify_outside}" "${verify_block}" >/dev/null \
    || die "the root crontab is unparseable after restoring the managed block"
  cmp -s "${verify_block}" "${saved_block}" \
    || die "the restored managed block is not byte-identical to the one that was removed"
  [ "$(sha256_file "${verify_outside}")" = "$(state_get rootcron_outside_sha256)" ] \
    || die "restoring the managed block changed unrelated root crontab lines"
  log "root crontab: managed block restored byte-for-byte, unrelated lines untouched"
  rm -f "${tmp}" "${outside}" "${block}" "${rebuilt}" "${verify_tmp}" "${verify_outside}" "${verify_block}"
}

rootcron_state() {
  local tmp outside block
  tmp="$(mktemp)"; outside="$(mktemp)"; block="$(mktemp)"
  rootcron_read > "${tmp}"
  if ! rootcron_split "${tmp}" "${outside}" "${block}" >/dev/null; then
    printf 'unknown'
  elif grep -Eqv '^[[:space:]]*(#.*)?$' "${block}" 2>/dev/null; then
    printf 'running'
  else
    printf 'stopped'
  fi
  rm -f "${tmp}" "${outside}" "${block}"
}

# ── Scheduler control, for whatever the scheduler actually is ──────────────

# `none` is a claim, not an observation. Accepting it on the operator's word is
# how a cutover quiesces "successfully" while a crontab entry keeps firing sync
# runs into a half-migrated database, so every place a scheduler could live is
# checked before the claim is honoured.
assert_no_scheduler_exists() {
  local found=""
  if rootcron_read | grep -Eqi 'adsecute|omniads'; then
    found="${found} root-crontab"
  fi
  if ls /etc/cron.d 2>/dev/null | grep -qi 'adsecute'; then
    found="${found} /etc/cron.d"
  fi
  if command -v systemctl >/dev/null 2>&1 &&
     systemctl list-unit-files 2>/dev/null | grep -Eq 'adsecute.*\.(timer|service)'; then
    found="${found} systemd"
  fi
  if docker compose ps --services 2>/dev/null | grep -qx scheduler; then
    found="${found} compose"
  fi
  [ -z "${found}" ] \
    || die "SYNC_CUTOVER_SCHEDULER=none claims there is no external scheduler, but one was found in:${found}. Declare it explicitly instead."
  log "scheduler=none verified: no root crontab entry, no /etc/cron.d fragment, no systemd unit and no compose service references this application"
}

resolve_scheduler() {
  if [ -n "${SCHEDULER_SPEC}" ]; then
    printf '%s' "${SCHEDULER_SPEC}"
    return 0
  fi
  # Detect, in order of how this deployment is actually wired.
  if [ "$(rootcron_state)" = "running" ]; then
    printf 'rootcron'
    return 0
  fi
  if command -v systemctl >/dev/null 2>&1 &&
     systemctl list-unit-files 2>/dev/null | grep -q '^adsecute-sync-cron.timer'; then
    printf 'systemd:adsecute-sync-cron.timer'
    return 0
  fi
  if [ -f /etc/cron.d/adsecute-sync ]; then
    printf 'cron:/etc/cron.d/adsecute-sync'
    return 0
  fi
  if docker compose ps --services 2>/dev/null | grep -qx scheduler; then
    printf 'compose:scheduler'
    return 0
  fi
  printf 'unresolved'
}

scheduler_stop() {
  local spec="$1"
  case "${spec}" in
    systemd:*) systemctl disable --now "${spec#systemd:}" ;;
    cron:*) mv "${spec#cron:}" "${spec#cron:}.cutover-disabled" ;;
    rootcron) rootcron_stop ;;
    compose:*) docker compose stop "${spec#compose:}" ;;
    none) log "scheduler=none (verified absent); nothing to stop" ;;
    *) die "cannot stop scheduler: '${spec}' is not a supported spec. Set SYNC_CUTOVER_SCHEDULER explicitly." ;;
  esac
}

scheduler_start() {
  local spec="$1"
  case "${spec}" in
    systemd:*) systemctl enable --now "${spec#systemd:}" ;;
    cron:*) mv "${spec#cron:}.cutover-disabled" "${spec#cron:}" ;;
    rootcron) rootcron_start ;;
    compose:*) docker compose up -d "${spec#compose:}" ;;
    none) log "scheduler=none (verified absent); nothing to start" ;;
    *) die "cannot start scheduler: '${spec}' is not a supported spec" ;;
  esac
}

# Prints "running" or "stopped". Never guesses: an unsupported spec is fatal.
scheduler_state() {
  local spec="$1"
  case "${spec}" in
    systemd:*)
      if systemctl is-active --quiet "${spec#systemd:}" 2>/dev/null; then
        printf 'running'
      else
        printf 'stopped'
      fi
      ;;
    cron:*)
      if [ -f "${spec#cron:}" ]; then printf 'running'; else printf 'stopped'; fi
      ;;
    rootcron) rootcron_state ;;
    compose:*)
      case "$(container_state "${spec#compose:}")" in
        running) printf 'running' ;;
        *) printf 'stopped' ;;
      esac
      ;;
    none) printf 'stopped' ;;
    *) printf 'unknown' ;;
  esac
}

# The scheduler identity recorded in the state record. It is deliberately the
# digest of the MANAGED CONTENT, not of the live location, so it is stable while
# the scheduler is stopped — otherwise every phase between quiesce and resume
# would see a "changed" scheduler and refuse.
scheduler_hash() {
  local spec="$1"
  case "${spec}" in
    rootcron) rootcron_block_hash ;;
    systemd:*)
      local unit="${spec#systemd:}" path
      path="$(systemctl show -p FragmentPath --value "${unit}" 2>/dev/null || true)"
      if [ -n "${path}" ] && [ -f "${path}" ]; then sha256_file "${path}"; else sha256_string "${unit}"; fi
      ;;
    cron:*)
      local file="${spec#cron:}"
      if [ -f "${file}" ]; then sha256_file "${file}"
      elif [ -f "${file}.cutover-disabled" ]; then sha256_file "${file}.cutover-disabled"
      else printf 'absent'; fi
      ;;
    compose:*) sha256_string "${spec}" ;;
    none) printf 'none' ;;
    *) printf 'unknown' ;;
  esac
}

# ── App-host primitives ────────────────────────────────────────────────────

run_in_pinned_image() {
  docker run --rm \
    --network host \
    --env-file "${ENV_FILE}" \
    -e NODE_ENV=production \
    -e SYNC_ROLLOUT_PROJECT_DIR="${APP_DIR}" \
    -v "${APP_DIR}:${APP_DIR}" \
    -w /app \
    "${EXPECTED_WORKER_IMAGE}" \
    "$@"
}

container_state() {
  local service="$1" id
  id="$(docker compose ps -q "${service}" 2>/dev/null || true)"
  if [ -z "${id}" ]; then printf 'absent'; return; fi
  docker inspect "${id}" --format '{{.State.Status}}' 2>/dev/null || printf 'unknown'
}

assert_stopped() {
  local service="$1" observed
  observed="$(container_state "${service}")"
  case "${observed}" in
    absent | exited | created) log "${service}=${observed}" ;;
    *) die "${service} is '${observed}'; it must be stopped before continuing" ;;
  esac
}

# ── F21.6: the fingerprint ─────────────────────────────────────────────────
#
# Three row counts could not tell an expand-only migration from one that swapped
# one selected account for another, rotated a credential, dropped a connection or
# rewrote the release-gate history: all of those keep the counts identical. The
# fingerprint below is the full selected identity/position set, the connection
# and credential GENERATIONS (hashed — no token, no secret, ever leaves the
# database), the counts and content hashes of the raw/config/state/release-gate
# relations that exist, the migration schema identity, and the exact database id.

FINGERPRINT_TABLES="business_provider_accounts provider_connections integration_credentials provider_account_assignments provider_accounts meta_raw_snapshots shopify_raw_snapshots google_ads_raw_snapshots meta_config_snapshots meta_sync_state google_ads_sync_state shopify_sync_state sync_release_gates sync_runtime_instances sync_worker_heartbeats"

db_identity() {
  db_sql "SELECT current_database() || '|' || system_identifier::text FROM pg_control_system();" |
    tr -d '[:space:]'
}

db_system_identifier() {
  db_sql "SELECT system_identifier::text FROM pg_control_system();" | tr -d '[:space:]'
}

# The migration schema identity. There is no migration ledger table — migrations
# are idempotent DDL replayed every deploy — so schema identity has to come from
# the catalogue itself.
schema_identity_on() {
  db_sql_on "$1" "
    SELECT encode(sha256(convert_to(COALESCE(string_agg(sig, E'\n' ORDER BY sig), ''), 'UTF8')), 'hex')
    FROM (
      SELECT c.table_name || ':' || c.column_name || ':' || c.data_type || ':' || c.is_nullable AS sig
      FROM information_schema.columns c
      JOIN information_schema.tables t
        ON t.table_schema = c.table_schema AND t.table_name = c.table_name
      WHERE c.table_schema = 'public' AND t.table_type = 'BASE TABLE'
    ) s;
  " | tr -d '[:space:]'
}

# One round trip for every count, over exactly the relations that exist. A
# missing relation is reported as missing rather than aborting the statement,
# because the pre-migration and post-migration schemas legitimately differ.
table_counts_on() {
  local database="$1" values="" table
  for table in ${FINGERPRINT_TABLES}; do
    if [ -z "${values}" ]; then values="('${table}')"; else values="${values},('${table}')"; fi
  done
  db_sql_on "${database}" "
    WITH wanted(relname) AS (VALUES ${values})
    SELECT w.relname || '=' ||
           (xpath('/row/c/text()',
                  query_to_xml('SELECT count(*) AS c FROM public.' || quote_ident(w.relname),
                               false, true, '')))[1]::text
    FROM wanted w
    WHERE to_regclass('public.' || quote_ident(w.relname)) IS NOT NULL
    ORDER BY w.relname;
  "
}

# OLD-SCHEMA SAFE. `is_selected` is added BY the migration this cutover runs, so
# before it exists the query would fail and the pre-fingerprint could never be
# taken — the deadlock this phase graph exists to avoid. Before the column
# exists, the pre-model semantics are that every identity binding IS selected,
# so that is what gets hashed; after the migration the backfilled selected set
# must reproduce exactly the same digest.
selected_binding_hash_on() {
  db_sql_on "$1" "
    SELECT COALESCE(encode(sha256(convert_to(string_agg(identity, E'\n' ORDER BY identity), 'UTF8')), 'hex'), 'empty')
    FROM (
      SELECT bpa.business_id::text || '|' || bpa.provider || '|' || bpa.provider_account_id || '|' ||
             COALESCE(to_jsonb(bpa) ->> 'position', 'null') AS identity
      FROM business_provider_accounts bpa
      WHERE CASE
              WHEN EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_schema = current_schema()
                  AND table_name = 'business_provider_accounts'
                  AND column_name = 'is_selected'
              )
              THEN COALESCE((to_jsonb(bpa) ->> 'is_selected')::boolean, FALSE)
              ELSE TRUE
            END
    ) rows;
  " | tr -d '[:space:]'
}

connection_generation_hash_on() {
  db_sql_on "$1" "
    SELECT COALESCE(encode(sha256(convert_to(string_agg(sig, E'\n' ORDER BY sig), 'UTF8')), 'hex'), 'empty')
    FROM (
      SELECT pc.business_id::text || '|' || pc.provider || '|' ||
             COALESCE(to_jsonb(pc) ->> 'status', '') || '|' ||
             COALESCE(to_jsonb(pc) ->> 'provider_account_id', '') || '|' ||
             COALESCE(to_jsonb(pc) ->> 'updated_at', '') AS sig
      FROM provider_connections pc
    ) s;
  " | tr -d '[:space:]'
}

# The credential GENERATION, never the credential. Each token is reduced to its
# own digest before it is folded into the set digest, so a rotation is visible
# and the secret is not — including to anyone reading this script's output or
# the state directory.
credential_generation_hash_on() {
  db_sql_on "$1" "
    SELECT COALESCE(encode(sha256(convert_to(string_agg(sig, E'\n' ORDER BY sig), 'UTF8')), 'hex'), 'empty')
    FROM (
      SELECT ic.provider_connection_id::text || '|' ||
             encode(sha256(convert_to(
               COALESCE(to_jsonb(ic) ->> 'access_token', '') || '|' ||
               COALESCE(to_jsonb(ic) ->> 'refresh_token', ''), 'UTF8')), 'hex') || '|' ||
             COALESCE(to_jsonb(ic) ->> 'updated_at', '') AS sig
      FROM integration_credentials ic
    ) s;
  " | tr -d '[:space:]'
}

assignment_hash_on() {
  db_sql_on "$1" "
    SELECT COALESCE(encode(sha256(convert_to(string_agg(sig, E'\n' ORDER BY sig), 'UTF8')), 'hex'), 'empty')
    FROM (
      SELECT paa.business_id::text || '|' || paa.provider || '|' ||
             COALESCE(array_to_string(paa.account_ids, ','), '') AS sig
      FROM provider_account_assignments paa
    ) s;
  " | tr -d '[:space:]'
}

release_gate_hash_on() {
  db_sql_on "$1" "
    SELECT COALESCE(encode(sha256(convert_to(string_agg(sig, E'\n' ORDER BY sig), 'UTF8')), 'hex'), 'empty')
    FROM (
      SELECT srg.id::text || '|' || COALESCE(to_jsonb(srg) ->> 'build_id', '') || '|' ||
             COALESCE(to_jsonb(srg) ->> 'mode', '') AS sig
      FROM sync_release_gates srg
    ) s;
  " | tr -d '[:space:]'
}

counts_have_table() {
  printf '%s\n' "$1" | grep -q "^$2="
}

# The complete fingerprint of one database, as key=value lines.
fingerprint_of() {
  local database="$1" counts
  counts="$(table_counts_on "${database}")"
  printf 'identity=%s\n' "$(db_sql_on "${database}" "SELECT current_database() || '|' || system_identifier::text FROM pg_control_system();" | tr -d '[:space:]')"
  printf 'schema_identity=%s\n' "$(schema_identity_on "${database}")"
  printf 'selected_binding_hash=%s\n' "$(selected_binding_hash_on "${database}")"
  if counts_have_table "${counts}" provider_connections; then
    printf 'connection_generation_hash=%s\n' "$(connection_generation_hash_on "${database}")"
  else
    printf 'connection_generation_hash=absent\n'
  fi
  if counts_have_table "${counts}" integration_credentials; then
    printf 'credential_generation_hash=%s\n' "$(credential_generation_hash_on "${database}")"
  else
    printf 'credential_generation_hash=absent\n'
  fi
  if counts_have_table "${counts}" provider_account_assignments; then
    printf 'assignment_hash=%s\n' "$(assignment_hash_on "${database}")"
  else
    printf 'assignment_hash=absent\n'
  fi
  if counts_have_table "${counts}" sync_release_gates; then
    printf 'release_gate_hash=%s\n' "$(release_gate_hash_on "${database}")"
  else
    printf 'release_gate_hash=absent\n'
  fi
  printf '%s\n' "${counts}" | sed '/^$/d' | sed 's/^/count./'
}

# ── F21.2: a FRESH backup, scratch-restored, bound to this database ────────
#
# Preflight used to grep somebody else's manifest for `scratch_restore_verified=yes`.
# That manifest could have been written months ago, against another database, by
# a job whose artifact has since been rotated away — and the core backup it
# describes deliberately omits provider_connections, integration_credentials and
# the account assignments, which are precisely the rows a bad Sync migration
# destroys. A rollback plan that omits the data at risk is not a rollback plan.

backup_dir_for_epoch() { printf '%s/%s' "${BACKUP_ROOT}" "$1"; }

db_free_bytes_for() {
  db_run "df -Pk $(printf %q "$1") | awk 'NR==2 {print \$4 * 1024}'" | tr -d '[:space:]'
}

db_logical_bytes() {
  db_sql "SELECT pg_database_size(current_database())::text;" | tr -d '[:space:]'
}

# The tables whose DATA the rollback artifact deliberately does not carry, read
# from the SAME policy file the daily backup uses. One source of truth: a table
# cannot be tier B for the backup and tier A for the cutover.
RECOVERY_POLICY_FILE="${SYNC_CUTOVER_RECOVERY_POLICY:-${CUTOVER_DIR}/recovery-policy.tsv}"

# The policy decides which tables the rollback artifact carries, so a MISSING or
# ALTERED policy silently changes what "a complete rollback" means. If the
# delivered manifest pins its digest, it must match; and if the policy is absent
# entirely the wrapper refuses rather than quietly treating every table as tier A
# and then failing the capacity gate for a reason that looks unrelated.
assert_recovery_policy() {
  local pinned actual
  [ -f "${RECOVERY_POLICY_FILE}" ] \
    || die "no recovery policy at ${RECOVERY_POLICY_FILE}; it is delivered with the wrapper, so this wrapper was not installed by a deploy of this release"
  pinned="$(awk -F= '$1 == "delivered_policy_sha256" { print $2 }' "${WRAPPER_MANIFEST}" 2>/dev/null | tr -d '[:space:]')"
  if [ -n "${pinned}" ]; then
    actual="$(sha256_file "${RECOVERY_POLICY_FILE}")"
    [ "${pinned}" = "${actual}" ] \
      || die "the recovery policy hashes ${actual}, the delivered manifest pins ${pinned}. It was edited on this host; re-deliver it, do NOT edit it in place."
  fi
}

tier_b_table_list() {
  [ -f "${RECOVERY_POLICY_FILE}" ] || return 0
  awk -F'\t' '/^[[:space:]]*#/ { next } NF >= 2 && $2 == "B" { print $1 }' \
    "${RECOVERY_POLICY_FILE}" | LC_ALL=C sort -u
}

# A SQL list literal of the tier-B tables, or an impossible name when there are
# none, so the predicates below stay valid either way.
tier_b_sql_list() {
  local list first=1 out=""
  list="$(tier_b_table_list)"
  if [ -z "${list}" ]; then printf "''" ; return 0; fi
  while IFS= read -r t; do
    [ -n "${t}" ] || continue
    if [ "${first}" = "1" ]; then out="'${t}'"; first=0; else out="${out},'${t}'"; fi
  done <<EOF
${list}
EOF
  printf '%s' "${out}"
}

# What the ARTIFACT actually has to hold: heap + TOAST of the tables whose data
# it carries. Indexes are excluded because pg_dump ships CREATE INDEX, not index
# pages — on this database that is 47 of 136 GiB, and counting it was what made
# the old gate demand a filesystem nobody has.
db_included_dump_input_bytes() {
  db_sql "SELECT COALESCE(sum(pg_relation_size(c.oid) + COALESCE(pg_total_relation_size(c.reltoastrelid),0)),0)::text
          FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname='public' AND c.relkind='r'
            AND c.relname NOT IN ($(tier_b_sql_list));" | tr -d '[:space:]'
}

# What a SCRATCH RESTORE of that artifact inflates to: the same tables with their
# indexes rebuilt. This lands in the PostgreSQL data directory, not in
# BACKUP_ROOT, so it is measured against a different filesystem.
db_included_restored_bytes() {
  db_sql "SELECT COALESCE(sum(pg_total_relation_size(c.oid)),0)::text
          FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
          WHERE n.nspname='public' AND c.relkind='r'
            AND c.relname NOT IN ($(tier_b_sql_list));" | tr -d '[:space:]'
}

db_data_directory() {
  db_sql "SHOW data_directory;" | tr -d '[:space:]'
}

assert_capacity_for_migration() {
  local free logical required data_dir
  data_dir="$(db_data_directory)"
  [ -n "${data_dir}" ] || die "could not read the PostgreSQL data directory on the database host; refusing to migrate blind"
  free="$(db_free_bytes_for "${data_dir}" || true)"
  logical="$(db_logical_bytes || true)"
  case "${free}" in
    "" | *[!0-9]*) die "could not read free space on the database host's PostgreSQL data directory; refusing to migrate blind" ;;
  esac
  case "${logical}" in
    "" | *[!0-9]*) die "could not read the logical size of ${DB_NAME}; refusing to migrate blind" ;;
  esac
  # The backfill rewrites matched rows and the concurrent index builds need room
  # for the new relations plus WAL. Half the database again, with a 5 GiB floor,
  # is the smallest defensible headroom.
  required=$(( logical / 2 ))
  if [ "${required}" -lt 5368709120 ]; then required=5368709120; fi
  log "db free=${free}B logical=${logical}B required=${required}B"
  [ "${free}" -ge "${required}" ] \
    || die "insufficient free space on the database host: ${free}B free, ${required}B required for a ${logical}B database"
}

take_verified_backup() {
  local epoch="$1" dir artifact manifest scratch free logical prior_input prior_bytes sizing_basis artifact_bytes dump_input restored data_dir scratch_free artifact_required scratch_required exclude_flags
  dir="$(backup_dir_for_epoch "${epoch}")"
  artifact="${dir}/full.dump"
  manifest="${dir}/cutover-backup.manifest"
  scratch="adsecute_cutover_scratch_${epoch}"
  # PostgreSQL identifiers are limited to 63 bytes and the epoch carries a sha
  # prefix and a timestamp, so the scratch name is truncated deliberately rather
  # than silently by the server.
  scratch="$(printf '%s' "${scratch}" | tr -c 'a-z0-9_' '_' | cut -c1-60)"

  db_run "mkdir -p $(printf %q "${dir}") && chmod 0700 $(printf %q "${dir}")" \
    || die "could not create ${dir} on the database host"

  # Measured against what this artifact actually contains and where each part
  # lands — not against pg_database_size.
  #
  # The old gate demanded `logical + logical/4` under BACKUP_ROOT: on this
  # database 170 GiB, on a filesystem with 30. It was wrong twice over. It
  # counted 47 GiB of INDEX pages that pg_dump never writes, and it charged the
  # scratch restore to BACKUP_ROOT when a restore inflates into the PostgreSQL
  # DATA directory, which is usually a different filesystem entirely.
  #
  # The rollback artifact carries tier-A data only. That is sound because the
  # migration's write-set was proven: it adds columns and indexes to the tier-B
  # tables and mutates no pre-existing column of any of them, so undoing the
  # migration never needs their rows. Their DATA is archived separately by the
  # daily backup; their SCHEMA is in this artifact.
  logical="$(db_logical_bytes)"
  dump_input="$(db_included_dump_input_bytes)"
  restored="$(db_included_restored_bytes)"
  data_dir="$(db_data_directory)"
  free="$(db_free_bytes_for "${BACKUP_ROOT}")"
  scratch_free="$(db_free_bytes_for "${data_dir}")"
  case "${free}" in "" | *[!0-9]*) die "could not read free space for ${BACKUP_ROOT} on the database host" ;; esac
  case "${dump_input}" in "" | *[!0-9]*) die "could not measure the artifact's included dataset; refusing to back up blind" ;; esac
  case "${restored}" in "" | *[!0-9]*) die "could not measure the scratch-restore target size; refusing to back up blind" ;; esac
  case "${scratch_free}" in "" | *[!0-9]*) die "could not read free space for the data directory ${data_dir}" ;; esac

  # Sizing the artifact.
  #
  # The uncompressed input is an upper bound, but on this data it is a wildly
  # pessimistic one: measured on production, a 30.2 GiB tier-A input compresses
  # to a 1.40 GiB artifact — roughly 21x, because tier-A rows are small and
  # highly repetitive. Gating on the uncompressed figure would refuse a cutover
  # that fits twenty times over, which is how a safety check turns into a
  # phantom blocker.
  #
  # So: prefer EVIDENCE. If a previous artifact recorded both its input and its
  # resulting size, use that ratio with a 3x safety margin. With no evidence,
  # fall back to a deliberately cautious eighth of the input — still far above
  # any ratio observed here — and never below a 2 GiB floor.
  #
  # This is defence in depth, not the only protection: if the dump runs out of
  # space anyway, pg_dump fails and the phase dies before anything migrates.
  prior_input=""; prior_bytes=""
  if [ -f "${BACKUP_ROOT}/last-artifact-sizing" ]; then
    prior_input="$(awk -F= '$1=="input_bytes"{print $2}' "${BACKUP_ROOT}/last-artifact-sizing" | tr -d '[:space:]')"
    prior_bytes="$(awk -F= '$1=="artifact_bytes"{print $2}' "${BACKUP_ROOT}/last-artifact-sizing" | tr -d '[:space:]')"
  fi
  case "${prior_input}${prior_bytes}" in
    "" | *[!0-9]*) artifact_required=$(( dump_input / 8 )) ; sizing_basis="no_prior_measurement" ;;
    *)
      if [ "${prior_input}" -gt 0 ] 2>/dev/null; then
        artifact_required=$(( dump_input * prior_bytes * 3 / prior_input ))
        sizing_basis="measured_ratio_${prior_bytes}_over_${prior_input}"
      else
        artifact_required=$(( dump_input / 8 )); sizing_basis="no_prior_measurement"
      fi ;;
  esac
  if [ "${artifact_required}" -lt 2147483648 ]; then artifact_required=2147483648; fi
  log "capacity: artifact sizing basis=${sizing_basis}"
  scratch_required=$(( restored + restored / 4 ))
  log "capacity: artifact_input=${dump_input}B required=${artifact_required}B free(${BACKUP_ROOT})=${free}B"
  log "capacity: scratch_restore=${restored}B required=${scratch_required}B free(${data_dir})=${scratch_free}B"
  log "capacity: whole database is ${logical}B; the difference is index pages and tier-B data, neither of which this artifact carries"
  [ "${free}" -ge "${artifact_required}" ] \
    || die "insufficient free space for the cutover backup: ${free}B free under ${BACKUP_ROOT}, ${artifact_required}B required for a ${dump_input}B included dataset"
  [ "${scratch_free}" -ge "${scratch_required}" ] \
    || die "insufficient free space for the scratch restore: ${scratch_free}B free under ${data_dir}, ${scratch_required}B required to inflate a ${restored}B dataset"

  log "Taking a FRESH full backup of ${DB_NAME} on the database host"
  exclude_flags=""
  while IFS= read -r t; do
    [ -n "${t}" ] || continue
    exclude_flags="${exclude_flags} --exclude-table-data=public.${t}"
  done <<EOF
$(tier_b_table_list)
EOF
  # Redirected, not --file=.
  #
  # The artifact directory is created by this script as root with mode 0700, and
  # pg_dump runs as the postgres user, which cannot create a file inside it:
  # "could not open output file ... Permission denied". Redirecting makes the
  # ROOT shell on the database host create the file and pg_dump merely write to
  # its stdout. The daily backup script already does exactly this, for exactly
  # this reason.
  db_run "runuser -u postgres -- pg_dump --dbname=$(printf %q "${DB_NAME}") --format=custom --compress=9 --no-owner --no-privileges --no-tablespaces${exclude_flags} > $(printf %q "${artifact}")" \
    || die "pg_dump failed; there is no rollback artifact, so nothing may proceed"

  # Record what this artifact actually cost, so the next cutover sizes itself
  # against a measurement instead of a guess.
  # `wc -c <file` rather than `stat -c %s`: stat's flags differ between GNU and
  # BSD, and this script has to run against both.
  artifact_bytes="$(db_run "wc -c < $(printf %q "${artifact}")" | tr -d '[:space:]')"
  case "${artifact_bytes}" in
    "" | *[!0-9]*) : ;;
    *) db_run "printf 'input_bytes=%s\nartifact_bytes=%s\n' $(printf %q "${dump_input}") $(printf %q "${artifact_bytes}") > $(printf %q "${BACKUP_ROOT}/last-artifact-sizing")" || true
       log "capacity: artifact measured ${artifact_bytes}B from a ${dump_input}B input" ;;
  esac

  local artifact_sha artifact_bytes artifact_created
  artifact_sha="$(db_run "${REMOTE_SHA256_FN}; sha256_of $(printf %q "${artifact}")" | tr -d '[:space:]')"
  artifact_bytes="$(db_run "wc -c < $(printf %q "${artifact}")" | tr -d '[:space:]')"
  artifact_created="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  case "${artifact_bytes}" in "" | 0 | *[!0-9]*) die "the backup artifact ${artifact} is empty or unreadable" ;; esac
  log "backup artifact bytes=${artifact_bytes} sha256=${artifact_sha}"

  log "Scratch-restoring that artifact into ${scratch} and reading it back"
  db_run "runuser -u postgres -- dropdb --if-exists $(printf %q "${scratch}")" >/dev/null 2>&1 || true
  db_run "runuser -u postgres -- createdb $(printf %q "${scratch}")" \
    || die "could not create the scratch database ${scratch}; an unverified backup is not a rollback plan"
  # Piped, for the same reason the dump is redirected: the artifact lives in a
  # root-only directory, so the postgres user cannot even traverse to it. The
  # ROOT shell reads the file and pg_restore takes it on stdin.
  if ! db_run "cat $(printf %q "${artifact}") | runuser -u postgres -- pg_restore --dbname=$(printf %q "${scratch}") --no-owner --no-privileges --exit-on-error"; then
    db_run "runuser -u postgres -- dropdb --if-exists $(printf %q "${scratch}")" >/dev/null 2>&1 || true
    die "the fresh backup could NOT be restored. Do not migrate: this release has no rollback."
  fi

  local restored_schema restored_selected restored_connections restored_credentials restored_assignments restored_counts
  restored_schema="$(schema_identity_on "${scratch}")"
  restored_selected="$(selected_binding_hash_on "${scratch}")"
  restored_connections="$(connection_generation_hash_on "${scratch}")"
  restored_credentials="$(credential_generation_hash_on "${scratch}")"
  restored_counts="$(table_counts_on "${scratch}")"
  if counts_have_table "${restored_counts}" provider_account_assignments; then
    restored_assignments="$(assignment_hash_on "${scratch}")"
  else
    restored_assignments="absent"
  fi

  local live_schema live_selected live_connections live_credentials live_assignments live_counts
  live_schema="$(schema_identity_on "${DB_NAME}")"
  live_selected="$(selected_binding_hash_on "${DB_NAME}")"
  live_connections="$(connection_generation_hash_on "${DB_NAME}")"
  live_credentials="$(credential_generation_hash_on "${DB_NAME}")"
  live_counts="$(table_counts_on "${DB_NAME}")"
  if counts_have_table "${live_counts}" provider_account_assignments; then
    live_assignments="$(assignment_hash_on "${DB_NAME}")"
  else
    live_assignments="absent"
  fi

  db_run "runuser -u postgres -- dropdb --if-exists $(printf %q "${scratch}")" >/dev/null 2>&1 || true

  # The point of the scratch restore is not that it completed — it is that the
  # rows the Sync migration puts at risk came back identical.
  [ "${restored_schema}" = "${live_schema}" ] \
    || die "the restored backup's schema identity (${restored_schema}) differs from the live database (${live_schema}); the artifact does not describe this database"
  [ "${restored_selected}" = "${live_selected}" ] \
    || die "the restored backup does not reproduce the selected-binding set; it is not a usable rollback"
  [ "${restored_connections}" = "${live_connections}" ] \
    || die "the restored backup does not reproduce provider_connections; it is not a usable rollback"
  [ "${restored_credentials}" = "${live_credentials}" ] \
    || die "the restored backup does not reproduce integration_credentials; it is not a usable rollback"
  [ "${restored_assignments}" = "${live_assignments}" ] \
    || die "the restored backup does not reproduce the account assignments; it is not a usable rollback"

  local credential_count assignment_count connection_count binding_count
  credential_count="$(printf '%s\n' "${live_counts}" | awk -F= '$1=="integration_credentials"{print $2}')"
  assignment_count="$(printf '%s\n' "${live_counts}" | awk -F= '$1=="provider_account_assignments"{print $2}')"
  connection_count="$(printf '%s\n' "${live_counts}" | awk -F= '$1=="provider_connections"{print $2}')"
  binding_count="$(printf '%s\n' "${live_counts}" | awk -F= '$1=="business_provider_accounts"{print $2}')"

  {
    printf 'cutover_epoch=%s\n' "${epoch}"
    printf 'deploy_sha=%s\n' "${EXPECTED_SHA}"
    printf 'db_name=%s\n' "${DB_NAME}"
    printf 'db_system_identifier=%s\n' "$(db_system_identifier)"
    printf 'artifact_path=%s\n' "${artifact}"
    printf 'artifact_sha256=%s\n' "${artifact_sha}"
    printf 'artifact_bytes=%s\n' "${artifact_bytes}"
    printf 'artifact_created_utc=%s\n' "${artifact_created}"
    printf 'backup_scope=full_database\n'
    printf 'schema_identity=%s\n' "${live_schema}"
    printf 'selected_binding_hash=%s\n' "${live_selected}"
    printf 'connection_generation_hash=%s\n' "${live_connections}"
    printf 'credential_generation_hash=%s\n' "${live_credentials}"
    printf 'assignment_hash=%s\n' "${live_assignments}"
    printf 'binding_count=%s\n' "${binding_count:-absent}"
    printf 'connection_count=%s\n' "${connection_count:-absent}"
    printf 'credential_count=%s\n' "${credential_count:-absent}"
    printf 'assignment_count=%s\n' "${assignment_count:-absent}"
    printf 'scratch_restore_db=%s\n' "${scratch}"
    printf 'scratch_restore_verified=yes\n'
  } | db_write_file "${manifest}"

  BACKUP_MANIFEST="${manifest}"
  log "verified rollback artifact: ${artifact} (${artifact_bytes}B), manifest ${manifest}"
}

backup_manifest_value() {
  printf '%s\n' "$1" | awk -F= -v key="$2" '$1 == key { sub(/^[^=]*=/, ""); print; exit }'
}

# A manifest is only a rollback plan for THIS cutover of THIS database. Stale
# (an earlier epoch), foreign (another database or another system identifier) or
# tampered (a digest that no longer matches what the state record pinned) must
# all refuse.
assert_backup_manifest_bound() {
  local manifest_path text manifest_sha
  manifest_path="$(state_get backup_manifest_path)"
  [ -n "${manifest_path}" ] || die "the state record pins no backup manifest; re-run preflight"
  text="$(db_read_file "${manifest_path}" 2>/dev/null || true)"
  [ -n "${text}" ] || die "the backup manifest ${manifest_path} is gone from the database host; the rollback artifact this cutover was authorised against no longer exists"
  manifest_sha="$(printf '%s' "${text}" | sha256_stdin)"
  [ "${manifest_sha}" = "$(state_get backup_manifest_sha256)" ] \
    || die "the backup manifest changed since preflight (${manifest_sha} vs $(state_get backup_manifest_sha256)); it is not the artifact this cutover was authorised against"
  [ "$(backup_manifest_value "${text}" cutover_epoch)" = "$(state_get cutover_epoch)" ] \
    || die "the backup manifest belongs to cutover epoch $(backup_manifest_value "${text}" cutover_epoch), not $(state_get cutover_epoch); it is stale"
  [ "$(backup_manifest_value "${text}" db_name)" = "${DB_NAME}" ] \
    || die "the backup manifest describes database $(backup_manifest_value "${text}" db_name), not ${DB_NAME}"
  [ "$(backup_manifest_value "${text}" db_system_identifier)" = "$(db_system_identifier)" ] \
    || die "the backup manifest describes system identifier $(backup_manifest_value "${text}" db_system_identifier); this database reports $(db_system_identifier). It is a foreign backup."
  [ "$(backup_manifest_value "${text}" scratch_restore_verified)" = "yes" ] \
    || die "the backup manifest does not record a completed scratch restore"
  # The artifact is checksummed once, when it is taken. Re-checksumming a
  # multi-gigabyte dump at every phase would add minutes to each step, so later
  # phases prove it still exists at exactly the recorded size instead, and say so.
  local artifact bytes
  artifact="$(backup_manifest_value "${text}" artifact_path)"
  bytes="$(db_run "wc -c < $(printf %q "${artifact}")" 2>/dev/null | tr -d '[:space:]' || true)"
  [ -n "${bytes}" ] || die "the rollback artifact ${artifact} is missing from the database host"
  [ "${bytes}" = "$(backup_manifest_value "${text}" artifact_bytes)" ] \
    || die "the rollback artifact is ${bytes}B, the manifest recorded $(backup_manifest_value "${text}" artifact_bytes)B; it was replaced or truncated"
  log "rollback artifact bound: epoch=$(state_get cutover_epoch) ${artifact} (${bytes}B, size re-checked; digest verified at preflight)"
}

# ── The fingerprint host and the runtime must be the same database ─────────
#
# `db_sql` reaches the database through SYNC_CUTOVER_DB_SSH/DB_NAME; the app
# reaches it through DATABASE_URL in .env.production. Nothing proved those were
# the same system. A cutover could fingerprint one database, migrate it, and
# leave the runtime pointed at another.
assert_runtime_database_matches() {
  local runtime_identity control_identity
  control_identity="$(db_identity)"
  [ -n "${control_identity}" ] || die "could not read the control-path database identity"
  runtime_identity="$(
    docker run --rm --network host --env-file "${ENV_FILE}" \
      --entrypoint /bin/sh "${EXPECTED_WEB_IMAGE}" -c '
        node -e "
          const { Client } = require(\"pg\");
          const client = new Client({ connectionString: process.env.DATABASE_URL });
          client.connect()
            .then(() => client.query(\"SELECT current_database() || chr(124) || system_identifier::text AS id FROM pg_control_system()\"))
            .then((r) => { process.stdout.write(r.rows[0].id); return client.end(); })
            .catch((e) => { process.stderr.write(String(e && e.message)); process.exit(1); });
        "' 2>/dev/null | tr -d '[:space:]'
  )"
  [ -n "${runtime_identity}" ] \
    || die "could not read the database identity through the runtime's DATABASE_URL"
  [ "${runtime_identity}" = "${control_identity}" ] \
    || die "the cutover control path (${control_identity}) and the runtime DATABASE_URL (${runtime_identity}) point at DIFFERENT databases"
  log "runtime and control path agree: ${control_identity}"
}

# ── Quiescence, measured on the database ───────────────────────────────────
#
# Counting rows whose `lease_owner` is not null counts leases that expired days
# ago and will never clear, so the old gate could wait forever on nothing while
# a live backend held an open transaction it never looked at. What actually
# matters is whether an application backend is attached to THIS database right
# now, and whether anything holds a transaction open across the migration.
active_app_backends() {
  db_sql "
    SELECT COALESCE(string_agg(
             pid::text || '|' || COALESCE(application_name, '') || '|' || COALESCE(state, '') ||
             '|' || COALESCE(backend_start::text, ''), E'\n' ORDER BY pid), '')
    FROM pg_stat_activity
    WHERE datname = current_database()
      AND pid <> pg_backend_pid()
      AND backend_type = 'client backend'
      AND (
        application_name LIKE '${APP_NAME_PREFIX}%'
        OR state IN ('idle in transaction', 'idle in transaction (aborted)')
      );
  "
}

prepared_transactions() {
  db_sql "SELECT count(*)::text FROM pg_prepared_xacts WHERE database = current_database();" |
    tr -d '[:space:]'
}

assert_database_quiescent() {
  local backends prepared
  backends="$(active_app_backends)"
  if [ -n "$(printf '%s' "${backends}" | tr -d '[:space:]')" ]; then
    printf '%s\n' "${backends}" >&2
    die "quiescence not reached: ${APP_NAME_PREFIX} backends are still attached to ${DB_NAME} (pid|application_name|state|backend_start listed above). Stop them; do not migrate underneath them."
  fi
  prepared="$(prepared_transactions)"
  [ "${prepared}" = "0" ] \
    || die "quiescence not reached: ${prepared} prepared transaction(s) on ${DB_NAME} hold locks that will block every DDL statement in the migration"
  log "database quiescent: no ${APP_NAME_PREFIX} client backends, no prepared transactions"
}

# ── State invariants ───────────────────────────────────────────────────────

env_file_hash() { sha256_file "${ENV_FILE}"; }

assert_state_invariants() {
  local recorded
  [ "$(state_get state_version)" = "${STATE_VERSION}" ] \
    || die "the state record is version '$(state_get state_version)', this wrapper writes version ${STATE_VERSION}; the two do not describe the same cutover. Start from preflight."
  [ "$(state_get deploy_sha)" = "${EXPECTED_SHA}" ] \
    || die "this cutover was opened for $(state_get deploy_sha); DEPLOY_SHA is now ${EXPECTED_SHA}. One state directory cannot hold two releases."
  assert_image_pin
  recorded="$(db_identity)"
  [ "${recorded}" = "$(state_get db_identity)" ] \
    || die "the database identity is now ${recorded}, the cutover was opened against $(state_get db_identity); the control path was repointed mid-cutover"
  recorded="$(env_file_hash)"
  [ "${recorded}" = "$(state_get env_file_sha256)" ] \
    || die "${ENV_FILE} changed outside this cutover (${recorded} vs $(state_get env_file_sha256)). Reconcile by hand; the recreate would deploy an unreviewed configuration."
  [ "${SCHEDULER}" = "$(state_get scheduler_spec)" ] \
    || die "the scheduler is now '${SCHEDULER}', the cutover was opened against '$(state_get scheduler_spec)'"
  recorded="$(scheduler_hash "${SCHEDULER}")"
  [ "${recorded}" = "$(state_get scheduler_sha256)" ] \
    || die "the scheduler definition changed mid-cutover (${recorded} vs $(state_get scheduler_sha256)); resuming would restore something other than what was stopped"
  assert_backup_manifest_bound
}

# ── Enable-time rollback ───────────────────────────────────────────────────

DISABLED_ENV_BACKUP=""

rollback_enable() {
  local reason="$1"
  log "ROLLING BACK the enable: ${reason}"
  if [ -n "${DISABLED_ENV_BACKUP}" ] && [ -s "${DISABLED_ENV_BACKUP}" ]; then
    # Same-filesystem rename, so a reader sees the whole disabled file or the
    # whole enabled one. It does not un-recreate a container that already read
    # the enabled file — that is what stopping the runtime below is for.
    cp "${DISABLED_ENV_BACKUP}" "${ENV_FILE}.rollback.$$"
    mv "${ENV_FILE}.rollback.$$" "${ENV_FILE}"
    log "restored the disabled env file from ${DISABLED_ENV_BACKUP}"
  fi
  docker compose stop autoheal >/dev/null 2>&1 || true
  docker compose stop web worker >/dev/null 2>&1 || true
  scheduler_stop "${SCHEDULER}" >/dev/null 2>&1 || true
  state_chain_drop deploy-disabled enable resume-scheduler
  state_set invalidated yes
  state_set invalidated_after enable
  state_set invalidated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  state_set last_failure "enable: ${reason}"
  state_set env_file_sha256 "$(env_file_hash)"

  # Record what the rollback actually restored, in the release record, so the
  # next operator reads the truth rather than a record still claiming the
  # release is live. The PREVIOUS identity was captured at preflight, before
  # anything was swapped, which is the only moment it was still observable.
  release_set phase "rolled-back:enable"
  release_set rollback_reason "${reason}"
  release_set rollback_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  release_set restored_env_sha256 "$(env_file_hash)"
  release_set restored_env_matches_preflight \
    "$([ "$(env_file_hash)" = "$(release_get prev_env_sha256)" ] && echo yes || echo NO)"
  release_set restore_target_web_image_id "$(release_get prev_web_image_id)"
  release_set restore_target_worker_image_id "$(release_get prev_worker_image_id)"
  release_set restore_target_web_image_ref "$(release_get prev_web_image_ref)"
  release_set restore_target_worker_image_ref "$(release_get prev_worker_image_ref)"
  release_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
  log "release record marked rolled-back; restore target web=$(release_get prev_web_image_ref) worker=$(release_get prev_worker_image_ref)"
  log "runtime stopped, scheduler stopped, state invalidated. Re-run deploy-disabled to retry cleanly."
  die "enable failed and was rolled back: ${reason}"
}

# Every lane key the env file currently declares enabled. Both containers must
# agree with this list — the master switch alone says nothing about the lanes.
enabled_lane_keys() {
  grep -Eo '^[[:space:]]*(export[[:space:]]+)?ADSECUTE_SYNC_[A-Z0-9_]+_ENABLED[[:space:]]*=[[:space:]]*enabled' "${ENV_FILE}" 2>/dev/null |
    sed -E 's/^[[:space:]]*(export[[:space:]]+)?//; s/[[:space:]]*=.*$//' |
    sort -u
}

cd "${APP_DIR}"

exec 9>"${LOCK_FILE}"
flock -n 9 || die "another cutover is in progress (${LOCK_FILE})"

# Before ANY phase, including `status`: this file must be the released wrapper.
assert_wrapper_integrity

SCHEDULER="$(resolve_scheduler)"

case "${PHASE}" in
  status)
    printf 'state record: %s\n' "${STATE_FILE}"
    cat "${STATE_FILE}"
    printf 'scheduler=%s state=%s hash=%s\n' "${SCHEDULER}" "$(scheduler_state "${SCHEDULER}")" "$(scheduler_hash "${SCHEDULER}")"
    for service in web worker autoheal; do
      printf '%s=%s\n' "${service}" "$(container_state "${service}")"
    done
    ;;

  preflight)
    # OLD-SCHEMA SAFE. Nothing here may depend on the migration having run —
    # that was the phase-graph deadlock: preflight required post-migration
    # objects, and migrate required preflight.
    require_sha
    log "Verifying the exact images for ${EXPECTED_SHA} are present"
    docker image inspect "${EXPECTED_WEB_IMAGE}" >/dev/null \
      || die "missing image ${EXPECTED_WEB_IMAGE}; pull it first"
    docker image inspect "${EXPECTED_WORKER_IMAGE}" >/dev/null \
      || die "missing image ${EXPECTED_WORKER_IMAGE}; pull it first"

    log "Verifying the env file the runtime actually sources"
    [ -f "${ENV_FILE}" ] || die "missing ${ENV_FILE}"
    grep -q "\.env\.production" "${APP_DIR}/docker-compose.yml" \
      || die "docker-compose.yml does not reference .env.production; the target is wrong"

    log "Resolving the external scheduler"
    [ "${SCHEDULER}" != "unresolved" ] \
      || die "could not determine how the external scheduler runs. Set SYNC_CUTOVER_SCHEDULER to systemd:<unit>, cron:<file>, rootcron, compose:<service>, or none."
    if [ "${SCHEDULER}" = "none" ]; then
      assert_no_scheduler_exists
    fi
    log "scheduler=${SCHEDULER} state=$(scheduler_state "${SCHEDULER}")"

    log "Reaching the database host"
    identity="$(db_identity)"
    [ -n "${identity}" ] || die "could not read database identity from the DB host"
    log "database=${identity}"

    log "Proving the runtime's DATABASE_URL is the SAME database"
    assert_runtime_database_matches

    log "Proving there is room to migrate"
    assert_capacity_for_migration

    # A new epoch opens a new cutover. Everything below is bound to it, and every
    # later phase refuses anything carrying a different one.
    epoch="${EXPECTED_SHA:0:12}-$(date -u +%Y%m%dT%H%M%SZ)"

    log "Taking and verifying the rollback artifact for epoch ${epoch}"
    take_verified_backup "${epoch}"
    manifest_text="$(db_read_file "${BACKUP_MANIFEST}")"
    manifest_sha="$(printf '%s' "${manifest_text}" | sha256_stdin)"

    log "Pinning image digests"
    web_digest="$(docker image inspect "${EXPECTED_WEB_IMAGE}" --format '{{.Id}}')"
    worker_digest="$(docker image inspect "${EXPECTED_WORKER_IMAGE}" --format '{{.Id}}')"
    [ -n "${web_digest}" ] && [ -n "${worker_digest}" ] \
      || die "could not resolve immutable image ids for ${EXPECTED_SHA}"
    printf '%s %s\n' "${web_digest}" "${worker_digest}" > "${IMAGE_PIN_FILE}"
    log "web=${web_digest} worker=${worker_digest}"

    # The record is rewritten from scratch: a preflight opens a cutover, and
    # carrying a previous run's phase chain forward is exactly how a stale proof
    # survives into a release it was never taken for.
    : > "${STATE_FILE}"
    chmod 0600 "${STATE_FILE}"
    state_set state_version "${STATE_VERSION}"
    state_set cutover_epoch "${epoch}"
    state_set deploy_sha "${EXPECTED_SHA}"
    state_set web_image_digest "${web_digest}"
    state_set worker_image_digest "${worker_digest}"
    state_set db_identity "${identity}"
    state_set env_file_sha256 "$(env_file_hash)"
    state_set scheduler_spec "${SCHEDULER}"
    state_set scheduler_sha256 "$(scheduler_hash "${SCHEDULER}")"
    state_set backup_manifest_path "${BACKUP_MANIFEST}"
    state_set backup_manifest_sha256 "${manifest_sha}"
    state_set wrapper_sha256 "$(sha256_file "${BASH_SOURCE[0]}")"
    state_set phase_chain ""

    # The dedicated release identity record. Written fresh for this cutover,
    # atomically, root-owned. It is what every later phase checks itself against
    # — and what a rollback needs in order to restore the EXACT previous thing
    # rather than "whatever was there".
    rm -f "${RELEASE_RECORD}"
    release_identity_now | while IFS= read -r line; do
      release_set "${line%%=*}" "${line#*=}"
    done
    release_set backup_manifest_id "${manifest_sha}"
    release_set backup_manifest_path "${BACKUP_MANIFEST}"
    release_set build_timestamp_utc "$(docker image inspect "${EXPECTED_WEB_IMAGE}" --format '{{.Created}}' 2>/dev/null || echo unknown)"
    release_set cutover_epoch "${epoch}"
    release_set db_identity "${identity}"
    # What a rollback must put back. Captured BEFORE anything is swapped.
    release_set prev_web_image_id "$(docker inspect "$(docker compose ps -q web 2>/dev/null | head -1)" --format '{{.Image}}' 2>/dev/null || echo none)"
    release_set prev_worker_image_id "$(docker inspect "$(docker compose ps -q worker 2>/dev/null | head -1)" --format '{{.Image}}' 2>/dev/null || echo none)"
    release_set prev_web_image_ref "$(docker inspect "$(docker compose ps -q web 2>/dev/null | head -1)" --format '{{.Config.Image}}' 2>/dev/null || echo none)"
    release_set prev_worker_image_ref "$(docker inspect "$(docker compose ps -q worker 2>/dev/null | head -1)" --format '{{.Config.Image}}' 2>/dev/null || echo none)"
    release_set prev_env_sha256 "$(env_file_hash)"
    release_set prev_scheduler_sha256 "$(scheduler_hash "${SCHEDULER}")"
    release_set phase "preflight"
    release_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    assert_recovery_policy
    release_set policy_sha256_delivered "$(sha256_file "${RECOVERY_POLICY_FILE}")"
    assert_release_record "record its own preflight"
    log "release identity recorded at ${RELEASE_RECORD} for ${EXPECTED_SHA}"
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    state_chain_add preflight
    log "preflight OK epoch=${epoch}"
    ;;

  quiesce)
    require_sha
    require_phase preflight
    assert_state_invariants
    log "Stopping the external scheduler (${SCHEDULER}) BEFORE anything else"
    scheduler_stop "${SCHEDULER}"
    observed="$(scheduler_state "${SCHEDULER}")"
    [ "${observed}" = "stopped" ] \
      || die "scheduler is still '${observed}'; an external trigger would restart work mid-migration"

    # autoheal FIRST: it restarts unhealthy containers, so stopping the worker
    # while autoheal runs is how a "stopped" worker comes back by itself.
    log "Stopping autoheal, then web, then worker"
    docker compose stop autoheal || true
    assert_stopped autoheal
    docker compose stop web worker || true
    assert_stopped web
    assert_stopped worker

    log "Draining for ${DRAIN_SECONDS}s and proving nothing is mid-flight"
    sleep "${DRAIN_SECONDS}"
    assert_stopped web
    assert_stopped worker
    assert_stopped autoheal
    [ "$(scheduler_state "${SCHEDULER}")" = "stopped" ] \
      || die "the scheduler restarted during the drain window"

    assert_database_quiescent

    state_chain_add quiesce
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "quiesce OK"
    ;;

  fingerprint-pre)
    require_sha
    require_phase quiesce
    assert_state_invariants
    fingerprint_of "${DB_NAME}" > "${STATE_DIR}/fingerprint-pre"
    chmod 0600 "${STATE_DIR}/fingerprint-pre"
    cat "${STATE_DIR}/fingerprint-pre"
    state_set fingerprint_pre_sha256 "$(sha256_file "${STATE_DIR}/fingerprint-pre")"
    state_chain_add fingerprint-pre
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "fingerprint-pre OK"
    ;;

  migrate)
    require_sha
    require_phase fingerprint-pre
    assert_state_invariants
    log "Re-proving capacity immediately before the disk-consuming step"
    assert_capacity_for_migration
    log "Re-proving quiescence immediately before the migration acquires locks"
    assert_database_quiescent
    log "Running migrations from the pinned image against the DB host"
    APP_IMAGE_TAG="${EXPECTED_SHA}" APP_BUILD_ID="${EXPECTED_SHA}" \
      docker compose up --no-deps --abort-on-container-exit --exit-code-from migrate migrate \
      || die "migrations failed; completion was not announced and nothing was enabled"
    docker compose rm -f migrate >/dev/null 2>&1 || true
    state_chain_add migrate
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "migrate OK"
    ;;

  verify-contract)
    # POST-migration. This is what preflight used to run, which is why the graph
    # could never reach migration.
    require_sha
    require_phase migrate
    assert_state_invariants
    log "Verifying the post-migration schema contract from the pinned image"
    run_in_pinned_image node --import tsx scripts/global-sync-rollout.ts preflight \
      || die "the post-migration contract refused; do not continue"
    state_chain_add verify-contract
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "verify-contract OK"
    ;;

  fingerprint-post)
    require_sha
    require_phase verify-contract
    assert_state_invariants
    fingerprint_of "${DB_NAME}" > "${STATE_DIR}/fingerprint-post"
    chmod 0600 "${STATE_DIR}/fingerprint-post"
    [ "$(sha256_file "${STATE_DIR}/fingerprint-pre")" = "$(state_get fingerprint_pre_sha256)" ] \
      || die "the pre-migration fingerprint file changed since it was taken; it cannot be compared against"
    # The migration is expand-only. Identity, schema-identity aside, every count
    # and every identity/generation hash must be byte-identical. `schema_identity`
    # is expected to move — that is what the migration does — so it is compared
    # separately rather than silently ignored.
    if ! diff -u \
      <(grep -v '^schema_identity=' "${STATE_DIR}/fingerprint-pre") \
      <(grep -v '^schema_identity=' "${STATE_DIR}/fingerprint-post"); then
      die "the migration changed identity, row counts or an identity/generation hash. Do not enable. Restore from ${BACKUP_MANIFEST:-$(state_get backup_manifest_path)}."
    fi
    pre_schema="$(awk -F= '$1=="schema_identity"{print $2}' "${STATE_DIR}/fingerprint-pre")"
    post_schema="$(awk -F= '$1=="schema_identity"{print $2}' "${STATE_DIR}/fingerprint-post")"
    [ "${pre_schema}" != "${post_schema}" ] \
      || die "the schema identity is unchanged (${post_schema}); the migration this cutover exists to apply did not change the schema"
    log "schema identity moved ${pre_schema} -> ${post_schema}, everything else identical"
    state_set schema_identity_post "${post_schema}"
    state_chain_add fingerprint-post
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "fingerprint-post OK — data identical, schema advanced"
    ;;

  deploy-disabled)
    require_sha
    state_chain_has fingerprint-post \
      || die "phase 'fingerprint-post' has not completed in this cutover (chain='$(state_chain)'); run it first"
    assert_state_invariants
    log "Confirming every lane is OFF before the new build starts"
    if grep -Eq '^[[:space:]]*(export[[:space:]]+)?ADSECUTE_SYNC_[A-Z0-9_]+_ENABLED[[:space:]]*=[[:space:]]*enabled' "${ENV_FILE}"; then
      die "a sync lane is already enabled in ${ENV_FILE}; the new build must start disabled"
    fi

    # Nothing is swapped until the release record, the source sha, the pushed
    # branch sha, the image ids and their revision labels, and the wrapper /
    # manifest / policy pins all agree.
    assert_release_record "swap the running containers"
    release_set phase "deploy-disabled:swapping"
    release_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    log "Starting web and worker on ${EXPECTED_SHA}, lanes off"
    APP_IMAGE_TAG="${EXPECTED_SHA}" APP_BUILD_ID="${EXPECTED_SHA}" \
      docker compose up -d --force-recreate web worker

    for service in web worker; do
      expected="ghcr.io/erhanrdn/omniads-${service}:${EXPECTED_SHA}"
      actual="$(docker inspect "$(docker compose ps -q "${service}")" --format '{{.Config.Image}}')"
      [ "${actual}" = "${expected}" ] || die "${service} is running ${actual}, expected ${expected}"
      log "${service} image=${actual}"
    done

    log "Checking /healthz and /build-info"
    curl -fsS http://127.0.0.1:3000/api/healthz >/dev/null || die "/healthz did not answer"
    build_id="$(curl -fsS http://127.0.0.1:3000/api/build-info | python3 -c 'import json,sys; print(json.load(sys.stdin).get("buildId") or "")')"
    [ "${build_id}" = "${EXPECTED_SHA}" ] || die "build-info reports '${build_id}', expected ${EXPECTED_SHA}"

    # Effective CONTAINER environment, not the file. Key names and a yes/no
    # only — never a value.
    for service in web worker; do
      id="$(docker compose ps -q "${service}")"
      for key in ADSECUTE_SYNC_GLOBAL_ENABLED DATABASE_URL; do
        if docker exec "${id}" sh -c "test -n \"\${${key}:-}\""; then present=yes; else present=no; fi
        log "${service} env ${key} present=${present}"
        if [ "${key}" = "ADSECUTE_SYNC_GLOBAL_ENABLED" ] && [ "${present}" = "yes" ]; then
          die "${service} started with the master switch set; it must start disabled"
        fi
        if [ "${key}" = "DATABASE_URL" ] && [ "${present}" = "no" ]; then
          die "${service} has no DATABASE_URL; the env file was not sourced"
        fi
      done
    done

    log "Proving the worker registered fresh and no old process is still heartbeating"
    worker_started_at="$(docker inspect "$(docker compose ps -q worker)" --format '{{.State.StartedAt}}')"
    docker compose exec -T worker node --import tsx scripts/sync-worker-healthcheck.ts \
      --provider-scope meta --online-window-minutes 5 --min-online-workers 1 \
      --min-heartbeat-after "${worker_started_at}" \
      || die "no fresh worker heartbeat after start; an old process may still hold work"

    # Re-establishing the runtime proof is what clears an earlier invalidation,
    # so an emergency stop can be recovered from without hand-editing state.
    # What is RUNNING must be the release. Starting successfully is not the same
    # as running the right image: a stale tag, a cached layer or a compose file
    # pointing elsewhere all start cleanly and all deploy the wrong thing.
    assert_running_image_identity
    release_set phase "deploy-disabled"
    release_set running_web_image_id "$(docker inspect "$(docker compose ps -q web)" --format '{{.Image}}')"
    release_set running_worker_image_id "$(docker inspect "$(docker compose ps -q worker)" --format '{{.Image}}')"
    release_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"

    state_set invalidated no
    state_set last_failure ""
    state_chain_add deploy-disabled
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "deploy-disabled OK"
    ;;

  enable)
    require_sha
    require_phase deploy-disabled
    assert_state_invariants
    # Re-checked here, not merely inherited from deploy-disabled: a container can
    # be recreated, an image retagged or a compose file edited between the two
    # phases, and enabling lanes is the irreversible half.
    assert_release_record "enable the sync lanes"
    assert_running_image_identity

    DISABLED_ENV_BACKUP="${STATE_DIR}/env.disabled.$(state_get cutover_epoch)"
    cp "${ENV_FILE}" "${DISABLED_ENV_BACKUP}"
    chmod 0600 "${DISABLED_ENV_BACKUP}"
    log "disabled env preserved at ${DISABLED_ENV_BACKUP} (this is the rollback target)"

    log "Updating ONLY the managed lane keys in the preserved env file"
    run_in_pinned_image node --import tsx scripts/global-sync-rollout.ts enable \
      || rollback_enable "the rollout script refused"

    # Prove the rollout touched nothing else. It runs in a container with the
    # whole env file bind-mounted, so "it only writes lane keys" is a claim about
    # code that is easier to verify here than to trust.
    changed="$(diff "${DISABLED_ENV_BACKUP}" "${ENV_FILE}" 2>/dev/null |
      grep -E '^[<>]' | sed -E 's/^[<>][[:space:]]*(export[[:space:]]+)?//; s/[[:space:]]*=.*$//' | sort -u || true)"
    for key in ${changed}; do
      printf '%s' "${key}" | grep -Eq "${MANAGED_ENV_KEY_PATTERN}" \
        || rollback_enable "the rollout changed unmanaged env key '${key}'"
    done
    lanes="$(enabled_lane_keys)"
    [ -n "${lanes}" ] || rollback_enable "no lane is enabled in the env file after the rollout ran"
    log "managed keys changed: $(printf '%s' "${changed}" | tr '\n' ' ')"

    # The file changed. The RUNTIME has not: both processes read their
    # environment at container creation. This recreate is the runtime change,
    # and it is sequential — for the length of the recreate one container runs
    # the new configuration and the other the old.
    log "Recreating web and worker from that same configuration"
    APP_IMAGE_TAG="${EXPECTED_SHA}" APP_BUILD_ID="${EXPECTED_SHA}" \
      docker compose up -d --force-recreate web worker \
      || rollback_enable "docker compose could not recreate both containers"

    curl -fsS http://127.0.0.1:3000/api/healthz >/dev/null \
      || rollback_enable "/healthz did not answer after recreate"
    build_id="$(curl -fsS http://127.0.0.1:3000/api/build-info | python3 -c 'import json,sys; print(json.load(sys.stdin).get("buildId") or "")' || true)"
    [ "${build_id}" = "${EXPECTED_SHA}" ] \
      || rollback_enable "build-info reports '${build_id}' after recreate, expected ${EXPECTED_SHA}"

    for service in web worker; do
      id="$(docker compose ps -q "${service}" || true)"
      [ -n "${id}" ] || rollback_enable "${service} has no container after the recreate"
      [ "$(docker inspect "${id}" --format '{{.State.Status}}')" = "running" ] \
        || rollback_enable "${service} is not running after the recreate"
      actual="$(docker inspect "${id}" --format '{{.Config.Image}}')"
      [ "${actual}" = "ghcr.io/erhanrdn/omniads-${service}:${EXPECTED_SHA}" ] \
        || rollback_enable "${service} came back on ${actual}, not the pinned build"
      for lane in ${lanes}; do
        docker exec "${id}" sh -c "test \"\${${lane}:-}\" = enabled" \
          || rollback_enable "${service} did not pick up ${lane}; the recreate did not take effect"
      done
      docker exec "${id}" sh -c 'test -z "${ADSECUTE_SYNC_LANE_RETENTION_ENABLED:-}"' \
        || rollback_enable "${service} has retention enabled; retention must stay off"
      log "${service} carries $(printf '%s' "${lanes}" | tr '\n' ' ')and retention is off"
    done

    worker_started_at="$(docker inspect "$(docker compose ps -q worker)" --format '{{.State.StartedAt}}')"
    for scope in meta google_ads shopify; do
      docker compose exec -T worker node --import tsx scripts/sync-worker-healthcheck.ts \
        --provider-scope "${scope}" --online-window-minutes 5 --min-online-workers 1 \
        --min-heartbeat-after "${worker_started_at}" \
        || rollback_enable "no fresh ${scope} worker registration after the recreate"
      log "${scope} worker registered after ${worker_started_at}"
    done

    # An old worker that survived the recreate would keep leasing partitions
    # against the new schema. A backend older than the new container cannot
    # belong to it.
    stale="$(db_sql "
      SELECT COALESCE(string_agg(pid::text || '|' || COALESCE(application_name, ''), ','), '')
      FROM pg_stat_activity
      WHERE datname = current_database()
        AND backend_type = 'client backend'
        AND application_name LIKE '${APP_NAME_PREFIX}%'
        AND backend_start < timestamptz '${worker_started_at}';
    " | tr -d '[:space:]')"
    [ -z "${stale}" ] \
      || rollback_enable "processes older than the recreate are still attached to the database: ${stale}"
    log "no pre-recreate application backend survives"

    docker compose up -d autoheal
    state_set env_file_sha256 "$(env_file_hash)"
    state_set enabled_lanes "$(printf '%s' "${lanes}" | tr '\n' ',')"
    state_chain_add enable
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "enable OK — the external scheduler is still stopped"
    ;;

  resume-scheduler)
    require_sha
    require_phase enable
    assert_state_invariants
    log "Both processes are proven; restarting the scheduler (${SCHEDULER}) last"
    scheduler_start "${SCHEDULER}"
    observed="$(scheduler_state "${SCHEDULER}")"
    [ "${observed}" = "running" ] || die "scheduler is '${observed}' after start"
    state_set scheduler_sha256 "$(scheduler_hash "${SCHEDULER}")"
    state_chain_add resume-scheduler
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "resume-scheduler OK"
    ;;

  emergency-disable)
    # Always available: no DEPLOY_SHA, no database, no completed phase required.
    # Reports success only after LIVE state is confirmed stopped — "the command
    # returned 0" is not the same as "nothing is running".
    log "EMERGENCY: stopping scheduler (${SCHEDULER}), autoheal, web, worker"
    scheduler_stop "${SCHEDULER}" || true
    docker compose stop autoheal || true
    docker compose stop web worker || true
    failed=0
    for service in autoheal web worker; do
      observed="$(container_state "${service}")"
      log "${service}=${observed}"
      case "${observed}" in
        absent | exited | created) ;;
        *) failed=1 ;;
      esac
    done
    scheduler_observed="$(scheduler_state "${SCHEDULER}")"
    log "scheduler=${SCHEDULER} state=${scheduler_observed}"
    [ "${scheduler_observed}" = "stopped" ] || failed=1
    [ "${failed}" = "0" ] || die "emergency disable did NOT fully take effect; intervene by hand"

    # Everything that was proven about the RUNTIME is now false: the containers
    # that carried the proof are stopped. Leaving `enable` in the chain would let
    # `resume-scheduler` restart the external trigger against a runtime nobody
    # has re-verified, which is the worst possible order of operations.
    state_chain_drop deploy-disabled enable resume-scheduler
    state_set invalidated yes
    state_set invalidated_after "emergency-disable"
    state_set invalidated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    state_set updated_utc "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    log "emergency-disable CONFIRMED stopped; enable/resume proofs INVALIDATED (chain='$(state_chain)')"
    ;;

  *)
    die "unknown phase '${PHASE}'"
    ;;
esac
