#!/usr/bin/env bash
# The canonical database-seams sequence. ONE list, run by CI and by humans.
#
# WHY THIS EXISTS. The CI job used to spell out ~20 steps inline, and the local
# habit was to run "the ones that seemed relevant". Those two lists drifted, and
# the drift was invisible until a push failed: a guard ran green locally, was
# never re-run on the final tree, and CI executed a slightly different set in a
# different order. A verification you cannot reproduce exactly is not a
# verification, so `.github/workflows/ci.yml` now invokes this file and so does
# `npm run verify:pre-push`. There is nothing left to keep in sync.
#
# ORDER IS PART OF THE CONTRACT. The release-owner guard runs LAST, after every
# other check has had its chance to modify the tree (the wrapper manifest in
# particular is regenerated by a step below). Running it first — as CI did —
# checks a tree that no longer exists by the time the job ends.
set -euo pipefail

cd "$(dirname "$0")/.."

LABEL="[verify-db-seams]"
STAGE=0

stage() {
  STAGE=$((STAGE + 1))
  printf '\n%s ── %02d %s\n' "${LABEL}" "${STAGE}" "$1"
}

# FIRST, and cheap. A semantically invalid workflow is rejected by GitHub before
# any job is created — the run completes as failure with jobs: [], no check runs
# and no logs — so CI structurally cannot catch it. Only a local check can.
stage "Workflow semantics (undefined needs, cycles, malformed steps)"
npm run check:workflows

# Also the home of the null-versus-zero storage seams, because they are claims
# about the SCHEMA and only a freshly migrated cluster can settle them.
# `scripts/ephemeral-postgres-migrations-check.ts` runs
# `ephemeral-postgres-creative-null-presence-seam-child.ts` as a child against
# that cluster, and that child carries `link_clicks` on BOTH fact tables:
# `meta_ad_daily` (the groupBy="ad" branch) and `meta_creative_daily` (the
# DEFAULT Assets grain, and the table the engine's creative-grain aggregates
# read). For each: that the widening accepts NULL while rewriting no stored row
# — `pg_relation_filenode` is compared across it, so "catalog-only, no table
# rewrite" is measured rather than asserted — that it creates no NULLs of its
# own and re-runs cleanly, that the writer binds an unsupplied count as NULL and
# a supplied 0 as 0, that folding two unsupplied ad-rows into one creative-day
# stays unsupplied instead of manufacturing a measured zero, that a re-sync
# supplying nothing no longer overwrites a stored measurement with a fabricated
# zero (the old three-argument COALESCE could never reach its "keep what is
# stored" arm), and that the presence sidecar then publishes
# `link_clicks: false` — with CTR, CPC (link) and click-to-ATC going with it —
# for exactly the rows the database could not supply.
#
# The child ALSO carries the engine-equivalence half, which is the claim the
# whole change rests on: the engine's numbers must not move when a stored 0
# becomes an unsupplied NULL. `runCalibrationJob` is run twice over the same 50
# seeded creative-days with only that column flipped, and all 25 persisted
# calibration rows are compared including every link-click-denominated funnel
# percentile; then `runLifecycleJob` is asserted to still store
# `link_clicks_28d = 0` for an all-unsupplied creative rather than NULL. That
# last one is the load-bearing assertion for the `SUM(COALESCE(link_clicks, 0))`
# aggregates — reverting the coalesce makes it fail with "expected 0, got null",
# whereas the calibration comparison alone does NOT catch it, because every
# funnel rate there is guarded by `CASE WHEN total_link_clicks > 0` and that
# guard treats NULL and 0 alike.
#
# Deliberately NOT a separate stage: a second stage would boot a second cluster
# to re-prove the same migrated schema.
stage "Migrations from zero (incl. null-vs-zero storage seams: link_clicks, funnel keys, frequency)"
npm run test:migrations-from-zero

stage "Disaster-recovery backup and restore seam"
npm run test:dr-restore-seam

stage "Staged idle worker seam (real worker, real PostgreSQL)"
npm run test:staged-worker

stage "Native ad decision database seam"
node --import tsx scripts/ephemeral-postgres-native-ad-decision-seam.ts

# PRE-DEPLOY AUDIT: the D088 budget seam was written and never wired, so the
# canonical sequence never ran it. It boots its own cluster, applies the REAL
# migration registry, and proves the complete D088 postcondition — the 26-column
# journal contract with its types, nullability and safety defaults, both journal
# indexes, every constraint resolved to its exact schema and table, and the
# rollback-compatibility upsert BOTH application images must be able to issue.
stage "D088 budget proposal migration seam (schema contract + rollback compatibility)"
npm run test:d088-budget-migration-seam

# The operator readback an actual deploy depends on, executed in BOTH schema
# states: the schema production has today, and the schema after this release.
# A statement that merely NAMES a table this release creates aborts the whole
# transaction at parse time on the pre-deploy run, so "it should work" is not
# good enough and the file is executed rather than reviewed.
stage "Automation-OFF readback (pre-migration and post-migration, via psql)"
npm run test:automation-off-readback-seam

stage "Provider fixture seam"
npm run test:provider-fixture-seam

stage "Sync retention, growth and release seam"
npm run test:sync-retention-seam

stage "Release-gate plan and coalescing seam"
npm run test:release-gate-plan-seam

stage "Legacy import replay seam"
npm run test:legacy-replay-seam

stage "Google Ads date freshness seam (F1-F19)"
npm run test:google-ads-finality-seam

stage "Cutover wrapper package is current"
bash -n scripts/hetzner-sync-cutover.sh
bash -n scripts/cutover-wrapper-package.sh
bash -n scripts/cutover-real-postgres-harness.sh
bash -n scripts/cutover-wrapper-build-context-check.sh
bash -n scripts/check-release-owner-references.sh
bash -n scripts/verify-database-seams.sh
npm run test:cutover-wrapper-package

# A STATIC assertion that the wrapper is inside the Docker build context and
# captured by an existing COPY. NOT a container smoke test: no image is built.
stage "Cutover wrapper build-context assertion (static, not a smoke test)"
npm run test:cutover-build-context

# Every phase plus the negative controls against a REAL ephemeral PostgreSQL and
# a split app-host/DB-host command surface.
stage "Cutover state-machine harness (real PostgreSQL)"
npm run test:cutover-harness

# Admission over the REAL exported entrypoints, not a source scan.
stage "Entrypoint admission refusal seam"
npx vitest run lib/sync/entrypoint-admission.test.ts

stage "Entrypoint admission real-database seam"
npm run test:entrypoint-admission-seam

stage "Provider selection race seam"
npm run test:selection-race-seam

# The Automation confirmation queue is the ONE surface where an operator click
# becomes a provider write, and every guarantee it makes is a database
# guarantee: the claim's compare-and-set, the unique open-slot index that also
# covers `reconcile`, the append-only reconciliation receipt, and the migration
# that builds all three out of statements which individually swallow their
# errors. `package.json` has defined this script since the claim landed and
# NOTHING ran it — not this file, not any workflow — so a regression in any of
# them would have shipped green. It runs here, in the canonical sequence CI
# invokes, which is what makes it a release gate rather than a script.
stage "Automation execution claim, reconcile slot and settle fault injection"
npm run test:automation-claim-race-seam

# The Decisions/Copies -> Launchpad handoff. Single use is one conditional
# UPDATE, account scoping is a WHERE clause, and the origin-integrity check
# defends against an edited `payload_json` — none of which a mocked `sql` can
# show. The vitest file behind this used to gate on a hand-set
# META_HANDOFF_TEST_DATABASE_URL and therefore SKIPPED in every acceptance run,
# which reads exactly like a pass. This stage is what makes it run; the script
# also asserts its own negative control (the file must still skip without the
# harness, so nobody can "fix" a failure by deleting the gate).
stage "Launchpad handoff mint/consume/single-use seam (real PostgreSQL)"
npm run test:launchpad-handoff-seam

# Meta breakdown ingestion. `age,gender` is TWO dimensions that were stored
# under one `age` identity, and `reach` was a NOT NULL column the fetch never
# asked Meta to fill — so an unmeasured reach was written as a measured zero.
# Both fixes are database facts a mocked `sql` cannot show: whether two
# dimensions survive one account-day's unique key, whether replacing one slice
# deletes the other, whether the widened column accepts NULL, and whether the
# dirty-day coverage gate still demands exactly three types (a `gender` row must
# not mask a missing `country`). The harness also rejects a run whose tests
# SKIPPED, because a skipped database test reads exactly like a pass.
stage "Meta breakdown dimension split and unmeasured reach"
npm run test:breakdown-dimension-seam

# Six cross-tenant isolation assertions that were wired to NOTHING: the
# vitest file gates on ADSECUTE_EPHEMERAL_DB_SEAM=1, no npm script invoked
# the harness, and no stage ran it — so every acceptance run reported them
# as a pass while proving nothing. A deselected account's journal, currency
# and name being served to anyone who asks by id, or a cross-business
# widening, would have shipped green.
stage "Meta History account-assignment isolation seam (real PostgreSQL)"
npm run test:meta-history-assignment-seam

stage "Shopify install context seam"
npm run test:shopify-install-seam

stage "Shopify grant race seam"
npm run test:shopify-grant-race-seam

stage "Shopify install-context read authority seam"
npm run test:shopify-context-access-seam

# Fail-closed proof for the ORDINARY deploy path: a release carrying
# deploy/CUTOVER_REQUIRED must not be migratable outside the cutover lock.
stage "Ordinary deploy refuses a cutover-required release"
bash -n .github/scripts/hetzner-remote.sh
# The marker is present only while a cutover is PENDING; the commit after a
# completed cutover removes it. What must always hold is that the marker and the
# delivered manifest AGREE.
if [ -f deploy/CUTOVER_REQUIRED ]; then
  echo "cutover pending: deploy/CUTOVER_REQUIRED present"
  grep -q '^cutover_required=yes$' scripts/cutover-wrapper.manifest || {
    echo "deploy/CUTOVER_REQUIRED exists but the manifest does not say cutover_required=yes" >&2
    exit 1
  }
else
  echo "no cutover pending: deploy/CUTOVER_REQUIRED absent"
  grep -q '^cutover_required=no$' scripts/cutover-wrapper.manifest || {
    echo "deploy/CUTOVER_REQUIRED is absent but the manifest still says cutover_required=yes; run npm run cutover:package" >&2
    exit 1
  }
fi
grep -q 'deploy/CUTOVER_REQUIRED' .github/scripts/hetzner-remote.sh
# The grep proves the string is present; it cannot prove the ORDER, which is
# what matters. This also carries R1-R3, the production release boundary.
npm run test:deploy-gate-ordering
# The runbook must name the path that exists ON THE HOST.
installed=/var/www/adsecute/cutover/hetzner-sync-cutover.sh
grep -q "${installed}" docs/global-sync-rollout-runbook.md || {
  echo "the runbook does not name the installed wrapper path ${installed}" >&2
  exit 1
}
if [ -f deploy/CUTOVER_REQUIRED ]; then
  grep -q "${installed}" deploy/CUTOVER_REQUIRED || {
    echo "deploy/CUTOVER_REQUIRED does not name ${installed}" >&2
    exit 1
  }
fi
! grep -qE '^\s*(\./)?(\.github/)?scripts/hetzner-sync-cutover\.sh' docs/global-sync-rollout-runbook.md || {
  echo "the runbook still instructs running the repository copy of the wrapper" >&2
  exit 1
}

# The deploy carries a registry credential to a long-lived host. Executed, not
# asserted: token never in argv or the phase environment, ephemeral
# DOCKER_CONFIG cleaned on every exit path, failed login aborts before the
# phase runs, and the anonymous legacy-rollback path still works.
stage "Deploy registry auth (ephemeral credential handling)"
npm run test:deploy-registry-auth

# The recovery out of a half-finished cutover must refuse every state shape but
# one. Executed against synthetic state: wrong/reordered/already-resumed chain,
# invalidated, foreign release, wrong wrapper version, in-flight process,
# missing state, missing wrapper — plus proof it writes nothing and delivers no
# wrapper over the one that opened the cutover.
# The production deadlock, reproduced against the real wrapper: a live managed
# cron block whose hash cannot match a state recording `absent`, no saved block
# to restore, and emergency-disable proven to be an outage rather than a
# recovery. Pinned so nobody "fixes" the recovery path by loosening it.
stage "Cutover stuck-state reproduction (the deadlock is real)"
npm run test:cutover-stuck-repro

stage "Cutover resume recovery (refuses every state but one)"
npm run test:cutover-resume-recovery

# A cutover epoch belongs to exactly ONE wrapper. preflight always recorded the
# hash but nothing read it back, so two wrappers on one host could take turns
# driving a single state record — which is precisely the state that delivering
# a fixed wrapper beside the installed one would create. Also pins the escape
# hatch: preflight must never be gated by this, or a mismatch becomes another
# unfinishable cutover.
# A forwarded recovery invocation must not ride a master opened without
# forwarding: the shared ControlPath keys only on user/host/port, so an
# unforwarded phase leaves a master a later forwarded phase silently reuses,
# arriving with no agent and failing DB auth with "Permission denied".
stage "SSH multiplex isolation (forwarded calls get their own connection)"
npm run test:ssh-multiplex-isolation

stage "Cutover wrapper identity (one epoch, one wrapper)"
npm run test:cutover-wrapper-identity

# The corrected wrapper has to reach the host WITHOUT overwriting the one that
# opened the stuck epoch, so it is installed into an isolated, digest-pinned
# package instead. The dangerous failure is not "it does not install" — it is
# "it installs, and the destination quietly resolved into ${REMOTE_APP_DIR}/cutover
# anyway", which a string comparison cannot see. Proven against a shell-level
# docker fake: tags and malformed digests refused, the installed directory
# snapshotted byte-for-byte across install and a real phase run, symlinked
# destinations refused by realpath, and the extraction container removed on both
# the success and the failure path.
stage "Cutover runner package (isolated, digest-pinned, never overwrites the installed wrapper)"
bash -n scripts/cutover-runner-package-check.sh
npm run test:cutover-runner-package

# The 2026-07-30 severance. A preflight lost its invoker mid scratch-restore and
# left an 11 GB orphaned database plus a 25 GB unmanifested dump, and NOTHING
# reported either: the scratch drop ended `|| true`, and artifact reclamation
# compared against the epoch the state record had COMMITTED — which preflight
# only writes at the end, so a run could never reclaim its own artifact. These
# three cover the cleanup contract, the artifact-binding contract, and the
# operator driver that must now survive its invoker instead of taking the
# credential down with it.
stage "Cutover scratch cleanup (proven absent, or a real failure)"
bash -n scripts/cutover-scratch-cleanup-check.sh
npm run test:cutover-scratch-cleanup

# The 2026-08-04 blocker: `migrate` refused because the capacity sample it reads
# is produced only by the DB-host healthcheck timer, which `quiesce` must stop.
# 137 GB was free; the gate failed purely on the age of its evidence, with the
# site already down. migrate now refreshes that sample itself and gates on the
# evidence rather than on the sampler's exit code.
stage "Cutover migration capacity sample (migrate refreshes its own evidence)"
bash -n scripts/cutover-migration-capacity-sample-check.sh
npm run test:cutover-migration-capacity-sample

stage "Cutover self-cleanup (reclaims only its own unreferenced artifact)"
bash -n scripts/cutover-self-cleanup-check.sh
npm run test:cutover-self-cleanup

# Same 2026-08-04 blocker, one layer up: once `migrate` refused, the epoch sat at
# fingerprint-pre with a stale artifact and the single-epoch guard's `phase_chain
# = "preflight"` proxy left no sanctioned way to open a fresh one. The guard now
# checks the invariant it was standing in for — a fully reversible chain, and
# production proven restored — instead of the proxy.
stage "Cutover supersede guard (refuses by default, allows only a reversible chain)"
bash -n scripts/cutover-supersede-guard-check.sh
npm run test:cutover-supersede-guard

stage "Operator hardening (disconnect survival, ordered teardown, non-vacuous evidence)"
bash -n scripts/operator-hardening-check.sh
npm run test:operator-hardening

stage "Pre-change schema upgrade seam (branch point)"
npm run test:schema-upgrade-seam

# The commit production is ACTUALLY running, recorded in the baseline file.
stage "Pre-change schema upgrade seam (deployed production baseline)"
baseline="$(tr -d '[:space:]' < deploy/PRODUCTION_BASELINE_SHA)"
echo "production baseline: ${baseline}"
SCHEMA_UPGRADE_PRE_CHANGE_REF="${baseline}" npm run test:schema-upgrade-seam

# LAST, deliberately. Every step above has finished touching the tree — notably
# the wrapper manifest — so this is the only point at which "the tree is clean"
# is a claim about the tree that will actually be committed.
stage "Release owner references are current (LAST — the tree is final here)"
npm run check:release-owner

printf '\n%s PASS — %d stages\n' "${LABEL}" "${STAGE}"
