#!/usr/bin/env bash
# The canonical database-seams sequence. ONE list, run by CI and by humans.
#
# WHY THIS EXISTS. The CI job used to spell out ~20 steps inline, and the local
# habit was to run "the ones that seemed relevant". Those two lists drifted, and
# the drift was invisible until a push failed: a guard ran green locally, was
# never re-run on the final tree, and CI executed a slightly different set in a
# different order. A verification you cannot reproduce exactly is not a
# verification, so `.github/workflows/ci.yml` now invokes this file and so does
# `npm run verify:pre-push`. There is nothing left to keep in sync.
#
# ORDER IS PART OF THE CONTRACT. The release-owner guard runs LAST, after every
# other check has had its chance to modify the tree (the wrapper manifest in
# particular is regenerated by a step below). Running it first — as CI did —
# checks a tree that no longer exists by the time the job ends.
set -euo pipefail

cd "$(dirname "$0")/.."

LABEL="[verify-db-seams]"
STAGE=0

stage() {
  STAGE=$((STAGE + 1))
  printf '\n%s ── %02d %s\n' "${LABEL}" "${STAGE}" "$1"
}

# FIRST, and cheap. A semantically invalid workflow is rejected by GitHub before
# any job is created — the run completes as failure with jobs: [], no check runs
# and no logs — so CI structurally cannot catch it. Only a local check can.
stage "Workflow semantics (undefined needs, cycles, malformed steps)"
npm run check:workflows

stage "Migrations from zero"
npm run test:migrations-from-zero

stage "Disaster-recovery backup and restore seam"
npm run test:dr-restore-seam

stage "Staged idle worker seam (real worker, real PostgreSQL)"
npm run test:staged-worker

stage "Native ad decision database seam"
node --import tsx scripts/ephemeral-postgres-native-ad-decision-seam.ts

stage "Provider fixture seam"
npm run test:provider-fixture-seam

stage "Sync retention, growth and release seam"
npm run test:sync-retention-seam

stage "Release-gate plan and coalescing seam"
npm run test:release-gate-plan-seam

stage "Legacy import replay seam"
npm run test:legacy-replay-seam

stage "Google Ads date freshness seam (F1-F19)"
npm run test:google-ads-finality-seam

stage "Cutover wrapper package is current"
bash -n scripts/hetzner-sync-cutover.sh
bash -n scripts/cutover-wrapper-package.sh
bash -n scripts/cutover-real-postgres-harness.sh
bash -n scripts/cutover-wrapper-build-context-check.sh
bash -n scripts/check-release-owner-references.sh
bash -n scripts/verify-database-seams.sh
npm run test:cutover-wrapper-package

# A STATIC assertion that the wrapper is inside the Docker build context and
# captured by an existing COPY. NOT a container smoke test: no image is built.
stage "Cutover wrapper build-context assertion (static, not a smoke test)"
npm run test:cutover-build-context

# Every phase plus the negative controls against a REAL ephemeral PostgreSQL and
# a split app-host/DB-host command surface.
stage "Cutover state-machine harness (real PostgreSQL)"
npm run test:cutover-harness

# Admission over the REAL exported entrypoints, not a source scan.
stage "Entrypoint admission refusal seam"
npx vitest run lib/sync/entrypoint-admission.test.ts

stage "Entrypoint admission real-database seam"
npm run test:entrypoint-admission-seam

stage "Provider selection race seam"
npm run test:selection-race-seam

stage "Shopify install context seam"
npm run test:shopify-install-seam

stage "Shopify grant race seam"
npm run test:shopify-grant-race-seam

stage "Shopify install-context read authority seam"
npm run test:shopify-context-access-seam

# Fail-closed proof for the ORDINARY deploy path: a release carrying
# deploy/CUTOVER_REQUIRED must not be migratable outside the cutover lock.
stage "Ordinary deploy refuses a cutover-required release"
bash -n .github/scripts/hetzner-remote.sh
# The marker is present only while a cutover is PENDING; the commit after a
# completed cutover removes it. What must always hold is that the marker and the
# delivered manifest AGREE.
if [ -f deploy/CUTOVER_REQUIRED ]; then
  echo "cutover pending: deploy/CUTOVER_REQUIRED present"
  grep -q '^cutover_required=yes$' scripts/cutover-wrapper.manifest || {
    echo "deploy/CUTOVER_REQUIRED exists but the manifest does not say cutover_required=yes" >&2
    exit 1
  }
else
  echo "no cutover pending: deploy/CUTOVER_REQUIRED absent"
  grep -q '^cutover_required=no$' scripts/cutover-wrapper.manifest || {
    echo "deploy/CUTOVER_REQUIRED is absent but the manifest still says cutover_required=yes; run npm run cutover:package" >&2
    exit 1
  }
fi
grep -q 'deploy/CUTOVER_REQUIRED' .github/scripts/hetzner-remote.sh
# The grep proves the string is present; it cannot prove the ORDER, which is
# what matters. This also carries R1-R3, the production release boundary.
npm run test:deploy-gate-ordering
# The runbook must name the path that exists ON THE HOST.
installed=/var/www/adsecute/cutover/hetzner-sync-cutover.sh
grep -q "${installed}" docs/global-sync-rollout-runbook.md || {
  echo "the runbook does not name the installed wrapper path ${installed}" >&2
  exit 1
}
if [ -f deploy/CUTOVER_REQUIRED ]; then
  grep -q "${installed}" deploy/CUTOVER_REQUIRED || {
    echo "deploy/CUTOVER_REQUIRED does not name ${installed}" >&2
    exit 1
  }
fi
! grep -qE '^\s*(\./)?(\.github/)?scripts/hetzner-sync-cutover\.sh' docs/global-sync-rollout-runbook.md || {
  echo "the runbook still instructs running the repository copy of the wrapper" >&2
  exit 1
}

# The deploy carries a registry credential to a long-lived host. Executed, not
# asserted: token never in argv or the phase environment, ephemeral
# DOCKER_CONFIG cleaned on every exit path, failed login aborts before the
# phase runs, and the anonymous legacy-rollback path still works.
stage "Deploy registry auth (ephemeral credential handling)"
npm run test:deploy-registry-auth

# The recovery out of a half-finished cutover must refuse every state shape but
# one. Executed against synthetic state: wrong/reordered/already-resumed chain,
# invalidated, foreign release, wrong wrapper version, in-flight process,
# missing state, missing wrapper — plus proof it writes nothing and delivers no
# wrapper over the one that opened the cutover.
# The production deadlock, reproduced against the real wrapper: a live managed
# cron block whose hash cannot match a state recording `absent`, no saved block
# to restore, and emergency-disable proven to be an outage rather than a
# recovery. Pinned so nobody "fixes" the recovery path by loosening it.
stage "Cutover stuck-state reproduction (the deadlock is real)"
npm run test:cutover-stuck-repro

stage "Cutover resume recovery (refuses every state but one)"
npm run test:cutover-resume-recovery

# A cutover epoch belongs to exactly ONE wrapper. preflight always recorded the
# hash but nothing read it back, so two wrappers on one host could take turns
# driving a single state record — which is precisely the state that delivering
# a fixed wrapper beside the installed one would create. Also pins the escape
# hatch: preflight must never be gated by this, or a mismatch becomes another
# unfinishable cutover.
stage "Cutover wrapper identity (one epoch, one wrapper)"
npm run test:cutover-wrapper-identity

stage "Pre-change schema upgrade seam (branch point)"
npm run test:schema-upgrade-seam

# The commit production is ACTUALLY running, recorded in the baseline file.
stage "Pre-change schema upgrade seam (deployed production baseline)"
baseline="$(tr -d '[:space:]' < deploy/PRODUCTION_BASELINE_SHA)"
echo "production baseline: ${baseline}"
SCHEMA_UPGRADE_PRE_CHANGE_REF="${baseline}" npm run test:schema-upgrade-seam

# LAST, deliberately. Every step above has finished touching the tree — notably
# the wrapper manifest — so this is the only point at which "the tree is clean"
# is a claim about the tree that will actually be committed.
stage "Release owner references are current (LAST — the tree is final here)"
npm run check:release-owner

printf '\n%s PASS — %d stages\n' "${LABEL}" "${STAGE}"
